### ISSUE TITLE
404 presents runtime error

### ISSUE THREAD

**Issue by ambs** [PerlDancer/Dancer2#1001]
With latest Dancer version, when an unknown route is called, the 404 page shows a runtime error, with backtrace et al. Not sure this is desired.

To test, simple bootstrap a new app, plack it up, and try to access some strange route.

Cheers

**Comment by veryrusty** [comment]
Is it the stack trace, or the "Runtime Error" text that's not desired? The text is the default of the error `type` attribute, so could be set when the 404 error is thrown.

If the config setting `show_errors` is true, then `public/nnn.html` will be ignored and either `views/nnn.tt`, `error_template` template, or a default error template (which includes the stack trace) will be used.  (which is noted in the `environments/development.yml` file in a bootstrapped app, and possibly elsewhere).

**Comment by ambs** [comment]
I think 404 is not an error of the application. It is a legitimate answer from the server.

So, why to present a backtrace/error message...? No Perl code failed. It just did not found the route. And specially, there wasn't any Runtime error.

**Comment by racke** [comment]
I totally agree with @ambs. This is really confusing, especially for our flock of Dancer newbies.

**Comment by ambs** [comment]
:+1:

**Comment by veryrusty** [comment]
There is a more general issue; is a stack trace applicable for *any* "error" with a `4xx` code? 
From the reasoning from @ambs and @racke above, I think not.

In other words: stack traces should only be included for `5xx` errors codes when `show_errors` is true.
(which is simple to implement)

**Comment by veryrusty** [comment]
If `show_errors` are true, do we still want the rest of the information ( $env, config, etc) on the error page  for `4xx` codes?

**Comment by ambs** [comment]
I would say no. I would prefer a simple 404 - Not Found - Route that was not found.

But happy with other ideas :)

**Comment by racke** [comment]
Yeah, I agree with @ambs. After all, 404 isn't necessary an actual error.

**Comment by xsawyerx** [comment]
We shouldn't be providing a stacktrace for a 4xx, only 5xx. Who's fixing this? :)

**Comment by veryrusty** [comment]
Thanks for the concise summary @xsawyerx . Pr on its way very soon :)

**Comment by ambs** [comment]
:+1:

**Comment by xsawyerx** [comment]
@veryrusty my summary was just agreeing with you fully. You described it aptly. :)

Fix by @veryrusty (#1007) merged. Thanks everyone! :heart:
