### ISSUE TITLE
Dancer2::Manual::Testing

### ISSUE THREAD

**Issue by ramortegui** [PerlDancer/Dancer2#1003]
Just to clarify on Cookies section:

In order to make it work the "cookie jar" functions:
* $jar->extract_cookies($res);
* $jar->add_cookie_header($req);

The requests needs to have a complete URL, and for testing purposes could be:  
my $server = 'http://localhost';
$test->request( GET $server . '/login', ... );
$req = GET $server . '/logout';

**Comment by xsawyerx** [comment]
Completely forgot about that. You're absolutely right!

**Comment by cromedome** [comment]
Did this get fixed and the issue not get closed? Unless I am missing something really obvious, I don't see where the examples don't do this, and there's a nice note at the end explaining what you just mentioned :)

**Comment by rleir** [comment]
Hi Jason, if I hear you right, this issue should get closed. When you get a moment, thanks!
