### ISSUE TITLE
required Moo version is too old?

### ISSUE THREAD

**Issue by ambs** [PerlDancer/Dancer2#1004]
Hey

I had 

     Moo                 1.003001
     Role::Tiny        1.003002 
     Module::Runtime   0.013

Dancer2 tests failed (a lot of Internal Server errors).
Updated Moo to latest (so, 2.000002) and it updated Role::Tiny to 2.000001 and Module::Runtime to 0.014. And now tests pass.

So, unless someone knows what changed and on what version changed, I suggest requesting a higher version of Moo.

``````

**Comment by veryrusty** [comment]
Without spending time digging through what the actual minimum version of Moo we support, I suggest we specify Moo 2.000001 as the minimum as this uses strictures 2, which fatalizes only a subset of warnings.

**Comment by ambs** [comment]
What would be my decision too :-)

**Comment by xsawyerx** [comment]
Go for it!

**Comment by ambs** [comment]
See https://github.com/PerlDancer/Dancer2/pull/1006
As simple s it is, I could go and merge ahead, but I am sure I did something wrong O:-)

**Comment by xsawyerx** [comment]
#1006 merged, closing this. @ambs++ :+1:
