### ISSUE TITLE
It's necesary to install perl 5.20

### ISSUE THREAD

**Issue by renatolrr** [PerlDancer/Dancer2#1005]
I don't found the pre-reqisite un the documentación .
I must to intall perl 5.20

**Comment by racke** [comment]
Please elaborate, other versions of Perl work as well with Dancer.

**Comment by renatolrr** [comment]
I use Debian 8 testing , perl 5.14.4 and not found the directory perl 5.20

**Comment by xsawyerx** [comment]
@renatolrr why do you say you need to install 5.20? We're not using Dancer2 with 5.20.

**Comment by veryrusty** [comment]
The Debian team have libdancer2-perl 0.162000 for sid with perl 5.13.9 as minimum perl version. They would yell if something like this was amiss. We test back to perl 5.10 on TravisCI. There is nothing in those logs to indicate 5.20 is needed.

On a perl 5.14.4 image (thanks docker!),  `cpanm Dancer2` fails with the latest App::Cmd release (v0.328). Cpantesters has that as a general fail below perl 5.16. Installing the previous App::Cmd release or a newer Pod::Usage is sufficient. I'll report this upstream.

**Comment by renatolrr** [comment]
Thank, i install perlbrew and perl 5.20, perl 5.14
cpan dancer2 (using perl 5.20)
And now it's running under perl5.14
Thk and close

**Comment by xsawyerx** [comment]
I had thought about removing `App::Cmd` and started it, but never got around to finishing. :/
