### ISSUE TITLE
Deprecation warning seems off

### ISSUE THREAD

**Issue by nunorc** [PerlDancer/Dancer2#1008]
When running the following application:
```
use Dancer2;
use Dancer2::Plugin::Database;
use Dancer2::Plugin::Growler;
use Dancer2::Plugin::Passphrase;

set plugins => {
  Database => { driver=>'SQLite', database=>'/tmp/foo' }
};

get '/' => sub { 
  my $whatever = database->quick_select('something', {});

  return "ok";
};

dance;
```
I can see the following message in the logs:
```
DEPRECATED: Dancer2::Plugin::Database calls 'dsl' instead of '$dsl->dsl'.
  at /Library/Perl/5.18/Dancer2/Plugin/Database.pm line 30.
```
Which seems off, because there is no actual issue with the Database plugin. Also, if we remove the use statement to load the other plugins the warning no longer appears. Which also happens if we exchange the order in which the plugins are loaded (e.g. load the Database plugin last).

Is anything wrong with this example, or I'm missing something? Or is the deprecation warning actually incorrect?

My $local modules:
```
Dancer2 is up to date. (0.162000)
Dancer2::Plugin::Database is up to date. (2.13)
Dancer2::Plugin::Passphrase is up to date. (3.0.2)
Dancer2::Plugin::Growler is up to date. (0.03)
```

**Comment by veryrusty** [comment]
Thanks @nunorc . Linking to to the Pr #976 which has a hack to silence the (incorrect) warning.

**Comment by ambs** [comment]
Should be fixed on master. Cheers.

**Comment by nunorc** [comment]
No deprecation warning shows up with my previous example using master.

Thank you.

**Comment by ambs** [comment]
\o/
