### ISSUE TITLE
delayed with template error

### ISSUE THREAD

**Issue by jfallmann** [PerlDancer/Dancer2#1009]
I tried to use the new delayed method with templates as content like this,

get '/test/:*?' => sub {
	my $id	      = params->{'id'};
	my $blub	      = params->{'blub'};
    delayed {
        flush;
        content template 'results', {
            'id'  => $id,
            'bla' => $blub
        };
        ### Process further
        push @tmp, "String";

        content template 'results', {
            'id'  => $id,
            'bla' => $blub,
            'tmp' => \@tmp
        };
        done;
    };
};

which results in 
Odd number of elements in anonymous hash at Dancer2/Core/Request.pm line 345.
Odd number of elements in anonymous hash at Dancer2/Core/Request.pm line 345.
Can't call method "cookies" on an undefined value at Dancer2/Core/App.pm line 1046.

Removing flush does not help,
if I try a string as content it works, but the layout.tt is ignored for this route

any help highly appreciated

**Comment by girlwithglasses** [comment]
You might be better off calling Template::Toolkit directly as Dancer2's `template` call does more than just render the template -- it adds various config and request-related data to every template.

Your new `delayed` section might look like this:

    delayed {
    	my ( $id, $blub ) = do_something_cool_here();
    	my $tt = Template->new($tmpl_config) || die "Template error: $Template::ERROR\n";
    	my $out;
    	# note third argument -- scalar reference
	$tt->process('template_name', { id => $id, blah => $blub }, \$out) || die $tt->error() . "\n";

    	flush;
    	content $out;
    	done;
    }

Check the Template::Toolkit documentation for details on how to instantiate and process templates.

**Comment by jfallmann** [comment]
Hi,
Thanks for your help!
/will try asap, was without stable internet for the last days.

**Comment by jfallmann** [comment]
This removes the errors, however I can not render two templates from one route, which was the actual reason I started to use delayed, I fear this was unclear as my initial question was badly formatted.


    get '/test/:*?' => sub {
        my $id = params->{'id'};
        my $blub = params->{'blub'};
        delayed {
	    my $tt = Template->new(
		{INCLUDE_PATH => "$path",
		 WRAPPER  => 'layout.tt',			 
		 RELATIVE => 1,
		}) || die "Template error: $Template::ERROR\n";
           $tt->process('view.tt', {
                'id' => $id,
                'bla' => $blub
            };
           ### Process further
           push @tmp, "String";
	    my $tt2 = Template->new(
		{INCLUDE_PATH => "$path",
		 WRAPPER  => 'layout.tt',			 
		 RELATIVE => 1,
		}) || die "Template error: $Template::ERROR\n";
           $tt2->process('view.tt', {
                  'id'  => $id,
                 'bla' => $blub,
                 'tmp' => \@tmp
           };
          done;
        };
    };


What I'm looking for is a way to render a template with part of the results to the user to see while I continue processing and when I'm done I want to show the final template with all results.

Is this possible or am I completely on the wrong track?

**Comment by jfallmann** [comment]
I suppose this is not really an issue and will transfer the question to the mailing list,
thanks a lot for your help!
