### ISSUE TITLE
before_template(_render) hook broken since 0.16200

### ISSUE THREAD

**Issue by b10m** [PerlDancer/Dancer2#1013]
While upgrading to 0.16200 I noticed plugins that use the before_template hook die with:
> [TestApp:23715] error @2015-09-29 18:20:25> Route exception: Can't call method "params" on an undefined value at /usr/local/perlbrew/perls/5.19.3/lib/site_perl/5.19.3/Dancer2/Core/Role/Template.pm line 180. in /usr/local/perlbrew/perls/5.19.3/lib/site_perl/5.19.3/Dancer2/Core/App.pm l. 1273

Example to replicate this:

App (test) code:

```perl
use Plack::Test;
use HTTP::Request::Common;

{
    package TestApp;
    use Dancer2;

    hook before_template => sub {
        # do something, or nothing...
    };

    set template => 'template_toolkit';

    get '/' => sub {
        template 't.tt', { hi => "hello" },
    };
};

my $test = Plack::Test->create( TestApp->to_app );
my $res = $test->request(GET "/");

print $res->content;
```

With a very basic template named ```views/t.tt```

```perl
[% hi %]
```
The problem, I guess, is the order of operations here. When I move the ```set template => 'template_toolkit';``` above the ```hook```, all works as expected, but that'd means I have to use constructs like this to use plugins:

```perl
BEGIN {
    use Dancer2;
    set template => 'template_toolkit';
};
use Dancer2::Plugin::Something::That::Adds::A::Hook;
```

Not ideal.

**Comment by b10m** [comment]
Oh, the real issue comes from the fact that ```$self``` doesn't have a ```->request``` (yet) in ```Dancer2::Core::Role::Template::_prepare_tokens_options```

**Comment by xsawyerx** [comment]
The risk of allowing templates to be rendered outside a request is that you might want to render a template that requires something available in a request (the request object, the request stash, etc.).

I'm not sure why calling the `set template` after the `before` hook causes a crash, though...

**Comment by xsawyerx** [comment]
I see the problem happens because setting the `before` hook clears the variables used later in the template. I'm trying to solve it without having to allow calling `template` outside a request.

**Comment by xsawyerx** [comment]
I have a fix for review in #1092. @b10m++ @SysPete++

**Comment by b10m** [comment]
:+1: Seems to work for me. @xsawyerx++ for the digging (I know how horrible it must've been to debug this ;)

**Comment by xsawyerx** [comment]
@b10m Your test made it exceedingly easier - especially the note on location of `set` statement vs `hook`. :)

**Comment by veryrusty** [comment]
Thanks for the initial report and your suggested fix @b10m!
