### ISSUE TITLE
Using Dancer2 will unconditionally import some 'import' symbol

### ISSUE THREAD

**Issue by internetionals** [PerlDancer/Dancer2#1022]
When you do:

    package Foo;
    use Dancer2;
    use Exporter qw( import );

You get:

    Subrouting Foo::import redefined at /usr/share/perl/5.20/Exporter.pm line 33.

But the exported "import" method from Dancer2 is not functionally equivalent with the one from Exporter.

And the following won't fix the problem:

    use Dancer2 '!import';

**Comment by xsawyerx** [comment]
This is not a bug, but expected behavior from Dancer2. Dancer2 will override your `import` subroutine and will provide it's own. That's how `use MyApp` actually loads things properly.

You shouldn't be using `Exporter` and `Dancer2` in the same package.

**Comment by hvoers** [comment]
But we do it in D1.
How should we export subs that call DSL words in D2?

**Comment by xsawyerx** [comment]
@hvoers The way it works in D2 is that we provide the App class with our own `import` method that allows doing things like:

    use MyApp;
    use MyApp::API appname => 'MyApp';

This is done because when `MyApp::API` uses `Dancer2`, it provides it with an `import` method (just like `Exporter` would do when you use that). This is why you can't use both. Also, you really shouldn't. Dancer is for DSL, not a helper class.

**Comment by xsawyerx** [comment]
@hvoers I hope I answer your question, but if I didn't, I apologize and would be happy to explain what I didn't understand I asked. :)

**Comment by hvoers** [comment]
On Tue, 13 Oct 2015, Sawyer X wrote:

> @hvoers The way it works in D2 is that we provide the App class with our own `import` method that allows doing things like:
>
>    use MyApp;
>    use MyApp::API appname => 'MyApp';
>
> This is done because when `MyApp::API` uses `Dancer2`, it provides it with an `import` method (just like `Exporter` would do when you use that). This is why you can't use both. Also, you really shouldn't. Dancer is for DSL, not a helper class.

What would you call this, a DSL or a helper:

sub documentroot {
     return config->{public_dir} || config->{public};
}

**Comment by xsawyerx** [comment]
A function.

What I'm trying to say is that you shouldn't be writing something like:

    use MyApp qw<func1 func2>;

Because Dancer2 needs those parameters for Dancer2-related stuff:

    use MyApp 'nopragmas'; # for example
    use MyApp appname => 'OtherApp'; # another example

**Comment by hvoers** [comment]
PK. So I can't write:

    package MyLib;
    use Dancer2;

But what about Dancer2::Plugin::Things Do they export an import?
Can I write:

    package MyLib;
    use Dancer2::Plugin::Helpers;
    sub documentroot { return dancer_config->{public_dir}; }

?

**Comment by xsawyerx** [comment]
@hvoers I think so... did you try and it failed?

**Comment by hvoers** [comment]
@xsawyerx  I did try and it did not fail.
Now I have to think about "Do I want Plugin::Helpers?".
Dunno yet.
