### ISSUE TITLE
D2P2 - return empty hashref instead of undef when there is no config

### ISSUE THREAD

**Issue by yanick** [PerlDancer/Dancer2#1026]
See https://github.com/PerlDancer/Dancer2/pull/1010#issuecomment-147665846

**Comment by xsawyerx** [comment]
:+1: Absolutely!

(I did the same with `captures` in 3ac88bb66df37405a9cc3d405f4c3b2e87d75a47.)

**Comment by racke** [comment]
The other question is why is there no config :-).

**Comment by yanick** [comment]
@racke No config is a perfectly cromulent thing to happen. It just means that there was no

```
plugins:
   Foo:
     something: blah
```

for plugin `Foo`, which will happen, for example, if the app programmer goes for all defaults.

**Comment by racke** [comment]
I know, but I just suspect that sometimes the config for a plugin used by another plugin is hidden in the wrong drawer.

**Comment by veryrusty** [comment]
This was applied in commit 64c50c49.  Thanks everyone!
