### ISSUE TITLE
Manual still mentions context object

### ISSUE THREAD

**Issue by veryrusty** [PerlDancer/Dancer2#1031]
Need to revise the section of Dancer2::Manual on [The Session keyword]( https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Manual.pod#the-session-keyword).

It discusses the "context" object, which was removed over a year ago.

**Comment by xsawyerx** [comment]
No one picked it up and it was annoying me (plus was wholly incorrect as documentation at this point), so I fixed it.
