### ISSUE TITLE
DSL keyword for request headers

### ISSUE THREAD

**Issue by veryrusty** [PerlDancer/Dancer2#1039]
via @mickeyn:

>  want a keyword to access the request headers, that provides headers as a Hash::MultiValue.

**Comment by mickeyn** [comment]
background:
the current version of D2 allows access only through request->headers, since we don't force installed Plack version, this may be either HTTP::Headers or HTTP::Headers::Fast, both not providing a HMV type of access which would be consistent with the other *_parameters methods

**Comment by xsawyerx** [comment]
Up until the current version (including) it might have returned `HTTP::Headers` but from the next version we'll require the minimum version of `Plack` that introduces the `HTTP::Headers::Fast`.

Picking the DSL keyword would probably be the hardest part.

**Comment by mickeyn** [comment]
why not 'header_parameters' ?

AFAIK, HTTP::Headers::Fast doesn't use HMV, I suggest creating one lazily on access.
returning the internal object from Plack::Request doesn't seem like a correct approach, as this may change again.

**Comment by xsawyerx** [comment]
I like `header_parameters`.

**Comment by xsawyerx** [comment]
Although it does seem.. a bit odd. It's not really parameters. It's just header values.

**Comment by mickeyn** [comment]
request_headers ?

though, in that case, we might want to introduce response_header/s and deprecate the implicit ones.

**Comment by xsawyerx** [comment]
I think those are good ideas. To summarize:

* Currently `headers` accesses the response headers.
* Introduce `response_headers` to access the response headers more explicitly.
* Deprecate ambiguous `headers`.
* Introduce `request_headers` to access the request headers.

Votes?

Pinging (in no particular order):
@racke @mickeyn @veryrusty @sukria @shumphrey @cromedome @ambs @SysPete @bigpresh @dams @yanick

**Comment by racke** [comment]
On 12/16/2015 10:05 PM, Sawyer X wrote:
> I think those are good ideas. To summarize:
> 
>   * Currently |headers| accesses the response headers.
>   * Introduce |response_headers| to access the response headers more explicitly.
>   * Deprecate ambiguous |headers|.
>   * Introduce |request_headers| to access the request headers.
> 
> Votes?
> 

+1

> Pinging (in no particular order):
> @racke <https://github.com/racke> @mickeyn <https://github.com/mickeyn> @veryrusty <https://github.com/veryrusty> @sukria <https://github.com/sukria> @shumphrey <https://github.com/shumphrey> @cromedome <https://github.com/cromedome> @ambs <https://github.com/ambs> @SysPete <https://github.com/SysPete> @bigpresh <https://github.com/bigpresh> @dams <https://github.com/dams> @yanick <https://github.com/yanick>
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/PerlDancer/Dancer2/issues/1039#issuecomment-165239212>.
> 


-- 
Perl and Dancer Development

Visit our Perl::Dancer conference 2015.
More information on https://www.perl.dance.

**Comment by ambs** [comment]
It it keeps things working for now, go for it. :-)

**Comment by xsawyerx** [comment]
@ambs We still haven't resolved what "deprecation" means, but as said previously, it could stay deprecated forever, as long as it's not in the way. :)

**Comment by mickeyn** [comment]
+1 (tuurlijk)

**Comment by SysPete** [comment]
+1 for request_headers/response_headers

**Comment by dams** [comment]
+1

**Comment by veryrusty** [comment]
+1 for request_headers/response_headers

**Comment by veryrusty** [comment]
Do we leave `push_header`, or rename that `push_response_header` ?

**Comment by mickeyn** [comment]
@veryrusty++

I vote for renaming (as in keep the old one with deprecation warning for a while) so the DSL moves towards having clearer meaning names.

**Comment by xsawyerx** [comment]
:+1: for rename `push_header` as `push_response_header`, the way @mickeyn described it.

**Comment by veryrusty** [comment]
Closing now that #1085 has been merged.  Thanks all.
