### ISSUE TITLE
In-config no_server_tokens does not work.

### ISSUE THREAD

**Issue by slashbeast** [PerlDancer/Dancer2#1046]
Hello,

It seems that the no_server_tokens if put in config is completely ignored.

Adding 

    no_server_tokens: 1

to config.yml or environments/*.yml does not work. Dancer still sends Server header with it's version.

As per documentation

    no_server_tokens (boolean)
    If set to true, Dancer2 will not add an "X-Powered-By" header and also append the Dancer2 version to the "Server" header. Default to false - adding.

This seems to be also wrong, as there's no X-Powered-By at all, just the Server header with version.

Headers with config.yml 'no_server_tokens: 1'

    HTTP/1.1 200 OK
    Server: Perl Dancer2 0.161000
    Content-Type: text/html; charset=UTF-8
    Content-Length: 5304
    Date: Sun, 25 Oct 2015 19:38:39 GMT
    Connection: keep-alive

Headers when starting application with DANCER_NO_SERVER_TOKENS=1 env variable:

    HTTP/1.1 200 OK
    Content-Type: text/html; charset=UTF-8
    Content-Length: 5304
    Date: Sun, 25 Oct 2015 19:39:49 GMT
    Connection: keep-alive

Meaning, setting it thru env variable does works.

dev-lang/perl-5.22.0
dev-perl/Dancer2-0.161.0

**Comment by cromedome** [comment]
The code supports this. If you look here:
https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Core/Runner.pm#L99-L101

the config files are never consulted. I'll start looking at this.

**Comment by slashbeast** [comment]
Hello,

Have you managed to do anything regarding this issue? Should the documentation be changed or dancer2 aligned to support that?

**Comment by xsawyerx** [comment]
@cromedome ping. :)

**Comment by cromedome** [comment]
Sorry @slashbeast, $day_job has been in the way of getting this done. For now, perhaps we should patch the docs for now and fix it in an upcoming release. What do you think?

**Comment by xsawyerx** [comment]
This is considered a bug. I'll work on it.

**Comment by xsawyerx** [comment]
Fix provided in #1100.

**Comment by xsawyerx** [comment]
#1100 merged, I consider it fixed, and closing the issue.

@slashbeast Thank you for reporting!

**Comment by slashbeast** [comment]
I totally forgot about this one and just got notifaction that it's fixed.

Many thanks for fixing it!

**Comment by xsawyerx** [comment]
@slashbeast++

:smile:
