### ISSUE TITLE
serializer + before_serializer weird behavior

### ISSUE THREAD

**Issue by mickeyn** [PerlDancer/Dancer2#1052]
tried to set the ref to be serialized in the before_serializer hook rather than the route handler, didn't work so well.

here's a minimized version to show the problem:
code: http://pastebin.com/5Gg3CSQS
output: http://pastebin.com/wmcFwbaZ

bug?

**Comment by xsawyerx** [comment]
Nope.

    package BUG;
    use Dancer2;
    set serializer => 'JSON';

    hook before_serializer => sub {
        $_[0] = { blah => 'blah' };
    };

    get '/' => sub {
        print STDERR "do nothing in the route handler\n";
    };

**Comment by mickeyn** [comment]
thanks @xsawyerx ;)

so what happens here is that $content is passed to the hook (undefined value), since @_ is aliasing the same input variable (which is later passed to the serializer) we can set it there.
nice.

**Comment by xsawyerx** [comment]
@mickeyn++ Thanks for adding an explanation of how it works!

**Comment by mickeyn** [comment]
ok, checked and this doesn't really work (@xsawyerx - we only checked a generalized function call outside this problem scope).

problem 1:
since the hook is executed through an intermediate execute_hook which copies @_ into @args and passes *it* down to the hook code, $_[0] is not an alias to the original $content (that's created in 'around serialize').

(minor) problem 2:
there's a check on $content and it's length, so the route handler has to return a value in any case to reach the hook execution.
(that can potentially be solved by moving the content check till after the hook - so I'm not worried about it).

I'm not blocked by this, solved my problem with a completely different approach, but this still bugs me :)

though I agree this is not a bug, it's still an open question -
how can I replace the content sent to the serializer after the route handler has run?
(I do believe the proper place should be the 'before_serializer' hook)

**Comment by xsawyerx** [comment]
@mickeyn Is this fixed by #1053?

**Comment by xsawyerx** [comment]
I guess so. :)
