### ISSUE TITLE
serializer error when set serializer as "JSON" 

### ISSUE THREAD

**Issue by gingerhot** [PerlDancer/Dancer2#1054]
I run "dancer2 -a appname" to create a new app, then "bin/app.pl", it works well.
Then I add "serializer: JSON" to config.yml , and I get a blank page in browser and have such error info:

```
 $ bin/app.pl
>> Dancer2 v0.163000 server 45189 listening on http://0.0.0.0:3000
[testapp:45189] core @2015-11-06 00:07:54> looking for get / in /Library/Perl/5.18/Dancer2/Core/App.pm l. 1205
[testapp:45189] core @2015-11-06 00:07:54> Entering hook core.app.before_request in (eval 77) l. 1
[testapp:45189] core @2015-11-06 00:07:54> Failed to serialize the request: hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /Library/Perl/5.18/JSON.pm line 154. in /Library/Perl/5.18/Dancer2/Core/Response.pm l. 250
[testapp:45189] core @2015-11-06 00:07:54> Entering hook core.app.after_request in (eval 77) l. 1
```

### my Perl version 

```
$ perl -v
This is perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)

Copyright 1987-2013, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

### my Dancer2 version
```
Dancer2 0.163000
```

And I tested it in a Ubuntu system, and same errors occurred.  Could you help me out of this?
Thanks~

**Comment by mickeyn** [comment]
hi @gingerhot,

Out of the box, the generated app created a route handler for " get '/' " which renders a template and returns the (string) output of its HTML processing.
As this returned content is not a ref (hash/array) the JSON serializer doesn't handle it.
What you need is to alter this part in the handler - try replacing the line:
    template ...;
with:
    return +{ ... };

**Comment by gingerhot** [comment]
@mickeyn Thanks for your reply~
It seems that the serializer in Dancer2 behaves differently with Dancer1? 
But the serializer config is global, If I set it to "JSON", what I should do when I really need the keyword "template" to render a page?

Thanks.

**Comment by mickeyn** [comment]
Why do you need a global serializer configuration, rather than per app? (you can have your JSON serving apps set it and the others not - seems to me like the right way to go here)

I'm not sure why you want to render a template in a JSON context, but even if you do - the way you use it (the OOTB example) is as a return value (which is not a ref, and JSON.pm doesn't like it - that's your set serializer in this case which is trying to serialize your return value)... of course, you can assign it into variables or wrap it in a ref it that actually makes sense to you.

**Comment by gingerhot** [comment]
thanks~
I think I got you, but my case is in the app there're some pages, and there're also some handlers for ajax requests, it's a mixture... so when I set serializer in config.yml,  it's a global setting in the app. I don't know how to construct it...

**Comment by mickeyn** [comment]
so what I suggest is have 2 apps, in one use "set serializer => 'JSON'" (not in config) and have it serve your ajax routes and the other without it to serve the HTML pages.

I highly recommend reading some of the articles in our last years' advent calendar as a good best-practices source for your API goals.
check out http://advent.perldancer.org/2014

**Comment by veryrusty** [comment]
There is one other option which is useful when the number of routes needing to serialize their response is _small_ [ think O(1) ]; do not set a serializer and use `Dancer2::Plugin::SendAs` to do the serialization on those routes.

If you find you are using `send_as` too often, then do as @mickeyn suggests; restructure into 2 apps.

**Comment by gingerhot** [comment]
@mickeyn Thanks a lot !  I'll read the advent articles.

@veryrusty I got it, very good advice, I'd have a try, thanks~
