### ISSUE TITLE
HVM and empty arrays in serialized body values

### ISSUE THREAD

**Issue by mickeyn** [PerlDancer/Dancer2#1055]
We have a small problem with HVM creation from deserialized body (tested with JSON) -
when the value of a JSON key is an empty array ([]), HVM will take it as an empty list of values so you can't represent it back as an arrayref or more importantly, diffrentiate it from a non-existing key in the JSON.

In the (deprecated) params, we still get it right.

example:

``` perl
package MyApp;
use Dancer2;

set serializer => 'JSON';

# curl -X POST -d'{"xxx"=>[]}'                                                                                                                                     
post '/' => sub {
    return {
        'body_parameters_xxx' => body_parameters->get('xxx'),
        'body_parameters_yyy' => body_parameters->get('yyy'),
        'params_xxx' => params->{'xxx'},
        'params_yyy' => params->{'yyy'},
    };
};
1;
```

output:

```
$ curl -X POST -d'{"xxx":[]}' http://0:3000/ | json_pp
{
   "params_yyy" : null,
   "body_parameters_xxx" : null,
   "body_parameters_yyy" : null,
   "params_xxx" : []
}
```

Any thoughts?

(related to issue: https://github.com/miyagawa/Hash-MultiValue/issues/11)

**Comment by xsawyerx** [comment]
If I recall correctly, we do this instead of `new` because if someone provides `foo` twice, we store it as arrayref instead of multi value key.

**Comment by mickeyn** [comment]
can you add the same key twice in serialized structure?

**Comment by xsawyerx** [comment]
The difference is that if you do it the way you suggest, then `foo=1&foo=2` becomes `foo=[1,2]` instead of `foo=1` (for `get`) and `foo=1,2` (for `get_all`).

**Comment by xsawyerx** [comment]
I'm not sure I'm making myself clear, but probably not well at this hour.

**Comment by mickeyn** [comment]
I was talking about the JSON that we deserialize from the body.

a side note, even if the JSON spec allows it, the serializer module we use doesn't support it anyway.

**Comment by cromedome** [comment]
Replacing with #1240 which is a newer issue that also covers this (making sure we don't lose anything by linking these issues though!).
