### ISSUE TITLE
Won't upload files

### ISSUE THREAD

**Issue by logust79** [PerlDancer/Dancer2#1065]
The most recent version (0.163000) stopped uploading files. 

    post '/foo' => sub {
        my $file = upload('upload');
        return (Dumper $file).' '.params->{upload};
    };

would return 

    $VAR1 = undef; Untitled.txt
If I call `$file->filename` or `$file->content`, it will simply throw an error, saying I'm calling method on an undefined value as `$file`. Did I do something wrong?

`params->{upload}` though would catch the upload file's name with no problem.

**Comment by perldj** [comment]
I use:
my $requestParams = request->params;
my $filename = $requestParams->{'files'};
my $upload_dir = '/tmp/';
my $filename = 
my $file2 = request->upload('files');
then
$file2->copy_to( $upload_dir . $filename );

From something like:
<form method="post" id="fileinfo" name="fileinfo" onsubmit="return submitForm();">
        <input type="file" name="files" required />
        <input type="submit" value="Click to Upload" />
    </form>

So, could be a docs issue?

**Comment by veryrusty** [comment]
@logust79 Are you setting the appropriate enctype attribute on your form? e.g.
```
<form method="post" action="/upload" enctype="multipart/form-data">
```

**Comment by logust79** [comment]
Strange. Things still not working for me. It gives:

    Can't call method "copy_to" on an undefined value at test_app.pl line 16.

This is what I do:

In test_app.pl:

    use Dancer2;

    get '/test' => sub {
		# this is the get content
		template 'test.tt', {
	
		};
    };

    post '/test' => sub {
        my $requestParams = request->params;
        my $filename = $requestParams->{'files'};
        my $upload_dir = 'temp/';
        my $file2 = request->upload('files');
    
        $file2->copy_to( $upload_dir . $filename );
    
    };
    dance;
And in test.tt,

    <!DOCTYPE html>
    <html lang='en'>
	<head>
		
	</head>
        <body>
	    <form method='post' id='main-form'>
		
		    <input type='file' name='files' />
					
		    <button type='submit' id='submit'>Submit</button>
				
	    </form>
  
       </body>
    </html>

And in config.yml

    # This is the main configuration file of your Dancer2 app
    # env-related settings should go to environments/$env.yml
    # all the settings in this file will be loaded at Dancer's startup.

    # Your application's name
    appname: "test"

    # The default layout to use for your application (located in
    # views/layouts/main.tt)
    # layout: "main"

    # when the charset is set to UTF-8 Dancer2 will handle for you
    # all the magic of encoding and decoding. You should not care
    # about unicode within your app when this setting is set (recommended).
    charset: "UTF-8"

    # template engine
    # simple: default and very basic template engine
    # template_toolkit: TT
    # template: "simple"

    template: "template_toolkit"

**Comment by logust79** [comment]
@veryrusty Magic!! I missed `enctype`!! Thank you so much!!
