### ISSUE TITLE
Plack can't pick up the config.yml settings. (Dancer2 0.163000)

### ISSUE THREAD

**Issue by logust79** [PerlDancer/Dancer2#1067]
Hello,
When I run my app as standalone, it causes no trouble. But when I call it with Plack or Starman, it failed to pick up the settings from config.yml. And all the `appdir` `view_dir` and `public_dir` are set to home directory by Plack. After changing the dirs to the correct ones in my app, it still doesn't work. This is only a problem with MacOS 10.11. It is no problem when I run it on Ubuntu. Can I do something to rectify it? 
Many thanks!

Error thrown:

	Error 500 - Internal Server Error

	Runtime Error

	Exception caught in 'core.app.before_request' filter: Hook error: Can't use an undefined value as an ARRAY reference at Base/Plasmid.pm line 14.
	 at ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/App.pm line 973.
	 at ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/Role/Hookable.pm line 114.
	Base/Plasmid.pm around line 14
	11 my @defaults;
	12 
	13 hook before => sub {
	14     @defaults = @{config->{default_display_fields}{plasmid}};
	15 };
	16 
	17 
	Stack
	main in ~/perl5/perlbrew/perls/perl-5.22.0/bin/starman l. 38
	Plack::Runner in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Plack/Runner.pm l. 277
	Plack::Loader::Delayed in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Plack/Loader/Delayed.pm l. 20
	Plack::Handler::Starman in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Plack/Handler/Starman.pm l. 25
	Starman::Server in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Starman/Server.pm l. 106
	Net::Server in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Net/Server.pm l. 60
	Net::Server::PreFork in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Net/Server/PreFork.pm l. 111
	Net::Server::PreFork in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Net/Server/PreFork.pm l. 187
	Net::Server::PreFork in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Net/Server/PreFork.pm l. 229
	Net::Server::PreFork in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Net/Server/PreFork.pm l. 229
	Net::Server in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Net/Server.pm l. 74
	Starman::Server in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Starman/Server.pm l. 298
	Starman::Server in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Starman/Server.pm l. 195
	Plack::Util in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Plack/Util.pm l. 145
	Plack::Util in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Plack/Util.pm l. 145
	Dancer2::Core::Runner in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/Runner.pm l. 212
	Dancer2::Core::Dispatcher in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/Dispatcher.pm l. 36
	Plack::Component in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Plack/Component.pm l. 50
	Plack::Middleware::Head in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Plack/Middleware/Head.pm l. 10
	Plack::Component in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Plack/Component.pm l. 50
	Plack::Middleware::Static in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Plack/Middleware/Static.pm l. 18
	Plack::Component in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Plack/Component.pm l. 50
	Plack::Middleware::FixMissingBodyInRedirect in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Plack/Middleware/FixMissingBodyInRedirect.pm l. 50
	Dancer2::Core::App in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/App.pm l. 1205
	Dancer2::Core::App in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/App.pm l. 1203
	Dancer2::Core::App in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/App.pm l. 1282
	Return::MultiLevel in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Return/MultiLevel.pm l. 97
	Return::MultiLevel in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Return/MultiLevel.pm l. 61
	Dancer2::Core::App in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/App.pm l. 1281
	Dancer2::Core::App in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/App.pm l. 1384
	Dancer2::Core::App in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/App.pm l. 1425
	Dancer2::Core::Error in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/Error.pm l. 307
	Method::Generate::Accessor in (eval 560) l. 20
	Dancer2::Core::Error in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/Error.pm l. 294
	Dancer2::Core::Error in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/Error.pm l. 110
	Dancer2::Core::Error in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/Error.pm l. 159
	Dancer2::Core::Error in ~/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Dancer2/Core/Error.pm l. 417
	Settings
	appdir => '~/projects/CFSlab',
	apphandler => 'PSGI',
	behind_proxy => 0,
	charset => '',
	content_type => 'text/html',
	environment => 'development',
	host => '0.0.0.0',
	log => 'debug',
	logger => bless( {
	  app_name => 'Plack::Sandbox::_2fUsers_2flogust_2fprojects_2fCFSlab_2fapp_2epl',
	  config => {},
	  hooks => {
		'engine.logger.after' => [],
		'engine.logger.before' => []
	  },
	  log_format => '[%a:%P] %L @%T> %m in %f l. %l',
	  log_level => 'debug'
	}, 'Dancer2::Logger::Console' ),
	no_server_tokens => 0,
	port => '3000',
	public_dir => '~/public',
	route_handlers => [
	  [
		'AutoPage',
		1
	  ]
	],
	show_errors => 1,
	startup_info => 1,
	static_handler => 1,
	template => 'Tiny',
	traces => 0,
	views => '~/views',
	warnings => 1
	Session
	undefined
	Environment
	undefined
	Powered by Dancer2 0.163000

**Comment by veryrusty** [comment]
I think this is due to the way Dancer2 determines where its located. Dancer2 uses a(n ugly) heuristic for find directories, starting from where the current file is and working up the directory structure looking for ./bin *and* ./lib dirs  (defaulting to '.' if nothing is found).  Dancer2 also looks for a `.dancer` file (its content is not important).

Looking at your dumped config, try
```
$> touch /Users/logust/projects/CFSlab/.dancer
```
and running your code under plackup. That should be sufficient to help the heuristic find where the app and its associated resources are located.

**Comment by logust79** [comment]
@veryrusty 
Many thanks! This solved my problem!
