### ISSUE TITLE
Return empty string instead of "0"

### ISSUE THREAD

**Issue by ambs** [PerlDancer/Dancer2#1079]
Hi
If a route returns "0", it gets "" at the end.
This is something recent, but looking to the commit descriptions didn't find the reason why.

Is this a feature or a bug? If it is a but (I think so) I can dig it up. Should be a missing call to `defined`.

**Comment by xsawyerx** [comment]
I would classify this as a bug!

**Comment by ambs** [comment]
Faster than I though.

**Comment by veryrusty** [comment]
Closed by #1082.

@ambs++ for reporting and thanks for the initial PR!.
