### ISSUE TITLE
Configuration missing for plugins inside plugins

### ISSUE THREAD

**Issue by racke** [PerlDancer/Dancer2#1083]
I tested the Dancer2::Plugin::Auth::Extensible topic/plugin2 against the latest copy of Dancer2, plugins-yanick.
Unfortunately a plugin inside plugin misses its configuration when used. The plugin is included like that:

```
has auth_extensible => (
    is => 'ro',
    lazy => 1,
    default => sub {
        scalar $_[0]->app->with_plugin( 'Auth::Extensible' )
    },
    handles => [ 'require_login' ],
);
```

**Comment by xsawyerx** [comment]
There is a test for it in the code. I wonder why that test passes and this code doesn't.

**Comment by xsawyerx** [comment]
@yanick what says you?

**Comment by yanick** [comment]
Do we have a test anywhere that highlight this problem?

Once we have a test, my  first instinct would to try it with my original branch and see if it works there.

**Comment by xsawyerx** [comment]
@racke Any chance of writing a test for it?

**Comment by racke** [comment]
On 01/01/2016 09:00 PM, Sawyer X wrote:
> @racke <https://github.com/racke> Any chance of writing a test for it?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/PerlDancer/Dancer2/issues/1083#issuecomment-168334876>.
> 

Yes, just give me a bit of time.

Regards
	Racke

-- 
Perl and Dancer Development

Visit our Perl::Dancer conference 2015.
More information on https://www.perl.dance.

**Comment by xsawyerx** [comment]
Thank you! :)

**Comment by racke** [comment]
I updated Dancer2::Plugin::Auth::Extensible topic/plugin2, so we get now a clear error message:

```
t/02-as-plugin.t .. No realms found in configuration. at /home/racke/dancer2/auth-extensible/blib/lib/Dancer2/Plugin/Auth/Extensible.pm line 1185.
```

**Comment by racke** [comment]
OK, I added a test file. If you comment out the `$plugin->config` call in `BUILD` sub, all tests are passing.

**Comment by yanick** [comment]
The test was setting its config for the app in the name `main`, not `AppInsidePlugin`...  

PR at PerlDancer/Dancer2-Plugin-Auth-Extensible#40

**Comment by xsawyerx** [comment]
:raised_hands:

**Comment by xsawyerx** [comment]
@racke May we close this ticket?

**Comment by racke** [comment]
On 01/06/2016 09:16 PM, Sawyer X wrote:
> @racke <https://github.com/racke> May we close this ticket?
> 

We should fix the failing test on t/plugin2/inside-plugin.t first.

Regards
	Racke


-- 
Perl and Dancer Development

Visit our Perl::Dancer conference 2015.
More information on https://www.perl.dance.

**Comment by xsawyerx** [comment]
@yanick ping on the failing test?

**Comment by yanick** [comment]
On 2016-01-10 09:20 AM, Sawyer X wrote:
> @yanick <https://github.com/yanick> ping on the failing test?

Fixed.

**Comment by xsawyerx** [comment]
Thanks!
