### ISSUE TITLE
Move to `HTTP::XSCookies` (was: Move to `Cookie::Baker`)

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#1087]
New versions of [Plack](https://metacpan.org/pod/Plack) require and use [Cookie::Baker](https://metacpan.org/pod/Cookie::Baker), which also has an XS backend. I wanted to move to replace `Dancer2::Core::Cookie` with it for a while now - now seems like a good time.

**Comment by SysPete** [comment]
`Plack::Request` doesn't use `Cookie::Baker`'s `crush_cookie` which is the only function with XS speedup but we may as well use it ourselves. I'll start a branch and throw up a PR for discussion as soon as I have something to show. Should reduce the line count if nothing else.

**Comment by xsawyerx** [comment]
@SysPete, I want to bring in @gonzus in this. A first solid implementation of a new cookie parser and "baker" is available at https://github.com/gonzus/devel-cookie. I think we'll rename it as `HTTP::XSCookies` and release it.

Meanwhile, if we can try to have our code attempt to use those functions, that would be great. It would also give us a good check for whether the functions are generic enough to be seamlessly integrated in Dancer2.

**Comment by gonzus** [comment]
On 23/01/2016 18:06, Sawyer X wrote:
>
> @SysPete <https://github.com/SysPete>, I want to bring in @gonzus 
> <https://github.com/gonzus> in this. A first solid implementation of a 
> new cookie parser and "baker" is available at 
> https://github.com/gonzus/devel-cookie. I think we'll rename it as 
> |HTTP::XSCookies| and release it.
>
> Meanwhile, if we can try to have our code attempt to use those 
> functions, that would be great. It would also give us a good check for 
> whether the functions are generic enough to be seamlessly integrated 
> in Dancer2
>

Hey everyone,

I just released the first version of HTTP::XSCookie (singular, crap). It 
includes (and passes) the testsuite from Cookie::Baker and 
Cookie::Baker:XS, as well as some additional tests of mine, so it is not 
/spectacularly/ wrong, but there could still be weird behavior in there. 
Please try it and let me know.

https://metacpan.org/pod/HTTP::XSCookie

Cheers,
Gonzo

**Comment by xsawyerx** [comment]
`s/$/s/;`

**Comment by gonzus** [comment]
Where's the patch?

Anyway, I just uploaded to CPAN a new version 0.000002, renamed to HTTP::XSCookies; it should appear soon. The old version is scheduled for deletion in CPAN.

"Thanks" Sawyer... I guess... ;-)

**Comment by xsawyerx** [comment]
@gonzus++ :heart:

**Comment by SysPete** [comment]
Started on a new branch which I'm using PR https://github.com/PerlDancer/Dancer2/pull/1117 to track.

I've also committed code to drop malformed cookies (no value) since that is the behaviour I see in Plack::Request and most other cookie crushers.

@gonzus we have a test failure in t/request.t with a test which sets a cookie as:

`cookie.a=foo=bar; cookie.b=1234abcd; no.value.cookie`

XSCookies appears to barf on the double `=` in `cookie.a` and returns an empty hash. So I guess we need to determine if having an equals sign in the value is valid.

**Comment by veryrusty** [comment]
A quick read over RFC6265 (which I think is the latest applicable RFC) implies that an `=` (%x3D) in the cookie value is valid. 

Here's an extract of what's valid:
```
 cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
 cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                       ; US-ASCII characters excluding CTLs,
                       ; whitespace DQUOTE, comma, semicolon,
                       ; and backslash
```

**Comment by gonzus** [comment]
Agreed. I already have a fix for this and am adding more test cases. 
Will report back.

**Comment by gonzus** [comment]
I just pushed a fix and a couple more test cases which failed before and now pass. I will release a new version on CPAN in a minute. Thanks @SysPete and @veryrusty.

**Comment by SysPete** [comment]
@gonzus getting closer but HTTP::XSCookies sets the `Secure` flag all lower-case as `secure` which might work but is non-standard and breaks current tests:

https://travis-ci.org/PerlDancer/Dancer2/jobs/105436755#L1433-L1439

**Comment by gonzus** [comment]
@SysPete easy to fix, but I also checked [RFC6265](https://tools.ietf.org/html/rfc6265) and it seems ALL cookie field names are Capitalized (see below). Should I go ahead and change all of them in HTTP::XSCookies accordingly?

> expires-av        = "Expires=" sane-cookie-date
> max-age-av        = "Max-Age=" non-zero-digit *DIGIT
> domain-av         = "Domain=" domain-value
> path-av           = "Path=" path-value
> secure-av         = "Secure"
> httponly-av       = "HttpOnly"

**Comment by SysPete** [comment]
@gonzus yup - looks like CamelCase is the way to go for all fields.

**Comment by gonzus** [comment]
OK, just pushed a fix (and updated test cases).

@SysPete Do you depend on me releasing a new version on CPAN? If yes, I will do it right away; if not, I will wait until I have a couple more substantial changes. Please let me know.

**Comment by SysPete** [comment]
@PerDancers please have a look at #1117 as I'm sure further improvements are possible.

@gonzus would be good to have a release so that we can more easily test (if possible). I've updated the old pure-Perl baking code and tests to match.

**Comment by SysPete** [comment]
For simple apps that only use cookies for session there might be some performance gain in having 2 layers of cookies: one with just simple hashes and one with full objects. This would mean we could avoid cookie object creation + cost of accessors for the session cookie but at the expense of more complex code. Just a thought that I'm quite happy to have shot down. :smile:

**Comment by gonzus** [comment]
@SysPete done, version 0.000005 should appear shortly on CPAN.

**Comment by SysPete** [comment]
Thanks @gonzus - all now working very nicely.

**Comment by gonzus** [comment]
Great! Please let me know if there is actually any improvement compared to the previous code; I'm curious... :-)

**Comment by SysPete** [comment]
I've add `tools/cookie_perf.pl` to see how different crush/bake implementations perform and there is some good news and some bad. HTTP::XSCookies is clearly faster for baking but for crushing it is slower than the pure-Perl code and also slower that pure-Perl and XS versions of Cookie::Baker. Interesting to see that Cookie::Baker::XS doesn't seem to perform any better than its PP version...
```
5.20.3@main:~/git/Dancer2$ COOKIE_BAKER_PP=1 perl -Ilib tools/cookie_perf.pl 
crush XS: Ran 20 iterations (0 outliers).
crush XS: Rounded run time per iteration: 2.1300e-02 +/- 2.5e-05 (0.1%)
crush PP: Ran 25 iterations (5 outliers).
crush PP: Rounded run time per iteration: 1.7486e-01 +/- 1.3e-04 (0.1%)
crush Cookie::Baker: Ran 27 iterations (6 outliers).
crush Cookie::Baker: Rounded run time per iteration: 1.7522e-01 +/- 1.0e-04 (0.1%)
bake XS: Ran 25 iterations (3 outliers).
bake XS: Rounded run time per iteration: 2.0014e-01 +/- 1.8e-04 (0.1%)
bake PP: Ran 20 iterations (0 outliers).
bake PP: Rounded run time per iteration: 2.7091e-01 +/- 1.0e-04 (0.0%)
```

```
5.20.3@main:~/git/Dancer2$ perl -Ilib tools/cookie_perf.pl 
crush XS: Ran 22 iterations (2 outliers).
crush XS: Rounded run time per iteration: 2.2035e-02 +/- 1.8e-05 (0.1%)
crush PP: Ran 25 iterations (5 outliers).
crush PP: Rounded run time per iteration: 1.7480e-01 +/- 1.0e-04 (0.1%)
crush Cookie::Baker: Ran 24 iterations (4 outliers).
crush Cookie::Baker: Rounded run time per iteration: 1.75619e-01 +/- 9.9e-05 (0.1%)
bake XS: Ran 23 iterations (3 outliers).
bake XS: Rounded run time per iteration: 2.0208e-01 +/- 2.4e-04 (0.1%)
bake PP: Ran 22 iterations (1 outliers).
bake PP: Rounded run time per iteration: 2.7663e-01 +/- 1.7e-04 (0.1%)
```

**Comment by gonzus** [comment]
Two things:

1. Are you sure you tested the PP version of Cookie::Baker? If the XS is 
installed, you have to explicitly tell it not to use it.
2. My performance tests show HTTP::XSCookies at about the same speed as 
Cookie::Baker::XS for short cookies and/or cookies with few URL-encoded 
characters, but it seemed to be much faster for longer cookies and/or 
cookies with lots of URL-encoded characters. Perhaps if you add some 
tests for such scenarios you will see something similar. I don't really 
know what the common case ends up being in real life.

Cheers,
Gonzalo

**Comment by SysPete** [comment]
Latest performance test script is fairest comparison so far and has code copy/pasted into local subs where appropriate and calls all functions in scalar context as we'd expect in the real world. `Dancer2::Core::Cookies` is not used directly and no objects are created and instead the Dancer2 `to_header code` is replaced with an equivalent sub that works on a hash instead of object. I'm now calling XS/PP code explicitly so no chance of confusion there.

Conclusion: there is clearly a winner: `HTTP::XSCookies`

Module | Method | Time | Comparison to HTTP::XSCookies
-------|--------|-------|----------
Dancer2 | crush | 1.77012 | +713.59%
HTTP::XSCookies | crush | 0.21757 | n/a
Cookie::Baker | crush | 1.77395 | +715.35%
Cookie::Baker::XS | crush | 0.17986 | -17.332%
Dancer2 | bake | 1.0222 | +13.641%
HTTP::XSCookies | bake | 0.8995 | n/a
Cookie::Baker | bake | 2.80012 | +211.30%

As per @gonzus comment it is possible that `HTTP::XSCookies` would outshine the others even further with more complex cookies but it is clearly the obvious choice right now as an option to the pure-Perl code.

Raw results:
```
crush Dancer2: Ran 25 iterations (5 outliers).
crush Dancer2: Rounded run time per iteration: 1.77012e+00 +/- 5.6e-04 (0.0%)
crush HTTP::XSCookies: Ran 20 iterations (0 outliers).
crush HTTP::XSCookies: Rounded run time per iteration: 2.1757e-01 +/- 3.1e-04 (0.1%)
crush Cookie::Baker PP: Ran 21 iterations (1 outliers).
crush Cookie::Baker PP: Rounded run time per iteration: 1.77395e+00 +/- 9.0e-04 (0.1%)
crush Cookie::Baker::XS: Ran 23 iterations (2 outliers).
crush Cookie::Baker::XS: Rounded run time per iteration: 1.7986e-01 +/- 2.4e-04 (0.1%)
bake Dancer2: Ran 20 iterations (0 outliers).
bake Dancer2: Rounded run time per iteration: 1.0222e+00 +/- 1.0e-03 (0.1%)
bake Cookie::Baker::XS: Ran 22 iterations (0 outliers).
bake Cookie::Baker::XS: Rounded run time per iteration: 8.995e-01 +/- 1.0e-03 (0.1%)
bake Cookie::Baker: Ran 23 iterations (3 outliers).
bake Cookie::Baker: Rounded run time per iteration: 2.80012e+00 +/- 8.8e-04 (0.0%)

```

**Comment by gonzus** [comment]
That's awesome. If you guys decide to go with HTTP::XSCookies, that could be a good moment to release it as v1.0; let me know and I'll do that (as well as fixing / adding anything you need).

**Comment by SysPete** [comment]
So I have one problem with current #1117 :unamused: but only because of some problem with `Dancer2::Test`:

Now I've switched to using `Plack::Request->cookies` when `HTTP::XSCookies` is not available the final test in `t/dancer-test.t` fails when there is no `HTTP::XSCookies`. I really don't want to put the crushing code back into `_build_cookies` when `Plack::Request` already has perfectly good code we can use.

I've never used `Dancer2::Test` and really don't want to so any ideas?

**Comment by SysPete** [comment]
Seems my problem is simply Dancer2::Test doing weird stuff so I've added a small change in there so that it handles cookie header in the way the new request code expects (with pure-Perl crushing via Plack::Request). https://github.com/PerlDancer/Dancer2/pull/1117#issuecomment-178724804

**Comment by gonzus** [comment]
Hi Peter,

I was curious how it went with HTTP::XSCookies in Dancer. Any news? Do 
you need any help?

Cheers,
Gonzo

**Comment by SysPete** [comment]
Plugin2 just merged so need to wait for that to settle. I'm hoping xscookies will get merged soon. 

@xsawyerx any thoughts on current PR?

On 7 Mar 2016 10:43, Gonzalo Diethelm <notifications@github.com> wrote:

Hi Peter,

I was curious how it went with HTTP::XSCookies in Dancer. Any news? Do 
you need any help?

Cheers,
Gonzo

**Comment by SysPete** [comment]
Closing this issue since we have PR #1117 so I suggest moving further discussion over there.

**Comment by xsawyerx** [comment]
TODAY I WILL BE REVIEWING THIS ENTIRE THING!
(WHATDOYOUMEAN MY CAPS LOCK IS STUCK?!)

**Comment by SysPete** [comment]
@gonzus just to let you know HTTP::XSCookies change was released as part of Dancer2 v0.202000 yesterday. Many thanks for the code speedup!

**Comment by gonzus** [comment]
Awesome! Let me know if you need anything, now that this is live for real.

Cheers!

**Comment by hvoers** [comment]
@gonzus  Mmm, maybe some more pod, eg SYNOPSIS, DESCRIPTION, exported subs.
I would like to make a FreeBSD port for this.

**Comment by hvoers** [comment]
And do not forget to include a LICENSE section.

**Comment by hvoers** [comment]
And you need a better NAME section :-)

**Comment by gonzus** [comment]
I just uploaded a new version to CPAN and the github repo; I believe I 
added everything you suggested. Patches welcome!

Let me know if you would feel more comfortable with an "official" v1.0.

Cheers!
