### ISSUE TITLE
Move away from `HTTP::Body`

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#1090]
I've been wanting to do this for a very long time.

`Plack` did this in https://github.com/plack/Plack/pull/537.

**Comment by veryrusty** [comment]
Totally agree! @xsawyerx++

The merged PR for `Plack` is https://github.com/plack/Plack/pull/538

**Comment by veryrusty** [comment]
I was about to revise my `refactor/request_body_parsing` branch which removed HTTP::Body from Dancer2::Core::Request.. I'll go check the impact that of using HTTP::Entity::Parser on that work :)

**Comment by veryrusty** [comment]
Just updated Plack locally to its latest release (1.0039). Plack::Request still uses HTTP::Body even though was released after the above merge..  #weird.

**Comment by veryrusty** [comment]
D'Oh. Plack 1.0039 was a bugfix release..  No 'new feature' release has been made for Plack since the PR to remove HTTP::Body was merged.

**Comment by xsawyerx** [comment]
@veryrusty Thank you for looking into this and (hopefully) taking it on. :)

**Comment by veryrusty** [comment]
Challenge accepted :)

**Comment by xsawyerx** [comment]
@veryrusty++

**Comment by bigpresh** [comment]
I'm interested in this one - I'm looking at how much work it would be to swap HTTP::Body out of Dancer1, too, as part of PerlDancer/Dancer#1140.  I suspect it'll be too much work to justify on D1, though; if so, I'll come up with some kind of workaround for it instead - HTTP::Body works well enough for us, other than its rather weird body handling (that the body is available via a filehandle for some request types, but not others)

**Comment by veryrusty** [comment]
@bigpresh D2's request object inherits from Plack::Request, so I'm waiting for a Plack release that has this change (being #lazy).   For D1, have a look at the change that went into Plack::Request.

**Comment by xsawyerx** [comment]
@veryrusty Is such a release of `Plack` expected?

**Comment by veryrusty** [comment]
Note for self: Plack 1.0040 TRIAL is out, with HTTP::Body replaced with HTTP::Entity::Parser

**Comment by veryrusty** [comment]
Plack 1.0040 TRIAL breaks our body param handling. Working on a fix..

**Comment by veryrusty** [comment]
Fix for body param passing in #1148.

**Comment by xsawyerx** [comment]
@veryrusty++

**Comment by xsawyerx** [comment]
Where are we now?

**Comment by veryrusty** [comment]
I started on this a couple of weeks ago; then got distracted fixing the HMV parameter encoding issues.  I'm not going to be able to dedicate time to it till December.

**Comment by xsawyerx** [comment]
No rush. :)

**Comment by cromedome** [comment]
Resolved by #1406. Closing.
