### ISSUE TITLE
switch to Type::Tiny

### ISSUE THREAD

**Issue by SysPete** [PerlDancer/Dancer2#1101]
Would a switch from MooX::Types::MooseLike to Type::Tiny be a good idea? I've switched a number of projects over recently for a number of reasons:

- Moose compatibility (not so relevant for Dancer2)
- constraint checks are faster due to use of Sub::Quote::quote_sub inlining
- easily use type constraints for coercion
- Type::Tiny::XS - optional go-faster stripes

**Comment by xsawyerx** [comment]
I would like to see a benchmark along with it, because that would be my biggest motivation.

**Comment by SysPete** [comment]
@veryrusty and I have run different tests and can see no obvious speed difference between current type system and Type::Tiny. There *might* be a difference but the real cost is the type checking itself and choice of actual type system is insignificant in comparison. In my own tests I see an order of magnitude difference when disabling type checking completely with a very simple class with just a handful of attributes.

**Comment by xsawyerx** [comment]
I'm not surprised that removing the check completely is a more significant change, but I am surprised that changing to Type::Tiny was such a small difference. Any profiling data on this?

**Comment by SysPete** [comment]
On 23/01/16 19:09, Sawyer X wrote:
>
> I'm not surprised that removing the check completely is a more
> significant change, but I am surprised that changing to Type::Tiny was
> such a small difference. Any profiling data on this?
>
>
NYTProf profiling that I've done seems to suggest that Type::Tiny
provides an a substantial performance improvement. Just need to find
tuits to formalise my results.

**Comment by xsawyerx** [comment]
@SysPete++

**Comment by SysPete** [comment]
PR opened #1120. Enjoy!

**Comment by SysPete** [comment]
@xsawyerx see https://github.com/PerlDancer/Dancer2/pull/1120#issuecomment-178105324 for performance results. I'm sure we can squeeze a little more in some places but it is already an improvement.

**Comment by xsawyerx** [comment]
Done.
