### ISSUE TITLE
Dancer2::FileUtils::normalize path returns unexpected results for "../../.."

### ISSUE THREAD

**Issue by dboehmer** [PerlDancer/Dancer2#1102]
I am writing a Dancer2 app with a 3rd level Perl namespace (`Foo::Bar::MyApp`). To retrieve a file from my projects root directory I tried to use `path( dirname( __FILE__), qw<.. .. .. foo bar.baz> )` but didn't get the expected result.

After some debugging this test file shows how `normalize_path` is behaving differently from what I expected:

```perl
#!/usr/bin/env perl

use Test::More;

BEGIN { use_ok 'Dancer2::FileUtils', qw<normalize_path> }

sub is_path {
    my ( $input => $expected ) = @_;
    is normalize_path($input) => $expected, "$input => $expected";
}

is_path "/a/b/c/d/A/B/C"             => "/a/b/c/d/A/B/C";
is_path "/a/b/c/d/../A/B/C"          => "/a/b/c/A/B/C";
is_path "/a/b/c/d/../../A/B/C"       => "/a/b/A/B/C";
is_path "/a/b/c/d/../../../A/B/C"    => "/a/A/B/C";
is_path "/a/b/c/d/../../../../A/B/C" => "/A/B/C";

done_testing;
```

Output for me on Linux with Dancer2 0.166000:

```prove
normalize_path.t ..
ok 1 - use Dancer2::FileUtils;
ok 2 - /a/b/c/d/A/B/C => /a/b/c/d/A/B/C
ok 3 - /a/b/c/d/../A/B/C => /a/b/c/A/B/C
ok 4 - /a/b/c/d/../../A/B/C => /a/b/A/B/C
not ok 5 - /a/b/c/d/../../../A/B/C => /a/A/B/C
not ok 6 - /a/b/c/d/../../../../A/B/C => /A/B/C
1..6

#   Failed test '/a/b/c/d/../../../A/B/C => /a/A/B/C'
#   at catfile.pl line 9.
#          got: '/a/b/c/A/B/C'
#     expected: '/a/A/B/C'

#   Failed test '/a/b/c/d/../../../../A/B/C => /A/B/C'
#   at catfile.pl line 9.
#          got: '/a/b/A/B/C'
#     expected: '/A/B/C'
# Looks like you failed 2 tests of 6.
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/6 subtests 

Test Summary Report
-------------------
normalize_path.t (Wstat: 512 Tests: 6 Failed: 2)
  Failed tests:  5-6
  Non-zero exit status: 2
Files=1, Tests=6,  0 wallclock secs ( 0.03 usr  0.00 sys +  0.02 cusr  0.00 csys =  0.05 CPU)
Result: FAIL
```

**Comment by SysPete** [comment]
Already fixed in D1 by https://github.com/PerlDancer/Dancer/commit/399bd509c9875423d70ea668095bf2a3bef02ee2 so I guess we need to apply the same fix.

**Comment by SysPete** [comment]
Many thanks @dboehmer pending PR https://github.com/PerlDancer/Dancer2/pull/1103 fixes this issue.

**Comment by SysPete** [comment]
Having thought further on this I think I prefer using `Cwd`'s `realpath` as a replacement for `normalize_path` function. We import it anyway but don't use it so it seems someone at some point thought it was a better idea. Will update the PR later today.

**Comment by veryrusty** [comment]
Note that `normalize_path` also works on relative paths and is a "logical" cleanup. Whereas `realpath` works with absolute paths and will traverse the filesystem. Sometimes you want/need both variants.
( My preference is to apply this PR as is )

**Comment by SysPete** [comment]
And realpath blows up lots of things as I just found out. Also seems that `Cwd` isn't actually used so removing that from `FileUtils` so we drop a dep too.

**Comment by dboehmer** [comment]
Are you going to make a release with this fix? I've patched this in my local lib but every now and then one of my co-workers stumbles over this after a fresh CPAN install of Dancer2.
