### ISSUE TITLE
Using Template Toolkit gives a bad fallback in error handling

### ISSUE THREAD

**Issue by cym0n** [PerlDancer/Dancer2#1104]
I was trying to answer a request with an error

```
get '/foo' => sub {
    send_error("error", 403);
};
```

No problem using simple template enging.

With Template Toolkit I receive this error:

```
Route exception: file error - 403.tt: not found in /home/cymon/works/testenv/016/lib/perl5/Dancer2/Core/App.pm l. 1288
```

and the site try to return a 500.

Writing the route this way

```
get '/foo' => sub {
    Dancer2::Core::Error->new(
             response => response(),
             status   => 403,
             message  => "Error",
         )->throw
};
```

All works well.

**Comment by veryrusty** [comment]
I've tested the above example against the 0.166001 release (which fixed a TT2 related regression) and get a 403 response using `send_error("error", 403)`.

The referenced issued in strehler has been closed. @cym0n is this still a problem with the latest release ?

**Comment by cym0n** [comment]
It's not a problem any more.
I closed the bug releasing the workaround I reported in the bug report, but now I reverted it, trying my tests with Dancer 0.166001 and all went well!

**Comment by veryrusty** [comment]
Thanks for following up so quickly @cym0n.

With your workarounds reverted, I think its safe to close this. Please re-open (or create another issue) if there are further problems.
