### ISSUE TITLE
Can someone help me with mswin cpantesters?

### ISSUE THREAD

**Issue by hvoers** [PerlDancer/Dancer2#1118]
http://www.cpantesters.org/cpan/report/fdf4ca8c-6c04-1014-80ce-0fd55b53831f
shows a problem with \ vs / in Path::Tiny 

"got" is okay but "expected" is wrong.

**Comment by SysPete** [comment]
Hi @hvoers 

I'll have a PR for you pretty soon.

**Comment by SysPete** [comment]
Closing since PR https://github.com/hvoers/Dancer2-Plugin-Path-Class/pull/2 submitted & fixes problem.
