### ISSUE TITLE
Manual is inaccurate about param and query_parameters

### ISSUE THREAD

**Issue by smcmurray** [PerlDancer/Dancer2#1121]
https://metacpan.org/pod/Dancer2::Manual#Retrieving-request-parameters could be more clear about the difference between param and query_parameters.

> The params keyword returns a hashref of request parameters; these will be parameters supplied from named matches in the request's path, and from parameters within the request's query string and, for HTTP POST requests, the content of the POST body. Multiple values for the same parameter are ignored.
> 
> The query_parameters keyword provides a Hash::MultiValue result from the request's query string or POST body. It is considered much safer, but may not include the same information that params may return.

https://metacpan.org/pod/Dancer2::Manual#Named-matching should not include query_parameters calls for named parameters.

```
get '/hello/:name' => sub {
    "Hey ".param('name').", welcome here!";
};
```

For instance, try to request /user/x?id=y against the following route:

```
get '/user:id' => sub {
  "param: " . param('id') . ", query_parameters: " . query_parameters->get_all('id')
}
```

**Comment by shumphrey** [comment]
I think the docs should say route_parameters not query_parameters here, or params('route')
I also note that Dancer2::Core::Request doesn't document route_parameters.

**Comment by xsawyerx** [comment]
Yeah. This is a bug in documentation.

**Comment by xsawyerx** [comment]
The documentation has been revised, enough that nothing mentioned here is still applicable.

I think we can close this ticket. Thanks. :)
