### ISSUE TITLE
Can we make YAML warn on duplicate keys in config files?

### ISSUE THREAD

**Issue by SysPete** [PerlDancer/Dancer2#1130]

**Comment by racke** [comment]
Please keep in mind that we use `Config::Any` in Dancer 2, so YAML isn't the only configuration file format anymore.

**Comment by SysPete** [comment]
YAML isn't the only format and I agree with this...
```
<xsawyerx> so, YAML.pm http://YAML.pm  is actually the canonical parser
<xsawyerx> so we should depend onit
<xsawyerx> *on it
<xsawyerx> the rest are "some form of implementation"
<SysPete> yup
```
All examples show YAML and so I think we should do our best to help new users who try to use it. Anyone using an alternative config file format probably already understands its potential pitfalls so I don't think we need to worry as much about them.

**Comment by veryrusty** [comment]
I certainly would *NOT* consider YAML.pm the 'canonical' yaml parser. YAML.pm does not conform to the YAML spec; even Ingy recommends to use something built on libyaml (like YAML::XS) if at all possible. YAML.pm is the best pure-perl (and hence fat-packable) option for parsing YAML.

**Comment by xsawyerx** [comment]
I do recall `YAML::XS` to have its own set of problems. In Dancer we had to deal with plenty of YAML implementation problems and I think the only one that worked flawlessly (despite being YAML) was `YAML.pm`.

**Comment by xsawyerx** [comment]
I can't see how we can warn about this. Also, if it solves it for YAML, it doesn't mean it solves it for other formats.

Even having a configuration object which avoids duplicates wouldn't work if the configuration format already resolves multiple keys.

I honestly would like to see how easy it is to actually use other formats. We use `Config::Any`, but I've never used a different format and never saw anyone else use one. I like `.ini` much more than YAML.

**Comment by cromedome** [comment]
I think when I took the first crack at using `Config::Any` in Dancer, I was having a hate relationship with YAML. The problem with JSON is that we can't have comments in the config file, which I didn't consider at the time (INI doesn't have that, nor does YAML).

Something I never considered about INI is how does the plugin configuration handle INI config files? Or anything that has a couple of levels of config (`plugins / database / connections`, etc.)?

If we want to throw a warning on duplicate config keys, do we want to consider making YAML the only config file format again? Asking for a friend ;)

**Comment by xsawyerx** [comment]
INI has comments with any line starting with `;`. We use quite a few in our `dist.ini`.

I still fail to understand how you can detect multiple config keys with YAML.

**Comment by veryrusty** [comment]
On 15/02/2016 8:47 PM, Sawyer X wrote:
> I still fail to understand how you can detect multiple config keys 
> with YAML.

The YAML 1.0 (and above) specs define mappings as

 > A mapping is an unordered set of key/value node pairs, with the 
restriction that each of the keys is unique

But the spec leaves it up to the parser to define behavior when keys are 
not unique, examples include: throw a warning, or first/last wins.

Anyone for writing our own parser ? ( JOKING! ) I agree @xsaywerx, Its 
not feasible to detect multiple config keys with YAML.

**Comment by SysPete** [comment]
YAML::Tiny will produce 2 warnings for this:
```
use YAML::Tiny;
my $hashref = Load(<<'...');
---
foo:
  bar: 1
  bar: 1
foo:
  flu: 1
...
```
and YAML.pm codes looks like it produces warnings internal warnings but have yet to work out where to find them.

**Comment by SysPete** [comment]
Updated wording in last comment as I seem to have borked by keyboard. :wink:

...and YAML.pm code looks like it produces internal warnings but have yet to work out where to find them.

**Comment by xsawyerx** [comment]
I vote for closing this. If we ever find a way that we can easily add, we can just throw a PR for it.

Generally, I would prefer not to delve into the innards of a specific YAML implementation, and I think it's reasonable to assume hash keys override.

**Comment by racke** [comment]
What about adding a test to the skeleton which checks the YAML with YAML::Tiny?

**Comment by racke** [comment]
Or at least a recipe in the docs.

**Comment by xsawyerx** [comment]
There was a conversation about a *strict mode*. I don't remember what the status of it was. This could be added to it as optional.

**Comment by xsawyerx** [comment]
Meanwhile we can definitely add it to the docs.

**Comment by cromedome** [comment]
The more I have thought about this, the more I'm with @xsawyerx and @racke on it. Let's add something to the docs, but we probably shouldn't do more. We can't assume that people will always be using YAML (though all of our examples do).

We can add a test to the skeleton, but is there anything similar we could offer up for people that want to use JSON, Apache-style, etc. too?

If we add anything for this in strict mode (should we continue to do strict mode?), it should be optional there.

I also vote for closing this.

**Comment by xsawyerx** [comment]
We have two votes for closing. If anyone wants to apply any patches to the docs[1], go ahead. Meanwhile I'm closing this ticket, as there really is not additional comments on it or progress we can make on it, as far as I can tell.

[1] From what I understand, to basically document that multiple keys in YAML will overwrite each other. (Is it like that in JSON too?)
