### ISSUE TITLE
Serializer not initialized for first request

### ISSUE THREAD

**Issue by boldra** [PerlDancer/Dancer2#1137]
`around execute_hook` is creating the `response` (via lazy build) before the hooks are executed, and it's execution of hooks that instantiate engines (including serializers). The result is that the first request always returns a stringified perl hash (like "`HASH(0x1855980)`"), because Dancer2::Core::Response->serializer is unset in `around content`.

**Comment by xsawyerx** [comment]
@boldra, Any chance you could provide us with a test?

**Comment by boldra** [comment]
I really wish I could find the time, but I'm not optimistic. We already had a job to reload the dancer app's cache after every apache restart, so that already served as a workaround for this problem.

**Comment by veryrusty** [comment]
App engines are initialised when `to_app` is called, and the (lazy) builder for the response object will pass in the apps serializer.

@boldra I completely understand the time pressure, but I'm stumped on this without a test case. What serializer are you using, and where/when to you configure it ?

**Comment by Suic** [comment]
For me that bug appears when I configure serializer inside the route sub:
```
get '/' => sub {
    set serializer => 'JSON';
    return { test => 123 };
};
```
But I think this is not the correct way to configure serializer. When serializer is configured outside of route sub everithing is ok.

**Comment by boldra** [comment]
Thanks @Suic and @veryrusty that might be the answer. We have the serializer initializing in a "before" hook (in an attempt to make the serializer respond to the http "accept" headers).

**Comment by xsawyerx** [comment]
Let me just say you shouldn't be setting the serializer during run-time. This should happen when configuring the application, outside a route or hook. This messes with the compilation and lazy loading/instantiating done inside Dancer2.

Can you explain **why** you're doing this?

**Comment by boldra** [comment]
@xsawyerx Thanks for the advice, I can see why this is causing the problem. I tried to explain the reason for doing this in my previous comment: by waiting for the "Accept" http header, this was intended to lazy-build serializers. 

I'll close the ticket now. Big thanks everyone who invested time on this!

**Comment by xsawyerx** [comment]
@boldra I'm sorry I missed that comment. (I was just skimming through it quickly.)

The answer is basically, "this isn't what serializers are meant for". They are meant to be "I'm telling you what it **should** be", not "let me find out first, and let you know while you're running".

I think the solution for what you want is either:

* The `Mutable` serializer (dynamically picking the right one.)
* The `SendAs` plugin (which is integrated now in core, available from next version, or already on CPAN.)
