### ISSUE TITLE
commit aa86913 (part of plugin2) breaks plugin in a plugin

### ISSUE THREAD

**Issue by SysPete** [PerlDancer/Dancer2#1138]
https://github.com/PerlDancer/Dancer2/commit/aa86913eea73f0cd795339200e601ed42f60d426 breaks the part of plugin2 we need the most.

**Comment by SysPete** [comment]
Rename issue to make this clearer. I'm not in favour of more hacking on compatibility mode and prefer to just rehack the plugins to use the new much improved plugin2 way. There are not many affected plugins anyway and fixing up plugins (which we need to do one day anyway) is probably a lot less work than adding more nastiness to Plugin.

**Comment by xsawyerx** [comment]
Do we know how many plugins use other plugins?

**Comment by xsawyerx** [comment]
Do we know how many plugins use other plugins? Do we know how many things are effectively broken by this?

**Comment by racke** [comment]
We don't know how many I suppose, but it shouldn't be a lot :-)

**Comment by xsawyerx** [comment]
Any measurement?

**Comment by veryrusty** [comment]
Wasn't one of the "drivers" for Plugin2 so plugins _could_ use other plugins keywords as it didn't work with the original implementation?  So the figure should be something close to 0.

/me ponders if "compatibility mode" should be "back compatibility mode"; plugins using other plugins didn't work before and probably shouldn't be expected to while using compatibility mode.

**Comment by racke** [comment]
There is Dancer2::Plugin::Auth::Extensible which @SysPete will fix in time and Dancer2::Plugin::Interchange6 which never worked.

**Comment by xsawyerx** [comment]
I think @hvoers had some usage for it.

Since it breaks Auth::Extensible, it means it was possible for at least long enough for it to be used by it and maybe other stuff. I wonder how much it is.

**Comment by hvoers** [comment]
On Thu, 10 Mar 2016, Sawyer X wrote:

> I think @hvoers had some usage for it.

I postponed the use of D2.
Don't let me slow you down.

**Comment by xsawyerx** [comment]
@hvoers Your usage was instrumental in understand what we should support and how.

**Comment by SysPete** [comment]
If anyone would like to help fixing broken plugins see: https://github.com/PerlDancer/Dancer2/issues/1078.

In the 'Latest release OK' there are a number of modules marked as BROKEN. I've PRed a few already and am working on the following myself:

- Auth::Extensible
- Auth::Extensible::Provider::DBIC

Since `HTTP::Auth::Extensible` was forked from `Auth::Extensible` I suspect the best option there is to wait for my AE work to be completed. Anything else in #1078 is up for grabs - please add comments there.

**Comment by SysPete** [comment]
Closing this issue since affected plugins are all being rehacked into pure plugin2 and plugin1 compat for plugin using a plugin would mean more disruption and mess in plugin2 code.
