### ISSUE TITLE
Every request generates new session object

### ISSUE THREAD

**Issue by roryzweistra** [PerlDancer/Dancer2#1142]
Hi guys,

I'm on the scaleway servers https://www.scaleway.com/ and it appears that every request generates a new session. I've tried this with a couple of Dancer2 versions.

I have almost the exact same setup on another vps that works perfectly fine. "Almost the same" means different user and password etc. I've tried this with session Simple, YAML and DBIC. I've also tried this on 3 different laptops with 3 different ip addresses so I'm pretty sure it doesn't have anything to do with my workstation.

So what happens is this:

I've added a hook 'before' to log the session id. When I do 3 request to the same page, I always get a new session id logged from the hook 'before'. Example:
```
[johnenbeppie:1815] debug @2016-03-16 19:05:32> VumufN5tC3MhgLymkpdqwlKpbMvqCKNw in /var/www/johnenbeppie.nl/johnenbeppie/bin/../lib/johnenbeppie.pm l. 8
[johnenbeppie:1815] debug @2016-03-16 19:05:33> VumufSBFFUUv7l3-h1tmjx-xVDMZz2Ez in /var/www/johnenbeppie.nl/johnenbeppie/bin/../lib/johnenbeppie.pm l. 8
[johnenbeppie:1815] debug @2016-03-16 19:05:36> VumugKeqNLY9MJx8lvyRmG9cz75MTlRT in /var/www/johnenbeppie.nl/johnenbeppie/bin/../lib/johnenbeppie.pm l. 8
```
My config session setup looks like this:
```
  session:
    DBIC:
      dsn: "DBI:mysql:database=johnenbeppie;host=127.0.0.1;port=3306"
      schema_class: "Johnenbeppie::Schema"
      user: "***********"
      password: "*********"
      resultset: "Session"
      id_column: "id"
      data_column: "data"
```
User and pass here are scrambled.

I run my server from an nginx / plackup configuration that looks like this:

Nginx:

```
upstream johnenbeppie {
    server localhost:5001;
}

server {
        listen 80;
        server_name johnenbeppie.nl;
        rewrite ^(.*)$ $scheme://www.johnenbeppie.nl$1;
}       

server {
	listen 80;
        server_name  www.johnenbeppie.nl;
        
        access_log  /var/log/nginx/www-johnenbeppie-access.log;
        
        root /var/www/johnenbeppie.nl/johnenbeppie;
        
        location / {
                try_files $uri @proxy;
                access_log off;
                expires max;
        }       
        
        location @proxy {
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                proxy_pass http://johnenbeppie;
        }       
}
```
plackup:
```
carton exec plackup -E deployment -s Starman --workers=1 -p 5001 -a /var/www/johnenbeppie.nl/johnenbeppie/bin/app.psgi
```
It looks to me that it has something to do with the architecture I'm running on because for the live of me I can't think of any other config / nginx / plackup differences that can cause this.

I'm not a linux guru so if you need more info please let me know and I'll be happy to provide it.

Cheers,

Rory Zweistra

**Comment by racke** [comment]
I'm not sure if this is the case here, but one common and hard to detect session problem occurs
if you run multiple Dancer applications on the same (base) domain.

This can be alleviated with using "session_name" configuration variable. 

Also please check your logs.

**Comment by roryzweistra** [comment]
At this moment there is only one Dancer app running on the server. However setting a session_name seems like a good idea. 

I'll do some digging and debugging today and will post the results later.

**Comment by roryzweistra** [comment]
As it turns out the missing cookie_duration & cookie_name settings where causing this. 
```
cookie_name: johnenbeppie.session
cookie_duration: '2 hours'
```
And this works like a charm.

What I don't get is that my other apps on other servers are working without these settings, but yeah... I'm a happy dancer again :)

Thanks for your help @racke 
I think we can close this one unless you want me to check my other apps configs to see why those are working without the settings.

**Comment by roryzweistra** [comment]
We may want to keep this one open, it stopped working...... Everything unchanged from the last time, not even a plackup reboot.

When checking the cookies in Chrome I see no cookies created, in Safari I see a different cookie for every request. 

It worked for a little while so I must be missing something here...

**Comment by roryzweistra** [comment]
Looks like I'm getting closer to the real problem here, both Simple and YAML work, but it's session DBIC that's not working like I expect it to.

**Comment by racke** [comment]
OK, I'm the author of https://metacpan.org/pod/Dancer2::Session::DBIC. This could be a bug in the session engine, do you get any messages in the logfile?

**Comment by roryzweistra** [comment]
Nope no messages at all. 
I'll do some digging and debugging later and report to https://github.com/racke/Dancer2-Plugin-DBIC

**Comment by racke** [comment]
Other options to track that down are using DBIC_TRACE and checking SQL log files for the statements issued.
