### ISSUE TITLE
skeleton app should use unique template tags

### ISSUE THREAD

**Issue by jasonblewis** [PerlDancer/Dancer2#1147]
The skeleton app uses `[% %]` as template tags for things like `[% appdir %]`, but this is a problem if you wish to write a skeleton for that will use TT2, which uses the same characters for its tags.

see:
https://github.com/PerlDancer/Dancer2/blob/master/share/skel/views/index.tt#L43

```
<li>Location: <span class="filepath">[% appdir %]</span></li>
```
and 
https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/CLI/Command/gen.pm#L219-L220
```
sub _process_template {
    my ($template, $tokens) = @_;
    my $engine = Dancer2::Template::Simple->new;
    $engine->{start_tag} = '[%';
    $engine->{stop_tag} = '%]';
    return $engine->render(\$template, $tokens);
}
```
My suggestion is that the skeleton should use tags that would be unique to app generation. Maybe something like `<d2% %d2>` or similar.

**Comment by jasonblewis** [comment]
here is my proposed solution

https://github.com/jasonblewis/Dancer2/commits/pr/change_skel_template_tag

comments would be appreciated

**Comment by xsawyerx** [comment]
This has been resolved by your PR. Closing.

Thanks. :)
