### ISSUE TITLE
Confusing exception when the response is not serializable

### ISSUE THREAD

**Issue by fgabolde** [PerlDancer/Dancer2#1152]
```
Failed to serialize the request: encountered object <snip>, but neither allow_blessed, convert_blessed nor allow_tags settings are enabled (or TO_JSON/FREEZE method missing)
  at <snip>/lib/site_perl/5.18.2/JSON.pm line 154.
  in <snip>/lib/site_perl/5.18.2/Dancer2/Core/Response.pm l. 250
```

The error message says "Failed to serialize the **request**", but the exception is thrown from Dancer2::Core::Response.

**Comment by xsawyerx** [comment]
Could you please provide more details?

**Comment by fgabolde** [comment]
@xsawyerx I would if I could but there aren't many more details to be provided.

Basically, whenever I mess up and try to return something that JSON cannot serialize (e.g. a DateTime object), I get this exception. The issue is that the exception message says "failed to serialize the *request*" where it should say "response".

**Comment by xsawyerx** [comment]
@fgabolde any chance of putting together a test?

**Comment by fgabolde** [comment]
@xsawyerx You actually already have a test that checks for this message (in t/classes/Dancer2-Core-Role-Serializer/with.t). Again, I don't have a problem with the behavior of D2, just with the *wording* of this particular exception. The serializer doesn't serialize requests, it serializes *responses*.

**Comment by racke** [comment]
@fgabolde: what about a PR ?

**Comment by veryrusty** [comment]
The error on serializer fail has been changed to `Failed to serialize content`

Thanks for reporting the issue @fgabolde
