### ISSUE TITLE
POD list of Dancer2::Logger::File parameters not rendered

### ISSUE THREAD

**Issue by fgabolde** [PerlDancer/Dancer2#1153]
I'm not sure what was supposed to happen [here](https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Logger/File.pm#L118), maybe a dzil plugin was supposed to take care of it, but currently it is not rendered properly.

**Comment by xsawyerx** [comment]
Fixed by 148b72f. Thanks!
