### ISSUE TITLE
Dancer2::Core::Request->query_parameters fails with new Plack::Request

### ISSUE THREAD

**Issue by dboehmer** [PerlDancer/Dancer2#1154]
This call to [$self->_parse_query](https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Core/Request.pm#L348) in Dancer2 fails because the inherited class Plack::Request doesn't have `_parse_query` since https://github.com/plack/Plack/commit/db1e817508d9ee08bc6df9474795e2767e7a9f0a.

This makes my Dancer2::Plugin::Swagger2 fail its tests because it requires Dancer2 v0.162000_01 and uses `request->query_parameters`.

This was quite hard to debug because it looks like Perl and all dependency versions are equal in these two tests:
* http://www.cpantesters.org/cpan/report/17c8be30-fcca-11e5-90bc-1ca2acbdcdc0
* http://www.cpantesters.org/cpan/report/f97f6df2-fcc9-11e5-b487-0a47fcd2507e

**Comment by veryrusty** [comment]
That commit ( plack/Plack@db1e817 ) is in the Plack 1.0040 TRIAL release.

( There are some other nots about this in #1090 and a proposed fix in #1148. )

**Comment by xsawyerx** [comment]
#1148 was merged, so this is effectively resolved. However, we will keep this open until we release a version with the fix.

**Comment by veryrusty** [comment]
Closing now the fix was release in Dancer2 v0.200000.

@dboehmer++ for raising the issue. Thanks!
