### ISSUE TITLE
'template' keyword not available via `use Dancer2`

### ISSUE THREAD

**Issue by girlwithglasses** [PerlDancer/Dancer2#1159]
From the Dancer2 advent calendar article ['Command line dancing'](http://advent.perldancer.org/2014/16)

> If you want to create command line applications that use the Dancer2 structures, you can simply `use Dancer2` and use the keywords it provides you.
> 
> What does this give you access to?
> 
> Dancer keywords
> `config` probably being the most helpful one, but `template` will also be available just like other engine-related keywords are - explained below under Engines.
> 

This is no longer true for Dancer2-0.166001, as `template` is only available from a route handler. Is there any chance of making it globally available? It would be very handy to be able to use it for writing files, etc. If not, could the advent calendar article be updated?

**Comment by xsawyerx** [comment]
The only reason I can think of that the `template` keyword would only be part of a route handler is because it contains a reference to the request as a token. We can change that, obviously. If I change it, none of the tests fail, which is pretty good.

I agree it can be a useful feature.

Does anyone have an objection? (@PerlDancer)

**Comment by veryrusty** [comment]
We'd need to wrap the parts of `Dancer2::Core::Role::Template->_prepare_tokens_options` that call the request attribute with a predicate check:  i.e.

```
if ($self->has_request) {
    $tokens->{request} = $self->request;
    $tokens->{params}  = $self->request->params;
    $tokens->{vars}    = $self->request->vars;
}
```

I agree that it seems like a reasonable feature.

**Comment by xsawyerx** [comment]
@veryrusty Funny, that was my exact implementation, which I just pushed as #1163

**Comment by racke** [comment]
Good idea :+1:

**Comment by veryrusty** [comment]
@girlwithglasses++ Thanks for raising the issue. 

#1163 has been merged. Closing 😺
