### ISSUE TITLE
forward doesn't set is_behind_proxy option

### ISSUE THREAD

**Issue by hanseman** [PerlDancer/Dancer2#1165]
Dancer2 is new to me, so please bear with me.
I'm deploying an application behind an Apache reverse proxy. Apache terminates SSL. Setting the configuration option behind_proxy to true ensures that methods like request->base and uri_for return an URI with protocol https. 
However, when doing forward to another route the behind_proxy setting is lost in the forwarded request,
If not an intended design, perhaps I may suggest the attached fix. Keep in mind my inexperience and that I probably don't have a clue.

Thank you for an excellent piece of software.

[App.pm.zip](https://github.com/PerlDancer/Dancer2/files/249463/App.pm.zip)

**Comment by veryrusty** [comment]
Thanks for the bug report @hanseman. I'll send a pull request with the fix shortly.

**Comment by veryrusty** [comment]
@hanseman++ for reporting and providing a test case 😄
