### ISSUE TITLE
Scope::Upper is broken for Perl 5.24

### ISSUE THREAD

**Issue by SysPete** [PerlDancer/Dancer2#1168]
Return::Multilevel uses Scope::Upper if it is available but we need to work around this for 5.24 until some SU fix is available. According to https://metacpan.org/pod/Return::MultiLevel#DEBUGGING RM's pure-Perl implementation of `unwind` can be forced by setting the environment variable `RETURN_MULTILEVEL_PP` to 1.

Thanks to @veryrusty for heads up.

**Comment by SysPete** [comment]
OK so Scope::Upper won't even install so this is a complete non-issue. Sorry for wasting time people.

**Comment by veryrusty** [comment]
The recent Scope::Upper v0.29 release installs on perl 5.24.0.

Many thanks to Dave Mitchell for his efforts there!
