### ISSUE TITLE
Type::Tiny::XS crash on Strawberry Perl 5.22

### ISSUE THREAD

**Issue by hurricup** [PerlDancer/Dancer2#1180]
Just FYI. Bug reported to developer: https://github.com/tobyink/p5-type-tiny-xs/issues/4

**Comment by xsawyerx** [comment]
@PerlDancer, should we revert Type::Tiny changes for now?

**Comment by cromedome** [comment]
As there seems to be some ongoing issues with it, I'd say we should.

**Comment by SysPete** [comment]
Does anyone have any news about tobyink or a possible fork & new maintainer? If it is likely that something might happen soon I'd prefer to avoid the revert since it adds work elsewhere. If there is nothing on the horizon then I agree that a revert is the sane option.

**Comment by veryrusty** [comment]
We've reverted the change to use Type::Tiny in #1220.  (Thanks again @SysPete).  Dancer2::Types uses MooX::Type::MooseLike again until the current Type::Tiny maintenance issues are resolved.

**Comment by SysPete** [comment]
Closing this issue now that Dancer v0.202000 has been released which includes #1220 which reverts back to using MooX::Types::MooseLike.
