### ISSUE TITLE
Make sure all Session engines work with current release

### ISSUE THREAD

**Issue by SysPete** [PerlDancer/Dancer2#1181]
List does not include engines that ship with Dancer2 (Simple and YAML).

| Engine | CPAN | repo | Date checked | _change_id support ? | Status |
| --- | --- | --- | --- | --- | --- |
| CGISession | [CPAN](https://metacpan.org/pod/Dancer2::Session::CGISession) | [GitHub](https://github.com/pierre-vigier/Dancer2-Session-CGISession) | 2016-08-16 | :+1: | :+1: |
| Cookie | [CPAN](https://metacpan.org/pod/Dancer2::Session::Cookie) | [GitHub](https://github.com/PerlDancer/Dancer2-Session-Cookie) | 2016-08-16 | :+1: (actually a noop) | :+1: |
| DBIC | [CPAN](https://metacpan.org/pod/Dancer2::Session::DBIC) | [GitHub](https://github.com/interchange/Dancer2-Session-DBIC) | 2016-07-07 | :+1: | :+1: |
| JSON | [CPAN](https://metacpan.org/pod/Dancer2::Session::JSON) | [GitHub](https://github.com/PerlDancer/dancer2-session-json) | 2016-07-07 | :+1: (SessionFactory::File) | :+1: |
| Memcached | [CPAN](https://metacpan.org/pod/Dancer2::Session::Memcached) | [GitHub](https://github.com/PerlDancer/dancer2-session-memcached) | 2016-08-16 | :+1: | :+1: |
| MongoDB | [CPAN](https://metacpan.org/pod/Dancer2::Session::MongoDB) | [GitHub](https://github.com/PerlDancer/dancer2-session-mongodb) | 2016-08-18 | :+1: | :+1: |
| PSGI | [CPAN](https://metacpan.org/pod/Dancer2::Session::PSGI) | [GitHub](https://github.com/veryrusty/dancer2-session-psgi) | 2016-07-07 | :+1: | :+1: |
| Redis | [CPAN](https://metacpan.org/pod/Dancer2::Session::Redis) | [GitHub](https://github.com/burnersk/Dancer2-Session-Redis) | 2016-08-16 | :+1: | :+1: |
| Sereal | [CPAN](https://metacpan.org/pod/Dancer2::Session::Sereal) | [GitHub](https://github.com/PerlDancer/dancer2-session-sereal) | 2016-08-16 | :+1: (SessionFactory::File) | :+1: |

**Comment by SysPete** [comment]
For some $customer work I need all of these to be working. I've been given co-maint on Redis and have released a new version fixing its issues. Will start looking at the others over the weekend.

**Comment by cromedome** [comment]
@SysPete Think we missed closing this. Reopen if I'm wrong :)
