### ISSUE TITLE
t/classes/Dancer2-Core-Request/new.t fails with perl 5.25.1

### ISSUE THREAD

**Issue by eserte** [PerlDancer/Dancer2#1185]
After patching Type::Tiny it's possible to build and test Dancer2 on perl 5.25.1 --- but one test fails:
```
    #   Failed test 'Dancer2::Core::Request->can(...)'
    #   at t/classes/Dancer2-Core-Request/new.t line 192.
    #     Dancer2::Core::Request->can('accept_charset') failed
    #     Dancer2::Core::Request->can('accept_encoding') failed
    #     Dancer2::Core::Request->can('accept_language') failed
    #     Dancer2::Core::Request->can('connection') failed
    #     Dancer2::Core::Request->can('keep_alive') failed
    #     Dancer2::Core::Request->can('x_requested_with') failed

    #   Failed test 'Request successful'
    #   at t/classes/Dancer2-Core-Request/new.t line 263.
    # Looks like you failed 2 tests of 6.

#   Failed test 'Defaults'
#   at t/classes/Dancer2-Core-Request/new.t line 267.
# Looks like you failed 1 test of 9.
t/classes/Dancer2-Core-Request/new.t ................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/9 subtests 
```
@andk: looks like a bisect candidate.

**Comment by andk** [comment]
Hey, I got this in my inbox, interesting, so github does have a CC feature.

Bisect leads us to v5.25.0-71-g5d32d26, same as https://rt.perl.org/rt3/Ticket/Display.html?id=128179

**Comment by andk** [comment]
Oops, I spoke too soon. There is randomness involved. I now see various successes with 71 and after

**Comment by andk** [comment]
No, it was not randomness, my bisecting was not paying attention to the distroprefs needed. With manual help now we have a new bisect result arriving at v5.25.0-80-g2e6807b

A BBC is broadcasted as https://rt.perl.org/Ticket/Display.html?id=128352

Thanks!

**Comment by xsawyerx** [comment]
Thank you, @eserte and @andk!
