### ISSUE TITLE
Nammed capture regex messing with the routing engine

### ISSUE THREAD

**Issue by pierre-vigier** [PerlDancer/Dancer2#1191]
Hi,

in a test script, i was exposed to some strange behavior when parsing a response with a nammed capture regex. After using the regex, all the requests were defaulted to the same route. Scoping the regex solved the issue.
I wrote a small piece of code to show case the issue.

```perl
package app;
use Dancer2;
get '/1' => sub {
    return '1';
};
get '/2' => sub {
    return '2';
};
package main;
use Plack::Test;
use HTTP::Request;

my $test = Plack::Test->create( app->to_app );
my $request  = HTTP::Request->new( GET => 'http://localhost/1' );
my $response = $test->request( $request );
print $response->content, "\n";
"12345" =~ m#(?<capture>23)#;
my $c = $+{capture};
$request  = HTTP::Request->new( GET => 'http://localhost/2' );
$response = $test->request( $request );
print $response->content, "\n";
```

That piece of code is display
```
1
1
```

If i use a regex without nammed capture, it is then working correctly
```perl
"12345" =~ m#(23)#;
my $c = $1
```

If i scope the regex part, it's working as well
```perl
{
    "12345" =~ m#(?<capture>23)#;
    my $c = $+{capture};
}
```

Both of those version display 1 and then 2 as expected.

I can reproduce on Dancer2 0.166001 and Dancer2 0.200001 , the problem is present on perl 5.16.3 and 5.24.0 , i did not try other version of perl.

Pierre

**Comment by demerphq** [comment]
Fixed in:

https://github.com/PerlDancer/Dancer2/pull/1258

Simple explanation, use of regex vars without properly checking that the pattern matched. Since pattern vars are dynamically scoped this means the Dancer2 internals read the state of an external pattern.

**Comment by xsawyerx** [comment]
Fixed by @demerphq in PR. Merged.
Thanks! :+1:
