### ISSUE TITLE
[PATCH] spelling fix

### ISSUE THREAD

**Issue by gregoa** [PerlDancer/Dancer2#1193]
In Debian we are currently applying the following patch to Dancer2.
We thought you might be interested in it too.

    Description: spelling fix
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-06-28
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libdancer2-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by cromedome** [comment]
Merged. Thanks for spotting and fixing!

**Comment by gregoa** [comment]
On Tue, 28 Jun 2016 13:19:35 -0700, Jason A. Crome wrote:

> Merged. Thanks for spotting and fixing!

Wow, that was fast -- thanks to you!

Cheers,
gregor

-- 
 .''`.  Homepage https://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-
