### ISSUE TITLE
Should we move to `JSON::MaybeXS`?

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#1196]
We currently use [JSON](https://metacpan.org/pod/JSON), but it both has issues and is in pure-Perl. [JSON::XS](https://metacpan.org/pod/JSON::XS) is useful but it's only XS and the author is... well, yes. [JSON::MaybeXS](https://metacpan.org/pod/JSON::MaybeXS) is both optionally XS (which means users with XS will have it installed automatically) and first attempts to load the cPanel JSON::XS implementation, which has a better maintainer, IMHO.

This means also recommending the cPanel variation of JSON::XS, which I would honestly prefer.

**Comment by cromedome** [comment]
I’ve heard nothing but good things about Cpanel::JSON::XS. I’d have no problem making these changes. +1.

**Comment by SysPete** [comment]
:+1: JSON::MaybeXS does seem to be the way to go. I've had to switch some modules over already due to the known JSON::XS issues.

**Comment by racke** [comment]
:+1:  Please go ahead.

**Comment by ambs** [comment]
Changed labels. If anyone start working on this, please warn here ;-)

**Comment by nunorc** [comment]
PR https://github.com/PerlDancer/Dancer2/pull/1212 is a tentative pull request to move serializer to JSON::MaybeXS. Comments and feedback are welcome. Thank you.

**Comment by cromedome** [comment]
Closed by PR #1212. Thanks @nunorc!
