### ISSUE TITLE
t/deserialize.t broken by downstream dep?

### ISSUE THREAD

**Issue by exodist** [PerlDancer/Dancer2#1197]
http://www.cpantesters.org/cpan/report/25911c10-4199-11e6-8d7d-86c55bc2a771
http://www.cpantesters.org/cpan/report/284ac158-419a-11e6-9a35-e3e15bc2a771

I was doing downstream testing for a newly released Test2. Dancer2 failed to install. I rolled back Test2 on my perlbrew but Dancer2 still failed. I found the above cpantesters reports that also show the problem, but on an older Test2 that is known to have worked (other reports show it).

I have not found out what is actually causing the breakage, and I do not have time to keep digging right now.

**Comment by shadowcat-mst** [comment]
YAML 1.16, released yesterday, produces an earth shattering kaboom.

YAML 1.15 appears not to result in an unexpected exothermic event.

**Comment by racke** [comment]
Fixed by YAML 1.17 and update to Dancer's dist.ini.
