### ISSUE TITLE
subroutine 'dancer_app' redefined

### ISSUE THREAD

**Issue by girlwithglasses** [PerlDancer/Dancer2#1202]
Since upgrading to Dancer2 0.2, I've been getting these errors when I run my apps:

```
Subroutine dancer_app redefined at (eval 795) line 5.
Subroutine request redefined at (eval 795) line 14.
Subroutine var redefined at (eval 795) line 23.
Subroutine hook redefined at (eval 795) line 32.
```

Is there a reason why these have started appearing, and if so, do I need to change my code to stop them showing up?

**Comment by SysPete** [comment]
@girlwithglasses my first guess is that you have some plugins installed that need upgrading for compatibility with 0.2. Most plugins have updated versions available on CPAN and we track compatibility via issue #1078. So perhaps you just need to uprgade some of your plugins.

**Comment by girlwithglasses** [comment]
Ah thanks -- it was the plugins that were causing the problem. I'll close this and request that the authors update their code.

**Comment by SysPete** [comment]
@girlwithglasses please let me know via this issue which plugins you have a problem with and I will work with the plugin authors to get updates done.

**Comment by girlwithglasses** [comment]
The plugins I'm using are:
* Dancer2::Plugin::Ajax
* Dancer2::Plugin::Approle::Helper: [MetaCPAN](https://metacpan.org/release/Dancer2-Plugin-AppRole-Helper), [GitHub](https://github.com/wchristian/Dancer2-Plugin-AppRole-Helper)
* Dancer2::Plugin::Cache::CHI
* Dancer2::Plugin::LogContextual

(those with no links are already in your list)

LogContextual seems to be the one causing trouble.

**Comment by SysPete** [comment]
On 06/07/16 20:58, girlwithglasses wrote:
>
> The plugins I'm using are:
>
>   * Dancer2::Plugin::Ajax
>   * Dancer2::Plugin::Approle::Helper: MetaCPAN
>     <https://metacpan.org/release/Dancer2-Plugin-AppRole-Helper>,
>     GitHub <https://github.com/wchristian/Dancer2-Plugin-AppRole-Helper>
>   * Dancer2::Plugin::Cache::CHI
>   * Dancer2::Plugin::LogContextual
>
> (those with no links are already in your list)
>
> LogContextual seems to be the one causing trouble.
>
Hmm. LogContextual has no tests so I haven't looked at it yet and it is
almost certainly going to be broken with Dancer2 .02+. I'll have a look
at it tomorrow and see if I can create a PR that fixes the main issues.

Thanks for hanging in on this. Hopefully we can get things working for
you ASAP.
