### ISSUE TITLE
plugin2-compat plugins might add hooks more than once

### ISSUE THREAD

**Issue by SysPete** [PerlDancer/Dancer2#1211]
Note: this is NOT an issue for pure plugin2 plugins but only ones making use of the compat layer and only if they add hooks.

In a multi-file app a plugin might need to be imported in more than one class inside the app. It appears that for plugin2-compat plugins any hooks end up being added every time the plugin is imported which means that hooks can end up being called multiple times. This might not be an issue but it certainly was for `Dancer2::Plugin::Deferred` - see: https://github.com/PerlDancer/dancer2-plugin-deferred/pull/9

Converting the plugin to pure plugin2 style fixes such issues. I wonder if it is possible to adjust compat mode to handle this? Otherwise we need to get on with upgrading plugins that call hooks.

**Comment by xsawyerx** [comment]
Do we want to fix it?

**Comment by cromedome** [comment]
Is this still a concern? At this point I would hope not. Suggest closing. Thoughts?

**Comment by SysPete** [comment]
I agree. Closing...
