### ISSUE TITLE
What is the ENV variable DANCER2_SHARE_DIR for?

### ISSUE THREAD

**Issue by cromedome** [PerlDancer/Dancer2#1215]
Can someone tell me what `DANCER2_SHARE_DIR` is for, or what the intent was behind it? I found it here: https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/CLI/Command/gen.pm#L62

It is not documented anywhere, and if it was trying to solve a problem, I'd like to understand what it was so we can document it. Failing that, I'd like to remove it.

Any insight is appreciated. Thanks!

**Comment by veryrusty** [comment]
After a little spelunking through git history:

`$ENV{DANCER2_SHARE_DIR}` looks like it was introduced to solve a bootstrapping problem; `dist_dir('Dancer2')` wouldn't have contained a `skel` before the CLI was released.

TWO years later the `skel` option was added to the CLI to support basically the same thing, and is documented.

:+1: for removing `DANCER2_SHARE_DIR`

**Comment by racke** [comment]
:+1: too

**Comment by xsawyerx** [comment]
:+1:

**Comment by cromedome** [comment]
Resolved by b37fe8a02d56eeb7814f2b656e96ffc177237d3b. Closing. Thanks everyone!
