### ISSUE TITLE
Please remove me from list of core developers

### ISSUE THREAD

**Issue by xdg** [PerlDancer/Dancer2#1218]
I don't have any active role anymore.  Please just list me among contributors.  Thanks!

**Comment by SysPete** [comment]
@cromedome suggested a new CORE DEVELOPERS EMERITUS section. :+1: from me on that.

**Comment by cromedome** [comment]
Resolved by 7f9fff858d52fe3d27ee794b025411d3eaeb658e. Thanks, @xdg for all you have done for us!
