### ISSUE TITLE
Can't call method "cookies" on an undefined value 

### ISSUE THREAD

**Issue by shardiwal** [PerlDancer/Dancer2#1221]
Can't call method "cookies" on an undefined value at /usr/local/share/perl/5.18.2/Dancer2/Core/App.pm line 1142.

Guys i am migrating my app from Dancer to Dancer2, Authentication works, but keep on getting the above error. Migration of param/params are required to do ?

Can you please guide on what's causing this issue ?

**Comment by shardiwal** [comment]
Calling session->read('user_id'); on Dancer2 application, pops error "Can't call method "cookies" on an undefined value"

**Comment by veryrusty** [comment]
@shardiwal *where* are you calling `session`?

( There are some comments in #1107 if you are calling session outside of a route. )

**Comment by xsawyerx** [comment]
@shardiwal Any update?
