### ISSUE TITLE
Plugins cannot access DSL from other plugins

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#1230]
This is an issue related to GH #1226, but in this case it's plugins accessing DSL by other plugins.

```perl
package MyApp {
    use Dancer2;
    use Dancer2::Plugin::Foo;
}

package Dancer2::Plugin::Foo {
    use Dancer2::Plugin;
    use Dancer2::Plugin::Bar;
    plugin_keywords('outer');
    sub outer { inner() }
}

package Dancer2::Plugin::Bar {
    use Dancer2::Plugin;
    plugin_keywords('inner');
    sub inner {1}
}
```

We have a Dancer App which loads a plugin which then loads another plugin. Both plugins have DSL keywords. Currently the second plugin (`Bar`) has a keyword (`inner`) which will never be exposed anywhere. It is not available to the App or to the first plugin (`Foo`).

**Comment by cromedome** [comment]
Merged with 9775d0031248fd41999e3dcff2094e0d228638d3. Closing!
