### ISSUE TITLE
request->body_parameters empty when body contains serialized (JSON) data

### ISSUE THREAD

**Issue by veryrusty** [PerlDancer/Dancer2#1232]
If a request contains serialized JSON, *and* some middleware wrapping the app created a Plack::Request object and called a method on that that causes the body to be read, then `$env->{'plack.request.body'}` is set to an empty Hash::MultiValue object (empty implying it has no keys).

Then within Dancer2, the logic to trigger deserializing of body params (https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Core/Request.pm#L368) fails, as that env key already exists.

I'm working on a test case. ~~Not sure what the best fix is at the moment.~~

**Comment by veryrusty** [comment]
Also; we spec'd the deserialization to return decoded (character) data. There is no need to decode that again (see https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Core/Request.pm#L372 )

**Comment by cromedome** [comment]
Resolved in 2f3579408e5a79ae25dc71dfb09b27ba96f123e9. Closing!
