### ISSUE TITLE
Dependency on List::Util not declared

### ISSUE THREAD

**Issue by andk** [PerlDancer/Dancer2#1237]
Here List::Util is used:

https://metacpan.org/source/CROMEDOME/Dancer2-0.203000/lib/Dancer2/Core/HTTP.pm#L8

But where is the dependency declaration?

HTH&&Thanks,

**Comment by andk** [comment]
Sample fail report:

http://www.cpantesters.org/cpan/report/72472957

**Comment by veryrusty** [comment]
Hmmm; List::Util has been in core since perl 5.7

However the `pair*` functions used here were added in List::Util v1.29. 

@andk Pr's greatly appreciated (add it to `dist.ini`)

**Comment by veryrusty** [comment]
We now specify List::Util v1.29 as the minimum required. (Pr #1238)

Thanks for reporting this @andk.
