### ISSUE TITLE
body_parameters not always being decoded

### ISSUE THREAD

**Issue by SysPete** [PerlDancer/Dancer2#1243]
I have not been able to reproduce this in a test. See 52e6d529a9d147aabde2e466f5dceb5950ac2e29 for a hack which fixes my app but breaks tests added in #1232

**Comment by veryrusty** [comment]
I suspect the same applies to query parameters. See these two lines:
 *  https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Core/Request.pm#L356
 *  https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Core/Request.pm#L375

Both `$self->SUPER::query_parameters` and `$self->SUPER::body_parameters` return Hash::MultiValue objects. Calling `_decode_ on those isn't going to do what we want..

**Comment by veryrusty** [comment]
(deleted my previous incorrect comment)

@SysPete your "hack" is correct.  We need to stash the *decoded* body parameters separately from the plack request's stash of the (encoded) body parameters. Mixing the two (as we were) causes headaches..

**Comment by veryrusty** [comment]
I've rebased and amended @SysPete's commit so that deserialized data is stashed in the same way, so the tests added in 1232 pass. See 96e662a.

**Comment by cromedome** [comment]
Per discussion with @SysPete this can be closed. Thanks!
