### ISSUE TITLE
304 (Not Modified) for static files or send_file(...)

### ISSUE THREAD

**Issue by vanHoesel** [PerlDancer/Dancer2#1253]
A server can respond with a `Last-Modified` header. This enables (intermediate) caches to revalidate stale responses with a requests that includes a `If-Modified-Since`.

The expected response on such a revalidation request should (in general) either be a `200 (OK)` response or hopefully a `304 (Not Modified)`. The latter one, as might be clear from the description, indicaties that the stored response in the cache is still valid and that the cache can use it to respond to it's client. If the resource or webpage or file has changed since that timestamp, it must return a `200 (OK)` response, and the full payload or body.

When the Dancer2 Framework (out of the box) serves a static file from the `public` directory or when `send_file` has been called, it does send a `Last-Modified` HTTP date, based on the file-system. All good and well, however, when a client or cache would then later try to do a revalidation request, the framework does not respond with a `304` ever, even though the file has not been changed. It will always (assuming no errors occurred) a `200 (OK)` status.

I'd love to see that my favorite web-framework would do the right thing. The current solution is not disastrous, it only slows down the internet tremendously. Wouldn't it be nice that even novice and medium experienced users of Dancer2 would get the right responses, without  the need of installing another proxy server in front of Dancer2 ?

Please make it return a `304 (Not Modified)` when applicable.

Cheers, and happy dancing

**Comment by veryrusty** [comment]
Thanks for raising the issue @vanHoesel.

This is something we'll need to work with upstream authors to remedy. Work is in process to do so.

Until then; depending on exact requirements one can implement the bulk of the requirements for `Not Modified` responses by using the ConditionalGET middleware in the app.psgi file:

```
use strict;
use warnings;

use Plack::Builder;
use Plack::Middleware::ConditionalGET;
use Plack::App::File;

use MyApp;

my $app = MyApp->to_app;
my $builder = Plack::Builder->new();

# static content paths
my $public_dir = MyApp->config->{public_dir}
for my $path (qw/css fonts images js/) {
    $builder->mount( "/$path" => builder {
          enable "Plack::Middleware::ConditionalGET";
          Plack::App::File->new( root => "$public_dir/$path" )->to_app;
    });
}

# mount application itself at '/'
$builder->mount('/' => $app);

# return the PSGI coderef
$builder->to_app;
```

**Comment by veryrusty** [comment]
Upstream PR:  https://github.com/plack/Plack/pull/575

**Comment by SysPete** [comment]
@veryrusty :hugs: :beers:

**Comment by cromedome** [comment]
Resolved by a803b0a7ecc939bef3a0aae5bdd3cf8e25160ad3. Closing.

**Comment by vanHoesel** [comment]
Thank you guys for solving this issue!!! 

🍻

a bit more complicated than what I had in mind with:
https://github.com/THEMA-MEDIA/Dancer2/commit/5f5267dc51d6dbacb9e978193a8c2abe43ff612b

but also a better solution!

**Comment by vanHoesel** [comment]
is there any way to get metrics about this change and how some browser benefit from it, some life Dancer applications out there that have quite some static content? Can we see how fast the build a web page before and after the change ?

**Comment by xsawyerx** [comment]
Do you mean loading a page?

It depends on the speed of the user's and server's network.

**Comment by xsawyerx** [comment]
And how many static files are part of the loading process. Do you streamline all CSS files into one? Do you use sprite images? Stuff like that affect the numbers from being 10-20 files to being 2, for example.
