### ISSUE TITLE
Should lack of Test::Perl::Critic prevent install?

### ISSUE THREAD

**Issue by nanis** [PerlDancer/Dancer2#1273]
I am asking this question, because I just ran into this on my test rig. `cpanm Dancer2` failed because `Test::Perl::Critic` depends on `MCE`  and it looks like some MCE tests are crashing with the particular build of `perl` (never had problems before, and I haven't diagnosed it yet).

But, this made me think about why there is a `test_requires 'Test::Perl::Critic';` in `cpanfile` and
```
"TEST_REQUIRES" => {
    "Test::Perl::Critic" => 0
  },
```
in `Makefile.PL`.

It seems to me that critic tests are for authors only, and the failure to run or pass those tests should not prevent an **automated** test/install of `Dancer2`? Of course, if I just unpack the distribution and do `nmake test`, I get the warning:

```
# *** WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING ***
#
# The following REQUIRED prerequisites were not satisfied:
#
# Test::Perl::Critic is not installed (any version required)
```

but all tests pass.

**Comment by xsawyerx** [comment]
Oh dear! No. This shouldn't happen!

**Comment by xsawyerx** [comment]
Fixed by @episodeiv and merged!

Thanks!

**Comment by nanis** [comment]
Thank you.
