### ISSUE TITLE
Expose `route_parameters`, `query_parameters`, and `body_parameters` as methods when rendering a view

### ISSUE THREAD

**Issue by mcmillhj** [PerlDancer/Dancer2#1284]
In https://github.com/PerlDancer/Dancer2/pull/1280 it was pointed out that these keywords are not available when rendering a view with the `template` keyword, but `params` is exposed. The suggested solution was to expose them as methods similar to `request` and `response`.

**Comment by xsawyerx** [comment]
I was thinking about this further and I now consider this something that will make it much easier to repeat a very insecure pattern of using parameters as values in templates. This allows people to simply add XSS code directly.

**Comment by xsawyerx** [comment]
I am giving this one week before closing this ticket as "WONT FIX", since I consider this to be a terribly insecure practice.

**Comment by mcmillhj** [comment]
@xsawyerx I am fine with this being closed, I only created the PR based on discussions in #1280.

**Comment by xsawyerx** [comment]
You helped us flesh out this topic and reach what I would consider an important decision. Thank you. :)
