### ISSUE TITLE
request->uploads are discarded after a forward

### ISSUE THREAD

**Issue by ghost** [PerlDancer/Dancer2#1289]
In the first handler of a route, the `request->uploads` hash contains the expected upload objects.  Following a `forward`, the `request->body` still contains the uploaded content but the `request->uploads` hash is empty and `upload($file)` is undefined.

**Comment by xsawyerx** [comment]
@Mr-Ash Thank you for opening this ticket. Would it be possible for you to write up a test we could use to fix this?

**Comment by ccntrq** [comment]
It seems the issue has been solved since it has been openen. I will work on a testcase.

**Comment by cromedome** [comment]
Resolved by #1558. Thank you!
