### ISSUE TITLE
Problem with Plack::Builder mount and redirect on index

### ISSUE THREAD

**Issue by mziescha** [PerlDancer/Dancer2#1296]
Hey,

I'm trying to use the mount function with Plack::Builder like the following stuff:
`use Plack::Builder;
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../../perl5/lib/perl5/";
use MyApp::Main;
use MyApp::Moderation;
use MyApp::Admin;
use MyApp::Assets;

sub main {
    builder {
        mount '/'       => MyApp::Main->to_app;
        mount '/moderation' => MyApp::Moderation->to_app;
        mount '/admin'      => MyApp::Admin->to_app;
        mount '/assets'     => MyApp::Assets->to_app;
    };
}
main(@ARGV);`

Now I'm trying to redirec to the index site if no session is set

`get '/' => sub {
        return (session('stuff')) ? template 'admin/index' : redirect '/';
};`

The result is a redirection error because of to many 302 redirections.
It seems the redirection to index isn't the absolute index to / but to /admin/.

I hope someone can help.

**Comment by SysPete** [comment]
Hi @mziescha 

Yes: `redirect` uses `uri_for` which returns the uri based on the current app's mount point. You could use [Dancer2::Plugin::RootURIFor](https://metacpan.org/pod/Dancer2::Plugin::RootURIFor) something like this instead:
```
use Dancer2::Plugin::RootURIFor;
get '/' => sub { return (session('stuff')) ? template 'admin/index' : redirect root_uri_for('/'); };
```
Perhaps we need to add something to the docs for `redirect` to make its behaviour clearer and also perhaps link to this plugin as well? Additions welcome.

**Comment by mziescha** [comment]
Appending to the Cookbook it would be nice to write like that:
Then those will be mounted together for a single app:
 
     # handler: app.pl:
     use MyApp;
     use MyApp::API;
     use Plack::Builder;
 
     builder {
         mount '/'    => MyApp->to_app;
         mount '/api' => MyApp::API->to_app;
     };

redirect routing between mounting apps it's helpful to use Dancer2::Plugin::RootURIFor:

     # package:
     package MyApp::App;
     use Dancer;
     use Dancer2::Plugin::RootURIFor;
     
     get '/' => sub {
         redirect root_uri_for('/');
     }

     # handler: app.pl:
     use MyApp;
     use MyApp::API;
     use Plack::Builder;
 
     builder {
         mount '/'    => MyApp->to_app;
         mount '/app' => MyApp::App->to_app;
     };

I think that would be helpful.

**Comment by xsawyerx** [comment]
@mziescha Would you like to submit this addition to the Cookbook? :)

**Comment by mziescha** [comment]
@xsawyerx I created a pull request #1298 but in the Manual.pod. Appending at the basicaly usage for Plack::Builder. I will change it to Cookbook if it's better placed there.

**Comment by mziescha** [comment]
@xsawyerx about the sample for Dancer2::Plugin::RootURIFor I wrote it into the Cookbook :-)
The changes are in the pull request #1298.
