### ISSUE TITLE
JSON serializer not honouring config in send_as

### ISSUE THREAD

**Issue by kwakwaversal** [PerlDancer/Dancer2#1302]
This will apply to other serializers, but I'm referring specifically to JSON.

https://github.com/PerlDancer/Dancer2/blob/0234f4edfc4c8b6a92a3a640514518820f388bb6/lib/Dancer2/Core/App.pm#L958

```perl
    # load any serializer engine config
    my $engine_options =
        $self->_get_config_for_engine( serializer => $type, {} ) || {};
    my $serializer = $serializer_class->new( config => $engine_options );
```

The config parameter to `_get_config_for_engine` is always empty, so it will always return empty options. My proposed "fix" for this will be adding `$self->config()` as the third parameter.

```perl
    # load any serializer engine config
    my $engine_options =
        $self->_get_config_for_engine( serializer => $type, $self->config ) || {};
    my $serializer = $serializer_class->new( config => $engine_options );
```

I'm willing to update the `t/dsl/send_as.t` unit test to make sure that it uses `allow_blessed` and `convert_blessed` options as an example of it honouring the config parameter. Please can someone confirm this is an acceptable fix, and that I'm not breaking anything outside of my domain knowledge of D2.

Thanks!

**Comment by kwakwaversal** [comment]
To add to this, it's only in `send_as` that it's not honouring the config. When used in conjunction with `set serializer => 'JSON';` it uses the serializer config as expected. This is due to `send_as` instantiating a new serializer object in the `send_as` method, which doesn't have access to the app's `config`.

**Comment by xsawyerx** [comment]
Skimming through this quickly, I think it's a good solution. I would be happy to have a bit more time to review this appropriately.

**Comment by cromedome** [comment]
Just merged the PR for this. Thank you!
