### ISSUE TITLE
Not start Dancer 0.204003

### ISSUE THREAD

**Issue by h707** [PerlDancer/Dancer2#1307]
Dancer 0.204003, perl v5.22.1, Ubuntu 16.04.
Do not start Dancer after upgrading 0.204002, the logs are empty.

In the message browser Hu [] [PROCESS'mdlwi ']
The source code messages in the browser:
`<!DOCTYPEhml><hmll="u"><hd><mhp-quiv="C-yp"="x/hml;h=[ih]"/><il>Hu</il><likl="ylh"h="[quui_b]//bpmi"/> ...`

**Comment by h707** [comment]
In the message browser Hu [] [PROCESS'mdlwi ']

**Comment by housah** [comment]
Have the same issue, i guess... all i get in the browser is: App[INCLUDE'vb'][]
Dancer2 0.204003, Perl  v5.16,  CentOS 7.3.1611

**Comment by h707** [comment]
The source code messages in the browser:
<!DOCTYPEhml><hmll="u"><hd><mhp-quiv="C-yp"="x/hml;h=[ih]"/><il>Hu</il><likl="ylh"h="[quui_b]//bpmi"/> ...

**Comment by SysPete** [comment]
The most likely suspect is probably #1250 since that changed TT and I don't have any issues in my projects, none of which use Template::Toolkit. I'll have a proper look later today.

**Comment by SysPete** [comment]
@h707 @housah can you share your `engines => template` section of your configs? I've tested a new app but all is working fine and I don't have anything else to test with.

**Comment by housah** [comment]
@SysPete here you go:

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      START_TAG: '[%'
      END_TAG:   '%]'

**Comment by SysPete** [comment]
Now that is scary. My test app was using `<% %>` so I switched it to `[% %]` and all hell broke loose...
```
$ wget -O - http://localhost:5000/
--2017-01-26 15:57:10--  http://localhost:5000/
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:5000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 348 [text/html]
Saving to: ‘STDOUT’

-                     0%[                      ]       0  --.-KB/s             <!DOCTYPEhml><hmll=""><hd><mh="[ih]"><mm="viwp"="widh=dvi-widh,iiil-l=10,u-lbl=y"><il>MyApp</il><likl="ylh"h="[quui_b]//yl"><!--GbjQuymCDN,llbklliy--><ip="//djquym/jquy-14mij"></ip><ipyp="x/jvip">/<![CDATA[/!widwjQuy&&dumwi'<ipyp="x/jvip"="[quui_b]/jvip/jquyj"><\/ip>'/]]>/</ip></hd><bdy>[]<divid="">Pwdby<h="hp://pld/">D-                   100%[=====================>]     348  --.-KB/s   in 0s     

2017-01-26 15:57:10 (44.8 MB/s) - written to stdout [348/348]
```

**Comment by housah** [comment]
@SysPete yep, that's pretty much it ...

**Comment by SysPete** [comment]
I can confirm a downgrade to 0.204002 fixes this problem so now to find out what broke things...

**Comment by housah** [comment]
@SysPete already try to downgrade, using force install of version 0.204002, and got the same issue while running the app :\

**Comment by SysPete** [comment]
Confirmed this was caused by commit 8d0f3b105897283f3c28eade020f0e01798923f5 introduced via PR #1250 so I created PR #1308. Not sure how fast we can get a new release out since usual release manager is off the grid for a few days.

**Comment by housah** [comment]
@SysPete just downgrade again, and didn't work, but then i changed "START_TAG" and "END_TAG", in the config, to lowercase again, now the app works again...

**Comment by nunorc** [comment]
@SysPete many thanks for the quick revert, still new release is required to everyone that already updated tho

**Comment by SysPete** [comment]
@housah cool - so at least you're not blocked for the time being. I've pinged team to see if a new release before Monday is possible but I don't know about availability of people with MAINT privs on CPAN so might have to wait.

@nunorc you're welcome. Clearly we were lacking tests for this problem commit and it certainly won't be going back in until those tests exist.

**Comment by housah** [comment]
@SysPete ok nice 👍 thanks for the help.

**Comment by nunorc** [comment]
@SysPete 👍

**Comment by xsawyerx** [comment]
Geez... this is crazy.

Anywho, new version out with the reverted change. Sorry about that, everyone!
