### ISSUE TITLE
Documentation for Dancer2::Core::Route->match is incorrect

### ISSUE THREAD

**Issue by simonbrent** [PerlDancer/Dancer2#1312]
The documentation says

```
my $match = $route->match( get => '/hello/sukria' );
```

but the code reads
```
sub match {
    my ( $self, $request ) = @_;
    ...
    my @values = $request->dispatch_path =~ $self->regexp;
```

so the argument to match must be a Dancer2::Core::Request object

**Comment by simbabque** [comment]
The change was introduced in https://github.com/PerlDancer/Dancer2/commit/a30d651c51bd73f538328e033562b2e5148b5f59, but the documentation was not updated.
