### ISSUE TITLE
META.yml does not require a specific version of ExtUtils::MakeMaker in build_requires section

### ISSUE THREAD

**Issue by atoomic** [PerlDancer/Dancer2#1315]
From META.yml file
```
build_requires:
  Capture::Tiny: '0.12'
  ExtUtils::MakeMaker: '0'
...
configure_requires:
  ExtUtils::MakeMaker: '7.1101'
  File::ShareDir::Install: '0.06'
```

Note that the minimal version for build_requires is 0 whereas it should be the same version specified in dist.ini

Suggestion add this to dist.ini
```
[Prereqs]
 ExtUtils::MakeMaker= 7.1101
```

**Comment by veryrusty** [comment]
Thanks @atoomic. Could you put a pull-request together with that suggested change?

**Comment by atoomic** [comment]
sure

**Comment by xsawyerx** [comment]
Solution merged. Thanks again! :+1:
