### ISSUE TITLE
Serializer configuration is not documented (?)

### ISSUE THREAD

**Issue by fgabolde** [PerlDancer/Dancer2#1317]
I had to go through the source of `Dancer2::Serializer::JSON` and `Dancer2::Core::Role::Serializer` to answer a coworker's question about configuring the serializer, specifically about setting `pretty` to a true value in dev/testing mode. I knew the answer but I wanted to double check, and there isn't anything that I can find in the documentation.

The serializer package doesn't mention that it can be configured at all; going up through the inheritance chain all the way to the engine role there is nothing about configuration either. If you don't know the internals of Dancer2 you might not realize that the serializer is an engine and so can be configured like the session and logger engines.

**Comment by sdeseille** [comment]
Hello 
I'm interested to work on that issue.
Can you remind me the best way to work on it ? 
I mean do i have to clone master repository or should i have to start with devel branch ?

regards
sdeseille

**Comment by sdeseille** [comment]
Hello

I just come to see documentation that answer to my question: 
https://github.com/PerlDancer/Dancer2/blob/master/GitGuide.md

I will follow that.

regards
sdeseille

**Comment by sdeseille** [comment]
Pull request submit. :)
https://github.com/PerlDancer/Dancer2/pull/1398

**Comment by cromedome** [comment]
Resolved by #1398. Closing. Thanks!
