### ISSUE TITLE
Can not set log level in config.yml

### ISSUE THREAD

**Issue by mark-00** [PerlDancer/Dancer2#1327]
My app is alway logging all core messages. I can not set the loglevel

It  has the following log settings

logger: console
behind_proxy: 1
engines:
  logger:
    console:
      log_level: info

I traced the problem to Dancer2\Core\App.pm? If I comment out the line below it seems to work ok. It seems that $config->{log} always has the value "core"

sub _build_logger_engine {
....
    exists $config->{log} and $logger->log_level($config->{log});
....

I also tried other logconfigs but that did not work
log: info
log_level: info
logger: console
behind_proxy: 1
engines:
  logger:
    console:
      log_level: info
      log: info

**Comment by mark-00** [comment]
There is some wrong with the logging but i can not put my finger on it. I will reopen the problem if i have a clear way to reproduce it.

**Comment by mark-00** [comment]
Ok I found a clear way to reproduce the problem

I create an app: /usr/local/bin/dancer2 -a dancertest
I start the app: plackup -r -R lib --port 3000 --server Starman --signal-on-term=QUIT --workers 5 bin/app.psgi
using the default config.yml  core messages are logged
[dancertest:1628] core @2017-03-03 12:53:07> looking for get / in /usr/local/share/perl5/Dancer2/Core/App.pm l. 35
[dancertest:1628] core @2017-03-03 12:53:07> Entering hook core.app.before_request in (eval 175) l. 1
[dancertest:1628] core @2017-03-03 12:53:07> Entering hook core.app.after_request in (eval 175) l. 1
10.254.3.222 - - [03/Mar/2017:12:53:07 +0000] "GET / HTTP/1.1" 200 5545 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
1

I then add the following lines to the config.yml
logger: console
log: info

The core log messages are still generated
Then I add the following lines in lib/dancertest.pm
set 'logger'       => 'console';
set 'log'          => 'debug';

The core log messages dissapear

**Comment by veryrusty** [comment]
That looks like the correct behaviour. `set log => 'debug'` filters out log messages lower in priority than `debug`. Core messages are lower in priority than debug.

You can see the priority assigned to the logging levels in `Dancer2::Core::Role::Logger`.

**Comment by mark-00** [comment]
yes the behavior is correct if I set in code: set log => 'debug' 
Not if I set it in the config file: log: info

**Comment by veryrusty** [comment]
Dancer2 configuration can come from multiple sources;  `./config.yml`, the environment config (in `./environments/*`), plus local overrides and hard-coded values in you app. They are merged left-to-right, that is, environment config has precedence over whats in config.yml

The default development environment file generated by the `dancer2` script includes `log: core`.
(see`./environments/development.yml` in your sample app). Hence you are seeing `$config->{log} = core`, which is having precedence over what you are setting in config.yml.

**Comment by mark-00** [comment]
Dang I missed the part of the environment specific configs in the manual.   Is just wanted to configure logging and only read that piece.  Did cost me a days work

May I can put in a feature request to add some core logging about how and which  config files are processed to spare others the same fate.

**Comment by xsawyerx** [comment]
Could you please change the title of this ticket to reflect what you wish to have?

**Comment by cromedome** [comment]
I have distilled the root issue into #1593. Closing. Thanks for the suggestion, @mark-00!
