### ISSUE TITLE
Can not set loglevel for session module

### ISSUE THREAD

**Issue by mark-00** [PerlDancer/Dancer2#1328]
I use Dancer2 version 0.204004 

I have written my own session module Dancer2::Session::Shibboleth
It uses the interface 'Dancer2::Core::Role::SessionFactory';

To log i use `$self->log_cb` for instance

```
sub _retrieve {
    my ( $self, $id ) = @_;
	$self->log_cb->("debug", "shibboleth Session _retrieve $id");
```

The loglevel I set in the app has no effect

```
set 'logger'       => 'console';
set 'log'          => 'info';
```

I traced back the problem to Dancer2::Core::App in the methode  _build_session_engine
I replaced the line
        `log_cb => sub { $weak_self->logger_engine->log(@_) },`
with
        `log_cb => sub { $weak_self->log(@_) },`
and then is seems to work ok

there is potentialy the same issue with `_build_template_engine` and `_build_serializer_engine`

**Comment by xsawyerx** [comment]
(I edited the ticket to improve the syntax, to make it more readable.)

**Comment by xsawyerx** [comment]
This seems like a case of aggressive caching. Is there any chance you can write a test to match? It would be easier to fix and make sure it doesn't come back.

**Comment by pdl** [comment]
We have also noticed that the log setting has no effect on engines. For instance the call to debug at https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Template/TemplateToolkit.pm#L86 prints a debug level message to loggers even when `log` is set to a higher level.

I don't think it is a caching issue, @xsawyerx - it just looks like the code is wrong. `$weak_self->logger_engine->log` unconditionally logs.  `$weak_self->log` calls a method like debug on the logger, which passes through `_should` to determine whether `log` should be called by the logger.

The change to replace log_cb as @mark-00 suggests looks like the right answer to me.

**Comment by veryrusty** [comment]
@pdl I concur; that code is wrong.

Would welcome a patch from anyone with that change to the `log_cb` to the three engines that get it initialized. Bonus if it has tests :)

(I'll even try to review the PR while on vacation!)

**Comment by pdl** [comment]
@veryrusty done. (But first, enjoy your holiday!)
