### ISSUE TITLE
Warning in Core::Request::_read_to_end() (Dancer2-0.205000)

### ISSUE THREAD

**Issue by NGEfreak** [PerlDancer/Dancer2#1336]
After #1290 Core::Request::_read_to_end() gives the following warning on Perl 5.10:

`Use of uninitialized value $buffer in length at [...]/Dancer2/Core/Request.pm line 509.`

On Perl 5.10 length(EXPR) gives a warning when EXPR is undefined. Looks like this behavior was changed in Perl 5.12+.

**Comment by SysPete** [comment]
Using `defined` rather than `length` would probably be a good move though tests needed of course: https://github.com/PerlDancer/Dancer2/pull/1290#issuecomment-257890068

**Comment by xsawyerx** [comment]
Fixed. Thanks!
