### ISSUE TITLE
app generator should output a helpful message about how to run the app

### ISSUE THREAD

**Issue by jasonblewis** [PerlDancer/Dancer2#1338]
when you generate an app with `dancer2 gen -a MyWeb::App`, it would be nice if the output gave a little message about how to run the newly created app.

perldoc dancer2 it suggests to run it like this:

```
The application is ready to serve:

        $ cd MyWeb-App
        $ plackup bin/app.psgi
        >> Listening on 127.0.0.1:3000
```
could a similar message be tacked onto the end of the generator app's output?

**Comment by cromedome** [comment]
Resolved by #1350. Closing! Thanks for reporting.
