### ISSUE TITLE
Perl6?

### ISSUE THREAD

**Issue by ryanerwin** [PerlDancer/Dancer2#1343]
Hello,

Just curious if you've got plans to make a Perl 6 version of Dancer?
I realize there is Bailador, but it doesn't seem to have nearly the features of Dancer.

Best,

**Comment by xsawyerx** [comment]
Hey,

None of us use Perl 6 or have any intent or interest at the moment in writing a Perl 6 version of Dancer2. We know there is Bailador, and there is now also Prancer, but we are not involved in either one.

All the best. :)
