### ISSUE TITLE
Spurious warning from Plugin.pm: Odd number of elements in hash assignment 

### ISSUE THREAD

**Issue by racke** [PerlDancer/Dancer2#1348]
Plugin.pm parses all `has` occurences in a plugin, but it can't cope with the following one:

```
has schema_object => (
    is => 'lazy',
    isa => InstanceOf('OpenAPI::Schema'),
);
```

It breaks it down the attribute parameters into 5 parts instead of 4:

is lazy isa InstanceOf OpenAPI::Schema

**Comment by veryrusty** [comment]
This isn't plugin or D2 related - a simple Moo class with the above isa (with round brackets) generates the same error.  The short version is: Use square brackets in your parameterized type definitions.

The "error" comes from how Type::Tiny parses that isa definition. Compare the output of these two:
 * `perl -MData::Dumper -MType::Parser -E'say Dumper Type::Parser::parse(q{InstanceOf("Foo::Bar")})'`
 * `perl -MData::Dumper -MType::Parser -E'say Dumper Type::Parser::parse(q{InstanceOf["Foo::Bar"]})'`
