### ISSUE TITLE
cookies don't default to HTTPOnly, despite the doco

### ISSUE THREAD

**Issue by bigpresh** [PerlDancer/Dancer2#1361]
albino reported on #dancer that they were seeing cookies set without HTTPOnly.

https://metacpan.org/pod/Dancer2::Core::Cookie#http_only claims "By default, cookies are 
 created with a property, named HttpOnly, that can be used for security, forcing the cookie to be 
 used only by the server (via HTTP) and not by any JavaScript code. If your cookie is meant to be 
 used by some JavaScript code, set this attribute to 0."

Yet, the http_only attribute defaults to 0 - https://metacpan.org/source/CROMEDOME/Dancer2-0.205001/lib/Dancer2/Core/Cookie.pm#L128-133

So, there's a choice to make here:

* Update the doco to match what the code currently does
* Update the code to do what the doco claimed it did.  This *could* bite some people who were accessing cookies via JS and having it work "by accident", but would be more secure, and align with the behaviour of session engines which *do* set httpOnly by default, so I think I'd prefer this.

I'd like feedback from the rest of the team as to which option they prefer, though.

**Comment by xsawyerx** [comment]
I think the second option. Security takes precedence, in my opinion.

**Comment by veryrusty** [comment]
I agree, make httpOnly the default.

**Comment by bigpresh** [comment]
Good stuff, sounds like we're all agreed :)  Thanks chaps.

**Comment by bigpresh** [comment]
(So, could you review PR #1362 and give it the nod? :) )

**Comment by bigpresh** [comment]
PR-1362 is merged, so closing this issue.
