### ISSUE TITLE
The "dancer2" script has an unpractical shebang

### ISSUE THREAD

**Issue by vpit** [PerlDancer/Dancer2#1366]
Hello,

The `dancer2` script has `#!/usr/bin/env perl` as its shebang. That makes it unusable if Dancer2 is not installed for the first `perl` in `PATH`.

My advice is to change it into `#!/usr/bin/perl` and let `ExtUtils::MakeMaker` translate it at install time to the full path of the perl Dancer2 is installed for.

Vincent

**Comment by ambs** [comment]
FIxed with 428fa22. Thanks for reporting.
