### ISSUE TITLE
XSS in Dancer2::Tutorial example

### ISSUE THREAD

**Issue by diocles** [PerlDancer/Dancer2#1368]
I noticed there is no HTML escaping in the template in the tutorial:

`<li><h2>[% entries.$id.title %]</h2>[% entries.$id.text %]`

Similarly to the paragraph on SQL injection, I think it would be nice to fix the XSS, and perhaps mention briefly why escaping matters.

**Comment by guest20** [comment]
This could be fixed by having the boiler plate apps use [Template::AutoFilter](https://metacpan.org/pod/Template::AutoFilter), who's default is to html escape content.

It does come with a "unstable until 1.0" warning though.
