### ISSUE TITLE
Serialization error : Trying to serialize a template to JSON.

### ISSUE THREAD

**Issue by jahagirdar** [PerlDancer/Dancer2#1372]
**Description** If one of the packages sets serializer (e.g. to JSON) then even HTML template based routes in other packages are serialized resulting in an error string of 
```
[serializerBug:20284] core @2017-08-16 10:04:12> Failed to serialize content: hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /usr/local/share/perl/5.22.1/Dancer2/Serializer/JSON.pm line 40. in /usr/local/share/perl/5.22.1/Dancer2/Core/Response.pm l. 260
```
# How to reproduce.

1. decompress the attached web app and run prove in the root folder.
OR
create an app using the command ` dancer2 -a serializerBug `

add api.pm file to lib folder with the following content
```
package api;
use Dancer2 appname=>'serializerBug';
set serializer=>'JSON';
get "/api/foo"=>sub {
        return {a=>'b'};
};
1
```
add `use api;` to lib/serializerBug.pm
run `prove`

Dancer Version `Dancer2 0.205001`
Perl Version `perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi`
[serializerBug.zip](https://github.com/PerlDancer/Dancer2/files/1227086/serializerBug.zip)

**Comment by xsawyerx** [comment]
This seems at first brush as though you have two packages with the same appname, trying to define two different serializers for them. That won't work. They will need different appnames.

Please refer to the following articles:
* http://advent.perldancer.org/2014/10
* http://advent.perldancer.org/2014/11

**Comment by duke-m** [comment]
the s/funny/interesting/ thing is I was able to reproduce the mentioned behaviour some times, but now I cannot anymore. I've even written a test facility to mass-test it, even with both plackup and (the one and only) starman.

**Comment by xsawyerx** [comment]
The reported problem is not a problem but expected behavior.

Dancer2 purposefully keeps one serializer for an app, no matter how many classes. The reporter created two classes with the same app and expects them to have different serializers. It's the opposite of what Dancer2 does on purpose.

The articles I mentioned hopefully explain this to a finer degree.

**Comment by duke-m** [comment]
Hi @xsawyerx, first of all (having the opportunity): thank you for your contributions and for Dancer2, which I have been using in production for some time.

I am aware of the fact that appname will extend an app. I just was not able to have a deterministic reproducibility (Dancer2 0.204004 / perl v5.20.3) of the reported behaviour which made me wonder why. Now all tests with the example (and with some changes) above run with 100% success. Before that in some cases I could reproduce it (all in the same environment with same code on a physical test server on the same day).

**Comment by xsawyerx** [comment]
I haven't tried the zip, but the description seems to me to be:

* Create an app by some name. Let's say MyApp. This will generate a `MyApp.pm`.
* Add another .pm file by a different name. `Extra.pm`, for example.
* In this file, use Dancer2 as `use Dancer2 'appname' => 'MyApp';`.
* Set a serializer in the second file, such as `set 'serializer' => 'JSON';`.
* Try to reach a path on `MyApp.pm`. This will fail.

Does that make sense? Maybe I missed something?

**Comment by duke-m** [comment]
yes, exactly. and now here everything behaves correctly and deterministic. maybe the test-server was undercaffeinated yesterday, too.

usually I do things like that:

```perl
use MyApp;
use MyApp::API;
#...
  builder {
      mount "/api" => builder {
          MyApp::API->to_app;
      };
      mount "/" => builder {
          MyApp->to_app;
      };
#...
```

TMTOWTDI

**Comment by jahagirdar** [comment]
@xsawyerx Thanks for the detailed response,

Till now I was using D2::P::REST to handle the mix of JSON and HTML routes.
I recently ran ` cpan-outdated    | cpanm ` after which I started seeing existing routes break :( along with an explicit message that the default serializer was being replaced by D2::P::REST 
As a first debug step I removed the REST Plugin and switched to mutable and then the JSON plugin...
resulting in this and bug reported in #1369 
I will try to go back to REST and see whether I can reproduce isolate and debug the original issue.

**Comment by xsawyerx** [comment]
@duke-m Those internal `builders` aren't doing anything and are making your app slower. You could just do: `mount '/' => MyApp->to_app;`. Otherwise, good.

@jahagirdar An alternative in the same app nowadays is to use `send_as` for a specific route response.

**Comment by duke-m** [comment]
Thanks for the info, but I see this as one solution to have different serializers. It's downside is that you have to maintain this outside /lib (maybe someone maintaining might wonder) and that, as you wrote, you have to build twice. Maybe I have to do more dancer2 thingies again :)
