### ISSUE TITLE
Make app->destroy_session a NO-OP when there's no session.

### ISSUE THREAD

**Issue by perlpilot** [PerlDancer/Dancer2#1376]
In some code at $work we have a logout route that looks something like this:
```
any '/logout' => sub {
    if (app->has_session && session->read("user_id")) {
        app->destroy_session;
    }
    # ... do some other stuff
}
```
For some reason the UI is firing that route twice and generating a 500 error on the call to `app->destroy_session`.  This appears to be because one of them calls it first, thus destroying the session, just before the second one also attempts to destroy the session.

Is there any reason `app->destroy_session` is not a NO-OP when there is no session?

btw, running Dancer2 0.205000.

**Comment by ambs** [comment]
Not being able to reproduce on 0.205002 with a double call to `app->destroy_session`.

**Comment by veryrusty** [comment]
I have no doubt that this can't be replicated when using `Session::Simple`. @perlpilot What session implementation are you using ?

**Comment by ambs** [comment]
I tried on `session_lifecycle` that tests three backends...

**Comment by cromedome** [comment]
I've not heard of this coming up again. We can revisit if it does.
