### ISSUE TITLE
`dancer2: command not found`

### ISSUE THREAD

**Issue by leegee** [PerlDancer/Dancer2#1379]
Been a while since I used Dancer, but need a very quick Perl web app.

Sadly, working on Snow Leopard.

Went to the homepage, http://perldancer.org/quickstart

Installed Dancer2 as instructed:

    curl -L http://cpanmin.us | perl - --sudo Dancer2

Then ran the suggested command:

    dancer2 -a MyWeb::App

Bash reports `dancer2: command not found`.

**Comment by StylusEater** [comment]
@leegee interesting... please let me know if `dancer2` is found after you close your existing terminal and spawn a new one. Please also paste the output from the Dancer2 install command (it should look like the following):

> $ curl -L http://cpanmin.us | perl - --sudo Dancer2
>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                 Dload  Upload   Total   Spent    Left  Speed
>100  298k  100  298k    0     0   218k      0  0:00:01  0:00:01 --:--:--  218k
> --> Working on Dancer2
> ...
> Successfully installed Dancer2-0.205001
> 105 distributions installed

**Comment by leegee** [comment]
Agh, thanks for implying the obvious -- ie read the output of the install
script.

Forgot I was on dratted Windows without make.

Cheers
Lee

**Comment by StylusEater** [comment]
@leegee so you're all set? I'll close this issue if you are. Thanks in advance for the reply.

**Comment by leegee** [comment]
Sorry and thanks again -- seems humans really do need sleep.
