### ISSUE TITLE
Custom error pages at wrong place

### ISSUE THREAD

**Issue by niceperl** [PerlDancer/Dancer2#1380]
I have built a Dancer2 app (version 0.205001) with the command line interface:

`%> dancer2 -a my_app`

The template toolkit was configured in this project.
The custom error pages created by the builder were placed at the "public" folder (`404.html` and `500.html`). Then in the application code, I tried to send a 404 error, but Dancer2 used its own page (and ignored the custom one). 

It works properly if I create a `404.tt` page at "views" folder.
Is this a bug in the CLI or a kind of feature that should be documented?

**Comment by cromedome** [comment]
Merged and fixed!
