### ISSUE TITLE
Error Handling and File Rendering self link in docs

### ISSUE THREAD

**Issue by szabgab** [PerlDancer/Dancer2#1385]
On https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Manual.pod

Error Handling have link that lead to itself. I think because there are two sections that are called `Error Handling`

File Rendering has a link titled `File Rendering` leading to file-handler.

Both seem to be a bit confusing.

**Comment by cromedome** [comment]
Went ahead and merged the PR for this. I can reopen if it is still a problem later. This looked great to me though!
