### ISSUE TITLE
Add examples to the repository and maybe even install them as well

### ISSUE THREAD

**Issue by szabgab** [PerlDancer/Dancer2#1386]
e.g. create and examples/ directory and in there
create examples/single for examples that only have a single psgi file and thus don't interfere with each other.
create a separate subdirectory for every other example that has multiple files templates etc.
Add tests for each example

**Comment by cromedome** [comment]
Closed by 63db51bfb83ce18f38f7f219cb90ca37a1db6d58. Thanks!
