### ISSUE TITLE
Making commits to tutorial?

### ISSUE THREAD

**Issue by sdondley** [PerlDancer/Dancer2#1405]
I'm thinking about making some commits to the tutorial page. After downloading the git repo, I notice the POD lines are wrapped neatly. The max line is 83 chars. Are files run through perltidy here on git hub before getting committed? Or do I have to do that myself?

**Comment by cromedome** [comment]
Someone might have run this through perltidy in the past, but I am not in the habit of using perltidy when prepping for a release. I typically try to wrap things short of 80 characters myself though.

Feel free to use perltidy on your PRs by all means, but I'd recommend against running perltidy on a whole file you are making changes to. Thanks!
