### ISSUE TITLE
Documentation on contributing via github?

### ISSUE THREAD

**Issue by sdondley** [PerlDancer/Dancer2#1407]
I stumbled on some outdated documentation from for contributing to Dancer2 and which git commands to run. Unfortunately, it took me a while and several git errors to figure out the documentation was long obsolete. I think I was finally able to get it working but there are no policies on contributing that I could find. Are there any? If not, what is the proper protocol for contributing via github?

**Comment by sdondley** [comment]
OK, disregard. Found it here: https://github.com/PerlDancer/Dancer2/blob/master/GitGuide.md

**Comment by racke** [comment]
I suggest that we reference the GitGuide in the Documentation Index of the main README.

**Comment by sdondley** [comment]
OK, sounds like a perfect thing for me to do. I'll give it a shot.

**Comment by cromedome** [comment]
Closing. Thanks!
