### ISSUE TITLE
Documentation on switching environments is unclear and not consistent with plack documentation

### ISSUE THREAD

**Issue by sdondley** [PerlDancer/Dancer2#1411]
I'm looking at the "Configuration" section of the `Dancer2::Manual` here: http://search.cpan.org/~xsawyerx/Dancer2-0.200002/lib/Dancer2/Manual.pod#CONFIGURATION

I was trying to figure out how to switch environments after generating an application with `dancer2 gen -a MyWeb::App` command.

The instructions there say to use the `--environment` switch. However, according to the [plack documentation](http://search.cpan.org/~miyagawa/Plack-1.0044/script/plackup) the actual switch is `--env` or `-E`. Once I figured this out, I was able to change the environment of my app.

Also, the documentation doesn't make clear that the switch is applied to the plackup command. This is obvious to most but not to individuals like myself who are new to Plack and Dancer2 in general.

**Comment by racke** [comment]
Another way is to set the environment variable DANCER_ENVIRONMENT in the shell or in your web server configuration (e.g. with Apache).

**Comment by cromedome** [comment]
Some clarification here would definitely be welcome! Working CLI examples would get you some Valuable Bonus Points too ;-)

Thanks for spotting this!

**Comment by sdondley** [comment]
OK, here is the pull request. Sorry, I'm not sure how to attack these pull requests to a particular issue. The pull request somehow ended up in another thread.

https://github.com/PerlDancer/Dancer2/commit/6c90d6b18e37edc6f09b279980ebad3f2b325f9f

**Comment by sdondley** [comment]
https://github.com/PerlDancer/Dancer2/pull/1408/commits/6c90d6b18e37edc6f09b279980ebad3f2b325f9f

**Comment by cromedome** [comment]
Thanks!
