### ISSUE TITLE
Documentation for template toolkit caching?

### ISSUE THREAD

**Issue by sdondley** [PerlDancer/Dancer2#1412]
I was trying to figure out how to turn on caching for the template toolkit templates. It seems it is as easy as adding at `COMPILE_EXT: '<file_ext>'` property to the config files. Correct me if I'm wrong, but this tip does not exist explicitly in the Dancer2 documentation.

I'd be happy to document this in the official documentation at https://metacpan.org/pod/Dancer2::Template::TemplateToolkit if others think it's appropriate. Let me know, please.

**Comment by racke** [comment]
Yes, please do that. 👍

**Comment by sdondley** [comment]
OK, pull request made: https://github.com/PerlDancer/Dancer2/commit/ab3528d47c44afa7731738b1bdaf03e96d98360a

**Comment by cromedome** [comment]
Merged. Thanks!
