### ISSUE TITLE
New Dancer2 GitHub wiki pages

### ISSUE THREAD

**Issue by sdondley** [PerlDancer/Dancer2#1414]
I've started three pages on Dancer2's GitHub wiki. They mostly serve as stubs for now and have limited content. Feedback and contributions to these pages are appreciated.

[Dancer2 history](https://github.com/PerlDancer/Dancer2/wiki/Dancer2-History) to provide a succint overview of significant events in the Dancer2 project.

[Meet the dancers](https://github.com/PerlDancer/Dancer2/wiki/Meet-the-Dancers) to help put a human face to the talent behind Dancer2.

[Undocumented Dancer2 development tips](https://github.com/PerlDancer/Dancer2/wiki/Undocumented-development-tips-and-tricks) for inclusion of advice that is only tangentially related to Dancer2 development or is not yet documented in the official docs

**Comment by sdondley** [comment]
For the history section, I was trying to figure out when the two Dancer projects were first put on CPAN. I couldn't find a way to determine this.

**Comment by cromedome** [comment]
Cool, thanks!

**Comment by cromedome** [comment]
Would you want to send in a PR that adds these links to the documentation Pod?

**Comment by cromedome** [comment]
Resolved by #1681. Closing.
