### ISSUE TITLE
Code is not enough

### ISSUE THREAD

**Issue by sdondley** [PerlDancer/Dancer2#1415]
I was watching Alexis Sukrieh's presentation on Dancer2 history. His slide entitled "Code is Not Enough" jumped out at me:  [Alexis Sukrieh (sukria) - Dancer, a brief history of code - 30:22](https://youtu.be/TM-HlK4Auk4?t=30m22s)

The essence of the slide is that a project needs promotion and marketing to be successful. It is a sentiment that I have been reflecting on over the last week while exploring Dancer2.

I'm interested to learn more about organized efforts to promote Dancer2. I'd like to pitch in where I can. If there is no current game plan, I'd be interested in helping to draft one. Can someone please point me in the right direction? Who should I talk to?

**Comment by StylusEater** [comment]
@sdondley Outside of the following I'm not sure:

https://github.com/PerlDancer/perldancer-book
https://github.com/PerlDancer/perldancer-website

I suspect it would be infinitely helpful if you were to start creating tutorials through a blog and/or `insert your favorite video site here` to help get the word out on how to use Dancer2 to make neat sites/services. Maybe start creating useful web services for others to use and advertise you built it using Dancer2? Maybe organize a local coding project and meet regularly to hack on a useful site and build it using Dancer2? Maybe @sukria and @xsawyerx would be open to creating a marketing repository to start capturing efforts? 

Hope that helps.

**Comment by sdondley** [comment]
Very cool. I wasn't aware of those repos. Thanks!

I'm far from qualified to be able to start cranking out tutorials, unfortunately. And I've built nothing with D2. I'm just learning.

But I do love what I see so far. I have a deep affection for Perl and I've had a long interest in being able to build a flexible web framework to suit my own needs. D2 seems to be absolutely perfect for this. I've also had a long fascination with free software but never found a project that really excited me.

I am working on a couple of projects but they are probably many months from being functional. I will certainly advertise them when I have something to show. Hopefully they will be good enough to win a little acclaim.

For now, I just want to let the D2 community know I'm willing to help wherever they think I can be used. Put me to work!

**Comment by perldj** [comment]
You can see my tutorial video here which shows how to get started with
Dancer 2.
https://www.youtube.com/watch?v=O7dO3K-krrg

**Comment by sdondley** [comment]
I've been diligently bookmarking and categorizing stuff related to D2. I think I'll start doing the same for tutorials like this and then do a dump of these kinds links somewhere and curate them.

But we will need some public place to put them.

**Comment by sdondley** [comment]
Another idea I had was to create a virtual machine that could be easily downloaded and shared and run inside VirtualBox. It would come preconfigured with a running plack server, database, and example apps. That way, the developer wouldn't have to be bothered taking the time to get all that set up. They could just dive in and start playing with live D2 examples right away.

**Comment by cromedome** [comment]
You can feel fee to post items here for inclusion in the website at a later time, or feel free to clone https://github.com/PerlDancer/perldancer-website and send us PRs for that. 

Thanks!

**Comment by StylusEater** [comment]
I'm happy to provide hosting if needed.

**Comment by racke** [comment]
Another thing we could do is organizing another Perl Dancer conference in 2018 (see https://www.perl.dance for the last one). Please contact me by email if you are interested in that.

**Comment by StylusEater** [comment]
@racke sounds like fun to me.

**Comment by StylusEater** [comment]
This seems to have lost momentum...am I wrong?

**Comment by racke** [comment]
@StylusEater you are right. Closing the issue now.
