### ISSUE TITLE
Guidance on writing a plugin for managing included javascripts on a page

### ISSUE THREAD

**Issue by sdondley** [PerlDancer/Dancer2#1416]
I'm thinking of writing a plugin to help me learn how to do write one. The first plugin I'm thinking of writing would allow developers to easily inject and remove `<script>` tags into a page to include javascript libraries. I'm thinking it would work something like this:

1) The plugin would detect if the library was external to the site. If it is, it would download the script to the local machine.

2) The plugin would write the necessary code to fall back to using the local copy of the code if external js is unavailable.

3) The developer could easily turn on and off libraries on specific pages. Some libraries could default to "always on" and would have to be removed by the developer while others would default to "always off" and have to be specifically added by the developer. 

4) The developer could indicate which javascript libraries could have dependencies. So if the developer includes jQuery Mobile, jQuery would automatically be loaded.

5) The developer could indicate where in the code it should go: head, body_top, body_bottom

5) The developer would configure these settings in the config file:

```
plugins:
  JavaScriptLoader:
    external_code: 'http://cdn.com/javascript'
    name: jQuery_mobile
    default: on
    depends_on: jQuery
    location: head
```

I think it would be straightforward, but I'm not sure of the best way to getting the inject the code into the page. I guess it would be up to the app developer to provide the appropriate variables in their template and then the plugin would have to somehow supply the html for those variables. But I'm not sure how that can best be achieved. Are there plugins I could look to as an example to see how this might be achieved?

Thanks.

**Comment by StylusEaterCTP** [comment]
Interesting idea but as a developer, I would be concerned about the security implications. I don't think I would use this in a production setting unless, possibly, I were referencing internal repositories. Even then I'd want some sort of verification mechanism (maybe a checksum to go along with it? to make sure no one changed a file on where I'm pulling it from?). 

This might be of use [OWASP - XSS](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet)

**Comment by sdondley** [comment]
It is common practice to load external libraries through `<script>` tags to inject them into the site (from reputable sources, of course). If the developer preferred to load the libraries locally off the server, it would be easy enough make that an option. So instead of using `extenal_code` they could load the js right from the server with something like `local_file: /js/jQuery.js`.

**Comment by sdondley** [comment]
Some kind of checksum would be cool, though, I think. Would help give the developer some piece of mind. Not sure how much that might slow things down, though.

**Comment by sdondley** [comment]
Well, that was pretty painless. So here is an early prototype:

```
package JSManager 0.01;

use strict;
use warnings;

use Dancer2::Plugin;

sub BUILD {
  my $s = shift;

  $s->app->add_hook( Dancer2::Core::Hook->new (
    name => 'before_template',
    code => sub {
      my $tokens = shift;
      $tokens->{js} = $s->_inject_js;
    }
  ));
}

sub inject_js {
  my $s = shift;
  my $libraries = $s->config;
  my $out = '';
  foreach my $library( keys $libraries ) {
    $out .= '<script src="' . $libraries->{$library}{url} . '"></script>';
  }
  return $out;
}
```

The config file looks like this:

```
plugins:
  JSManager:
    jquery:
      url: 'https://code.jquery.com/jquery-1.11.1.min.js'
```

And you'd just put `[% js %]` in `<head></head>`.

**Comment by sdondley** [comment]
I did a little more work on this module so that a local fallback script is used if CDN is down. I think it's ready to be committed to CPAN but I'd love to get some input on this if anyone is interested. I'd also like hear feedback from web development pros on why you think this module is or is not useful so I can learn.

https://github.com/sdondley/Dancer2-Plugin-JSManager/tree/master/lib/Dancer2/Plugin

Please see the Developer Notes in the Readme on GitHub for other ideas on where I'm thinking of taking this in the future.

Thanks!

**Comment by sdondley** [comment]
Just made it public. So link to repo will work now.
