### ISSUE TITLE
Doc bug: Configuring serializers 

### ISSUE THREAD

**Issue by lembark** [PerlDancer/Dancer2#1417]
Common enough case, especially during prototyping: Most content going out is JSON, with a few items returning text. using JSON as a global serializer works for all but non-ref scalars, which given an error indicating that I should set "allow_nonref" to true.

Catch: Nothing in the JSON serializer doc tells me how to set this in config or code.

I'd suggest adding one snippet to the JSON doc:

```
=head2 Configuring the JSON Serializer using "set engines"

The JSON serializer optoins can be configured via "set engines". The most
common settings are:

=over 4

=item   allow_nonref

Ignore non-ref scalars returned from handlers. With this set the "Hello, World!"
handler returning a string will be dealt with properly.

=back

Set engines should be called prior to setting JSON as the serializer:

 set engines =>
 {
     serializer =>
     {
         JSON =>
         {
            allow_nonref => 1
         },
     }
 };

 set serializer      => 'JSON';
 set content_type    => 'application/json';

=head2 Returning non-JSON data.

Handlers can return non-JSON via "send_as", which overrides the default serializer:

 get '/' =>
 sub
 {
     send_as html =>
     q{Welcome to the root of all evil...<br>step into my office.}
 };

Any other non-JSON returned format supported by 'send_as' can be used.
```

**Comment by deirdreemoran** [comment]
I'm new to OSS contributions, so this is my first time attempting to help.  I updated the JSON.pm documentation and pushed the changes mentioned above, so hopefully I did that correctly.  Please let me know if not, thanks!

**Comment by deirdreemoran** [comment]
I'm a beginner and would like to help update your documentation.  When I clone the repository, create a new branch, make changes to JSON.pm, and then try to push the changes back, I'm getting an access denied message with error 403.  Any guidance on what I should actually be doing would be much appreciated, thanks.

**Comment by cromedome** [comment]
Hi, and thank you for wanting to help!

Only the core developers can directly push changes to the Dancer2 repo. You will need to first fork the repo, then clone your fork to your development machine. Make your changes, push them, and then you can create a Pull Request. We evaluate the PRs, make suggestions if needed, and can merge them afterwards. 

I hope this helps! If you need some more details, please let me know. Thanks again, looking forward to your PR!
