### ISSUE TITLE
send_as supports "html" but not plain.

### ISSUE THREAD

**Issue by lembark** [PerlDancer/Dancer2#1418]
From what I can tell, send_as does not support text/plain, which is usefuil during prototyping the site. 

example would be "send_as plain => 'example pass1';".

**Comment by sdondley** [comment]
I'll take a stab at it. Just need a little guidance on the proper protocol for submitting this. So my local repo is currently on branch pr/docs. Do I start a brand new branch for this one bug?

**Comment by sdondley** [comment]
Maybe [Dancer2::Plugin::SendAs](http://search.cpan.org/perldoc?Dancer2%3A%3APlugin%3A%3ASendAs) is the way to go instead of a core change? Please advise.

**Comment by sdondley** [comment]
Disregard last, I now see that module has been marked as DEPRECATED.

**Comment by SysPete** [comment]
You can supply content_type to `send_as html`:
```
get '/' => sub {
    send_as html => "some plain text",
      { content_type => 'text/plain' };
};
```

**Comment by racke** [comment]
A shortcut for that would be nice, though.

**Comment by SysPete** [comment]
@racke I agree, and it would be a fairly small change.

**Comment by racke** [comment]
@sdondley: you need a separate branch for each PR.

**Comment by sdondley** [comment]
Ok. I’ve got a patch already written. I’m just trying to figure out how to
get the tests written for it now (yes, I know best practice is to write
them first).

**Comment by racke** [comment]
Should be relative straightforward to add a test to `t/dsl/send_as.t`

**Comment by sdondley** [comment]
Yeah. I figured that part out. Just don’t know how to run the tests. I’ve
done only a bit of test driven development on my own code. My experience
coordinating with others on a real suite of test tools is non-existent so
the process is a bit mysterious to me right now. I have to read some man
pages to get a clear idea. Haven’t done that yet. I’ll let you know if I
run into problems figuring it out.

**Comment by racke** [comment]
Single test:

`prove -vl t/dsl/send_as.t `

**Comment by sdondley** [comment]
Ok. Easy enough.

Earlier this year I got obsessive about minimizing keystrokes with vim and
patched together a crazy quilt of scripts with vim built on top of other
people’s scripts that automated my testing and wrapped all the basic stuff
like prove into some unseen script. In the process I lost the trees in the
forest.

**Comment by sdondley** [comment]
OK, I'm going to ask a dumb question, I'm sure.

I should be patching the `send_as` subroutine in `Core/App.pm` right?

I must be doing something completely stupid because when I comment out the entire `send_as` subroutine, the existing tests in `send_as.t` still pass.

**Comment by sdondley** [comment]
Ah, ok, I was running the test while I was in the `t/dsl` directory. When I moved up to the root of the D2 repo and ran the test, the tests failed as expected.

But now my question is, why is that?

**Comment by racke** [comment]
`prove -vl t/dsl/send_as.t`

The -l flag tells it to include **lib** directory, whereas when you run it in the directory the installed version of Dancer is used.

**Comment by sdondley** [comment]
OK, this patch is mixed in with my earlier doc patches despite me moving to a different branch. Did I screw something up or is that the way it's supposed to work?

**Comment by racke** [comment]
How did you move to this branch? You need to branch from master branch, not from your current branch.

**Comment by sdondley** [comment]
Yeah, that was my mistake. I made the assumption that starting a new branch would start from the master. It's been a few years since I first learned git and I've used it in a professional environment so it's a little fuzzy to me. Here's what I did:

From my pr/doc branch, I did:

`git checkout -b pr/send_as_plain`
`git add lib/Dancer2/Core/App.pm t/dsl/send_as.t`
`git commit -m 'commit message'`

**Comment by cromedome** [comment]
Done! Closing. Thanks for tackling this, @sdondley !
