### ISSUE TITLE
Changing layout_dir doesn't work

### ISSUE THREAD

**Issue by kal247** [PerlDancer/Dancer2#1427]
Changing layout_dir with `set layout_dir` doesn't work for me (I don't use any config file). I found a workaround by adding following code at Core/App.pm line 269 : 

`$engine_attrs->{layout_dir} ||= $config->{layout_dir} || path( $self->location, 'layouts' );`

I'm not sure if it's really a bug or not.

**Comment by sdondley** [comment]
Just a sanity check. The `layout_dir` is inside the `views/` dir. So if you have `layout_dir` set to `layouts`, the path to the layouts is `views/layouts`.

**Comment by kal247** [comment]
Absolutely. And if I rename the directory as "layouts_" and `set layout_dir => 'layouts_'`, I get this exception :

Route exception: Failed to render template: file error - layouts/main.tt: not found

**Comment by sdondley** [comment]
Seems like a bug to me. There is nothing in the manual to indicate this setting isn't overridable with `set`.

**Comment by veryrusty** [comment]
It's a bug; the `layout_dir` attribute is read-only in the template engine role. It'll also need a trigger to ensure changes propagate after the template engine has been instantiated. Expect a PR shortly :)

**Comment by cromedome** [comment]
Merged #1458. Thanks @veryrusty!
