### ISSUE TITLE
Documentation links not working

### ISSUE THREAD

**Issue by ambs** [PerlDancer/Dancer2#1439]
The result of converting the POD results on broken links. Check for example the -request- link here: https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Manual.pod#Default-Template-Variables

**Comment by jamesheesbeen** [comment]
I can give this a crack. I assume I'd just send a pull request when I'm done? (I'm a complete newbie!)

**Comment by cromedome** [comment]
Yes please. A PR will be just fine. 

Thanks!
Jason

**Comment by jamesheesbeen** [comment]
Great! I've just sent one.

https://github.com/PerlDancer/Dancer2/pull/1441

**Comment by cromedome** [comment]
Thank you! Closing.
