### ISSUE TITLE
Dancer2 0.205002 install fails on Failed test at t/cookie.t 

### ISSUE THREAD

**Issue by mark-00** [PerlDancer/Dancer2#1440]
I tried installing Dancer2 0.205002.It failed with the error.

t/context-in-before.t .................................. ok
   Failed test at t/cookie.t line 188.
     Structures begin differing at:
          $got->[0] = 'ARRAY(0x7f7ff2b6ad80)'
     $expected->[0] = 'bar'

   Failed test at t/cookie.t line 188.
     Structures begin differing at:
          $got->[0] = 'ARRAY(0x7f7ff2ba6978)'
     $expected->[0] = 'bar'
 Looks like you failed 2 tests of 118.
t/cookie.t ............................................. 

looks like it is related to  https://github.com/PerlDancer/Dancer2/pull/1438. 
--> Working on HTTP::XSCookies
Fetching http://www.cpan.org/authors/id/G/GO/GONZUS/HTTP-XSCookies-0.000021.tar.gz ... OK
Configuring HTTP-XSCookies-0.000021 ... OK
Building and testing HTTP-XSCookies-0.000021 ... OK
Successfully installed HTTP-XSCookies-0.000021
Building and testing Dancer2-0.205002 ... FAIL
! Installing Dancer2 failed. See /root/.cpanm/work/1521802526.118/build.log for details. Retry with --force to force install it.
57 distributions installed

It failed on both Redhat and ubuntu. On http://www.cpantesters.org/distro/D/Dancer2.html#Dancer2-0.205002 I see a number reports with the same error message. 

Is there a work around for this so I can install Dancer2

**Comment by jahagirdar** [comment]
I am facing the same issue with the following configuration:

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)


Linux  3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cc-skelos** [comment]
I see the same problem on OS X and Ubuntu 16.04.4 when I use perl-5.26.1. I've not tried any other version. I think I'll run up a new virtual machine and try an older release of perl. I will also look at the code, but since this is the first time I've tried to use Dancer2 to learn about it, I'm not sure if I'll be able to tell if the test is faulty or if it is validly failing.

**Comment by cc-skelos** [comment]
Ubuntu 16.04.4 with its "system" perl version 5.22.1 has the same problem. I've looked at the test code but don't understand it, not yet knowing how cookies and Dancer2 work.
The problem test source is this:
    my $r = Dancer2::Core::Request->new( env => { HTTP_COOKIE => 'foo=bar&baz' } );

    is_deeply [ $r->cookies->{foo}->value ], [qw/bar baz/];

Apparently "bar" is expected as the result but an array reference is found instead. I suspect this isn't  a hard problem for someone  who knows the code. The error output from the test matches (other probably than memory addresses) that in the original bug report.

**Comment by veryrusty** [comment]
Hey all.  There were upstream changes in HTTP::XSCookies that cause breakage in the cookie tests. See issue #1435 for the full discussion. The core has been updated to work with later releases of HTTP::XSCookies. The next release which includes a fix is due first week of April, given the current availability of core members.

Alternatively, downgrade HTTP::XSCookies to v0.000014.

**Comment by cc-skelos** [comment]
Thanks, veryrusty. A third choice is putting the change from https://github.com/PerlDancer/Dancer2/pull/1438/files into the current code, which allows the test suite to pass. That'll do for me; I'm in learning mode with Dancer2. I look forward to the next release, of course!

**Comment by mark-00** [comment]
installing the older version of the XSCookies did the trick. 
Thanks that was  what I needed

cpanm HTTP::XSCookies@0.000014
cpanm Dancer2

**Comment by jkeenan** [comment]
Per discussion today on [blogs.perl.org](http://blogs.perl.org/users/jason_a_crome/2018/04/dancer2-0206000-01-trial-version-released.html), today I attempted to install the [trial version of the next Dancer2 release](http://search.cpan.org/CPAN/authors/id/C/CR/CROMEDOME/Dancer2-0.206000_01.tar.gz) against [Perl 5 blead](v5.27.10-97-g28e487a0fb) on FreeBSD-11.0.  All tests PASSed and the module installed successfully.

It would be good if we could get an official release prior to April 20.  That would enable us to test Dancer2 against perl-5.27.11, the last expected monthly development release prior to the release of perl-5.28.0.

Thank you very much.
Jim Keenan

**Comment by cromedome** [comment]
@jkeenan, I will attempt to get an official release out the door by then. We are trying to time a D1 release alongside a D2 release this time. Hopefully we can make both by then.

Thank you for letting me know what your roadmap looks like.

**Comment by cromedome** [comment]
I haven't heard of this being an issue since releasing Dancer2 0.206000. I will reopen if necessary.
