### ISSUE TITLE
redirect '?foo=bar+%26+baz' does wrong thing

### ISSUE THREAD

**Issue by JRaspass** [PerlDancer/Dancer2#1460]
When one feeds a relative URL to `redirect` Dancer2 attempts to make it an absolute URL. It however has a bug in that the URL is URI decoded first, causing `?foo=bar+%26+baz` to become `...?foo=bar+&+baz` which obviously means something VERY different.

It does this because, as the [comment in the code](https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Core/App.pm#L1272) points out, RFC 2616 requires the URL in a Location header to be absolute. However [RFC 2616 is dead](https://www.mnot.net/blog/2014/06/07/rfc2616_is_dead) and this rule has been relaxed in [RFC 7231](https://tools.ietf.org/html/rfc7231#section-7.1.2), some even go as far as to suggest that that [was a bug in RFC 2616](https://stackoverflow.com/questions/8250259/is-a-302-redirect-to-relative-url-valid-or-invalid).

I therefore suggest we remove the offending code and add a test case which will simplify the code and make it more correct :-P

I am of course more than happy to write the commit, I just wanted to get some consensus first, thoughts @xsawyerx and co? Ran into this bug at $day_job.

**Comment by veryrusty** [comment]
It's been 4 years since RFC2616 was superseded. Dancer2 should adhere to the current HTTP spec ( RFC7231+).

@JRaspass you are more than welcome to clean up the existing redirect logic :)

**Comment by JRaspass** [comment]
@veryrusty PR filed :-)

**Comment by ehuelsmann** [comment]
Ran into this issue yesterday. The point isn't so much that Dancer2 should respect RFC 7231 or not, but that the rewrite logic should stick to making the URL absolute; not rewriting it in any other way (such as decoding the query string.
