### ISSUE TITLE
existence of sessions directory is only checked at start-up?

### ISSUE THREAD

**Issue by szabgab** [PerlDancer/Dancer2#1462]
This app.psgi:

```
use Dancer2;
set session => 'YAML';

get '/' => sub {
    my $count = session('counter') // 0;
    return 1;
};
```
I run it as `plackup app.psgi`

```
curl http://localhost:5000
```
This creates the 'sessions' subdirectory without any content.

If I had a 'sessions' subdirectory when I start the application and I remove it and only then I access the page:

```
rm -rf sessions
curl http://localhost:5000
```

Then the directory is not created.

**Comment by simbabque** [comment]
I've got a PR with tests for this. Will submit in a few days.

**Comment by cromedome** [comment]
Closing. See #1471 for details.
