### ISSUE TITLE
Documentation for setting the running environment incorrect.

### ISSUE THREAD

**Issue by whosgonna** [PerlDancer/Dancer2#1463]
[Dancer2::Config](https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Config.pod#environment-(string)) contains the following:

> The running environment can be set with:
> `set environment => "production";`
> Note that this variable is also used as a default value if other values are not defined.

Changing the `environment` value in this way only changes the string, it does not load the corresponding environment configuration, so I don't see it's value.  It's also not clear what 'other values' means here in the last line, either.

I would recommend that these three lines be removed from the POD.

**Comment by cromedome** [comment]
Merged your PR: 2d8612977e63a37d0bc8991d38f0125d8ec94249. Thanks!
