### ISSUE TITLE
Distinguish between user and server errors on deserialization fail

### ISSUE THREAD

**Issue by seav** [PerlDancer/Dancer2#1482]
Currently, if Dancer2 fails to deserialize a request body, it throws an error and returns an HTTP 500 error response. I think it would be better if we can distinguish failure due to user input (e.g., `Content-Type: application/json` but the JSON is invalid) for which we should return a HTTP 4xx error (most likely 400 Bad Request), and due to internal server errors (maybe a Perl module is missing) for which HTTP 500 is the correct response.

I am not sure how this issue is affected by #1056.

**Comment by veryrusty** [comment]
Some of my $work colleagues have bumped into this too. PR soon :)

**Comment by veryrusty** [comment]
Thanks again for reporting the issue @seav.

The work in #1509 has been merged into master in preparation for a new release (April 2020); deserialization failure will throw a 400 Bad Request.  There's an example in the test suite (see `t/deserialize.t`) if you want to customise the error on serialization fail.
