### ISSUE TITLE
Dancer2 didn't install on Windows 32 for me, issue with Plack dependency

### ISSUE THREAD

**Issue by sdondley** [PerlDancer/Dancer2#1483]
This is more of a heads up to Dancer2 distro maintainers in case it isn't on the radar. I was doing some testing on an old Win 8 virtual machine. Ran into issues getting Plack installed. Issue was with a Plack dependency, [Test::Time](https://metacpan.org/pod/Test::Time).

See https://github.com/cho45/Test-Time/issues

From what I can gather, bug was introduced into the module within the last year. Not sure what the best approach is for making sure new Dancer installs don't encounter this problem.

**Comment by cromedome** [comment]
Closing as the original `Test::Time` issue has been resolved.
