### ISSUE TITLE
Dancer2::Config documentation makes reference to non-existent module

### ISSUE THREAD

**Issue by sdondley** [PerlDancer/Dancer2#1492]
https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Config.pod#Logging,-debugging-and-error-handling mentions a `Dancer2::Config::Object` module but there is no such animal.

**Comment by racke** [comment]
AFAICT, this is a relict from Dancer 1. Couldn't find strict_config other than in this POD.

**Comment by racke** [comment]
I don't see that happening in the near future ... so I suggest to remove the invalid reference. It can be restored easily if needed.
