### ISSUE TITLE
Optional parameters and trailing slashes

### ISSUE THREAD

**Issue by jjatria** [PerlDancer/Dancer2#1497]
I was trying to implement a route that would display the results of a questionnaire under eg. `/results`. Since the questionnaire will be versioned, the results will only show for the latest version. And I wanted to make it so that previous versions were still visible under eg. `/results/foo` for version `foo`, etc.

I looked at the documentation and read about optional route parameters, so my first attempt was something like

``` perl
get '/results/:version?` => sub {
    my $version = route_parameters->get('version') // get_latest_version();
    my $results = get_results_for_version($version);
    template 'results', { data => $results };
};
```

However, this didn't work. I was surprised by this, and it took me a while to figure out that it was because while the _parameter_ was still optional, the (sometimes) _trailing slash_ wasn't.

It looks like there's been plenty of discussion here regarding the meaning of trailing slashes, so I don't really want to get into that. My question is: is there a way to specify that the optional parameter should carry with it the trailing slash? Or does the route without the slash need to be handled explicitly?

**Comment by veryrusty** [comment]
Use two routes (which makes it clear as to what's going on):

```
get '/results' => sub {
  my $version = get_latest_version();
  return _results_for_version($version);
};

get '/results/:version' => sub {
    my $version = route_parameters->get('version');
    return _results_for_version($version);
};

sub _results_for_version {
    my $version = shift;
    my $results = get_results_for_version($version);
    template 'results', { data => $results };    
};
```

**Comment by jjatria** [comment]
Thanks~
