### ISSUE TITLE
Invalid body causes a 500

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#1507]
When making a call with an invalid body, `HTTP::Body` croaks, which triggers a 400.

I think we should instead return a 400 for an invalid request.

Objections?

**Comment by cromedome** [comment]
No objection! :+1:

**Comment by ice-lenor** [comment]
The issue is also present in Dancer v1
https://github.com/PerlDancer/Dancer/issues/1167

**Comment by xsawyerx** [comment]
Reference tests for this: #1508

**Comment by cromedome** [comment]
Resolved by #1509.
