### ISSUE TITLE
log config setting seem ineffectual

### ISSUE THREAD

**Issue by alanmead** [PerlDancer/Dancer2#1511]
I'd prefer to just see errors right now, but I seem to see the same output on the console when developing (with plackup) regardless of using 'core' or 'error' (or 'info' etc.):

    logger: "console"
    log: "error"
    #log: "core"

I think the console output is identical and unaffected by these settings. Do I misunderstand what these settings do or am I using them wrong? Seems like a bug, but 99% of the time it's really my error but I don't see how in this case.

**Comment by cromedome** [comment]
Just wondering, what configuration file are you setting these in? If you are setting this in `config.yml`, be aware that anything in your `environments/` directory can override settings in `config.yml`. `config.yml` settings are intended to be universal, and anything in environments is specific to the environment you are running your app in (and therefore take precedence over similarly named settings in `config.yml`).

**Comment by alanmead** [comment]
That was it. `/environments/development.yaml` was set to 'core' and when I change it, I see what I expected. Thanks!
