### ISSUE TITLE
Documentation on configuring the adress to listen on: "server" does not seem to work, but "host" does.

### ISSUE THREAD

**Issue by m7a** [PerlDancer/Dancer2#1521]
version 0.207000 (if it matters)

I just tried to change the default address for the server to listen on to `127.0.0.1` for my local use case. After reading the documentation, I expected that to work as follows:

```
set server => "127.0.0.1";
```

This did not seem to have any effect. As an intermediate solution, I used the environment variable `DANCER_SERVER` which worked as expected. Finally, I checked the source code and got my original goal to work as follows:

```
set host => "127.0.0.1";
```

I believe this is a bug in the documentation.
Would it make sense for https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Config.pod to refer to `host` instead of `server`?

Thanks in advance
m7a

**Comment by cromedome** [comment]
Yes, it would make sense :) Happy to take a PR for it.

Thank you!

**Comment by cromedome** [comment]
Resolved by #1534. Thanks!
