### ISSUE TITLE
Any supported way to get the app (_not_ psgi) instance?

### ISSUE THREAD

**Issue by cxw42** [PerlDancer/Dancer2#1531]
## Motivating example

While porting Dancer::Plugin::MobileDevice to D2, I ran across an oddity.  The tests reach into the app and tweak its layout with `set layout => 'main';` ([here](https://github.com/cxw42/Dancer2-Plugin-MobileDevice/blob/dd4a020454f8bc6e3c5c0e1607084154b94ab939/t/03-dynamic-layout.t#L34-L35)).  (I'm not sure why, but this is just an example.)  I wanted to find a way to replicate that in Dancer2.

## What I did

Since `to_app` returns a PSGI application (i.e., a coderef), and not something I can call `setting()` on, I exfiltrated the app instance:

    my $app;
    { package TestApp; use Dancer2; $app = app; ... }

([here](https://github.com/cxw42/Dancer2-Plugin-MobileDevice/blob/774b641b1dc4f47647152d92fd9dfa46438ff102/t/03-dynamic-layout.t#L13-L19)), so that later I could say `$app->setting(layout => 'main');` ([here](https://github.com/cxw42/Dancer2-Plugin-MobileDevice/blob/774b641b1dc4f47647152d92fd9dfa46438ff102/t/03-dynamic-layout.t#L42)).

Having double-checked, I can also get the app instance by doing what `Dancer2::import()` does:

    my ($app) = grep { $_->name eq 'TestApp' } @{Dancer2->runner->apps};

## Question

Is there an official or supported way to access the app instance from outside the app's package?  E.g., it would be nice if I could do `TestApp->app`, but `app` only exists on object instances (Dancer2::Core::Role::DSL `has app`).

**Edit** See https://github.com/cxw42/Dancer2-Plugin-MobileDevice/commit/90413c376a3112e3c38cd884a38a8e4e83aae1d7 for things I tried while preparing this issue.

Thanks for considering this question!

**Comment by xsawyerx** [comment]
`Dancer2->runner->apps()` is the way to retrieve the entire set of registered Dancer2 applications. If you already have the caller, why not call `->app()` or the `app` keyword? They both would return the current app.

**Comment by cromedome** [comment]
Seems resolved. Will reopen if not. Thanks for the question and answer!
