### ISSUE TITLE
Plugin: $self->app->add_hook or $self->dsl->hook?

### ISSUE THREAD

**Issue by cxw42** [PerlDancer/Dancer2#1532]
The docs for Dancer2::Plugin show using `$self->app->add_hook` to add a hook:

https://github.com/PerlDancer/Dancer2/blob/84665e58df52eafc85151652b95017ddab1cfe20/lib/Dancer2/Plugin.pm#L650-L656

However, I just learned from the [2016 Advent calendar](http://advent.perldancer.org/2016/22) that you can use DSL via `$self->dsl->hook`.  I tried it with good success ([here](https://github.com/cxw42/Dancer2-Plugin-MobileDevice/commit/8b08e06771af16a853d90f9760227cec47a820be#diff-fc8a7b732d4c35b6f508f85d06d34fb9L31)).

Is there any underlying difference, in a Dancer2 plugin, between `$self->app->add_hook` and `$self->dsl->hook`?  Any reason to prefer one over the other?  If there is no difference or reason, any objection to a PR updating the Dancer2::Plugin docs to feature the latter, more concise form?

Thanks!

**Comment by SysPete** [comment]
@cxw42 there is no difference since DSL's `hook` results in this being called under the hood:
```
    $self->app->add_hook(
        Dancer2::Core::Hook->new( name => $name, code => $code ) );
```
I you feel like create a PR then it will get my approval at least.

**Comment by cromedome** [comment]
Closing. Would still entertain a PR should @cxw42 feel motivated :)
