### ISSUE TITLE
Adding a Mime::Type for files who get served from public/

### ISSUE THREAD

**Issue by incognico** [PerlDancer/Dancer2#1546]
I've stumbled upon the problem that a `*.mjs` file in `public/` didn't have the correct mime type assigned.

Trying to add it via `mime->add_type( mjs => 'text/javascript' );` didn't work, it seems that does not affects files who are served from `public/`.

I've worked around it by renaming it is `*.js` but it would be nice to be able to manipulate the mime types for files in `public/`. Or at least know how to do that, maybe I tried it the wrong way.

**Comment by racke** [comment]
First of all `*.mjs` is not supported by [MIME::Types](https://metacpan.org/pod/distribution/MIME-Types/lib/MIME/Types.pod) which Dancer2 is using. 

Second `mime->add_type( mjs => 'application/javascript')` should work in general. Where did you put this call? Maybe it needs to go into a before hook?

**Comment by incognico** [comment]
> First of all `*.mjs` is not supported by [MIME::Types](https://metacpan.org/pod/distribution/MIME-Types/lib/MIME/Types.pod) which Dancer2 is using.
Well, that's why I try to add it.

> Second `mime->add_type( mjs => 'application/javascript')` should work in general. Where did you put this call? Maybe it needs to go into a before hook?
I am pretty sure I have tried many things including before hook, nothing worked.

**Comment by veryrusty** [comment]
@incognico apologies for taking soo long to look at this. You are correct, the static handler isn't handling mime types correctly. PR to fix shortly.

**Comment by cromedome** [comment]
Resolved in #1561. Closing.
