### ISSUE TITLE
samesite issue

### ISSUE THREAD

**Issue by jdmartinsF** [PerlDancer/Dancer2#1547]
Hi
Using Dancer2-0.205002 or Dancer2-0.300003 and using Firefox 76.0.1 I'm receiving messages like this in browser console:
"Cookie “dancer.session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies"
Is this something dangerous, or can cause problems? 
Any way to avoid it ??
Thanks for your attention.
JMartins

**Comment by veryrusty** [comment]
@jdmartinsF Thanks for asking about configuring session cookies' `SameSite` attribute.

It's not currently possible. Added PR#1548 to assist with that.  Happy dancing!

**Comment by cromedome** [comment]
Resolved by #1548.
