### ISSUE TITLE
reload changes on directory in windows 10

### ISSUE THREAD

**Issue by free4cliff** [PerlDancer/Dancer2#1549]
I have found a issue on windows 10 reloading files on changes,
after some investigation, I find adding a line of code can solve the problem. I think my solution is not very good and you may have better solution, so, just for your ref.

my perl: strawberry-perl-5.30.2.1-64bit-portable

package Plack::Loader::Restarter;

...

sub _fork_and_start {
    my($self, $server) = @_;

    delete $self->{pid}; # re-init in case it's a restart

    my $pid = fork;
    die "Can't fork: $!" unless defined $pid;

    if ($pid == 0) { # child
        $SIG{'TERM'} = sub { exit; };   # I added this line for solving problems
        return $server->run($self->{builder}->());
    } else {
        $self->{pid} = $pid;
    }
}

...

**Comment by cromedome** [comment]
Hi there!

While we really appreciate you taking the time to find and fix this, it needs to get reported to the Plack project. We build on top of Plack, but are not responsible for it, nor do we maintain it. You can [find their repository here](https://github.com/plack/Plack).

Thanks again, and good luck!
