### ISSUE TITLE
JSON configuration loads as JSON::PP::Boolean throwing errors.

### ISSUE THREAD

**Issue by EvanCarroll** [PerlDancer/Dancer2#1553]
When my config file has 

    show_error: true

I get the following,

```
Reference bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' ) did not pass type constraint "Bool" (in $args->{"show_errors"}) at /usr/local/share/perl5/site_perl/Dancer2/Core/App.pm line 1648
    Reference bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' ) did not pass type constraint "Bool" (in $args->{"show_errors"})
    "Bool" is defined as: (!ref $_ and (!defined $_ or $_ eq q() or $_ eq '0' or $_ eq '1'))
```

However, when it's `1` everything works as expected.

**Comment by SysPete** [comment]
@EvanCarroll what version of Dancer2 are you using? Testing locally with v0.300004 I can use bools n YAML config without any problems. Perhaps you could share a full app with us that demonstrates this problem?

**Comment by cromedome** [comment]
I am hesitant to call this a bug until @EvanCarroll answers @SysPete's question. Pinging @EvanCarroll :)

**Comment by EvanCarroll** [comment]
Not sure and I no longer have any information on the above. If it can't be replicated I'm cool with closing it until someone else has more information.
