### ISSUE TITLE
redirect disregards path to app

### ISSUE THREAD

**Issue by nfg** [PerlDancer/Dancer2#1564]
Hey!

The `redirect` function has stopped respecting the path leading to the Dancer2 app. If my PSGI looks something like

```perl
use strict;
use warnings;
use lib qw<lib>;

use Plack::Builder;

use MainApp;
use SubApp;

builder {
    mount '/' => MainApp->to_app();
    mount '/subapp' => SubApp->to_app();
};
```

Then `redirect "/page"` in MainApp works fine, but `redirect "/page"` in SubApp goes to `/page` instead of `/subapp/page`.

This changed in #1461 . I can fix this on my end by finding everywhere I call `redirect` and calling `uri_for` first, but it's unexpected behaviour.

Cheers!

**Comment by cromedome** [comment]
Resolved by #1565. Thanks for reporting!
