### ISSUE TITLE
CI using GitHub Actions

### ISSUE THREAD

**Issue by szabgab** [PerlDancer/Dancer2#1571]
Plan to have the following steps

* Run the tests on Linux using the latest version of Perl and build the tar.gz file.
* On Linux/Windows/OSX try to install the tag.gz we just built.
* On Linux install the .tar.gz and then install various downstream packages to notice if the current change breaks any of them to be able to notify them early.

**Comment by atoomic** [comment]
here is one flavor of GitHub CI I'm using 
https://github.com/atoomic/Template2/blob/master/.github/workflows/testsuite.yml

note that this is using pre-set containers with common test distro

**Comment by cromedome** [comment]
Resolved by #1573. Thanks!
