### ISSUE TITLE
pod for Dancer2::Core::Hook mentions "apps" property that does not seem to exist

### ISSUE THREAD

**Issue by clemep-sios** [PerlDancer/Dancer2#1574]
Quoting `Dancer2/Core/Hook.pm`:

```
=head2 register_hook ($hook_name, [$properties], $code)

    hook 'before', {apps => ['main']}, sub {...};

    hook 'before' => sub {...};

Attaches a hook at some point, with a possible list of properties.

Currently supported properties:

=over 4

=item apps

    an array reference containing apps name

=back
```

The apps property (or support for any properties being passed) does not seem to exist, the best I can tell.

Would a PR to update the POD in `Dancer2::Core::Hook` be welcomed?

**Comment by racke** [comment]
That is very much possible, as this part of the POD exists since Dancer2 was started. A PR would be certainly welcome.

**Comment by clemep-sios** [comment]
Here's the PR:
https://github.com/PerlDancer/Dancer2/pull/1597

**Comment by cromedome** [comment]
Resolved. Thanks!
