### ISSUE TITLE
.dancer file not documented

### ISSUE THREAD

**Issue by LorenzoTa** [PerlDancer/Dancer2#1580]
Hello folks,
at perlmonks I saw a question about the undocumented .dancer file. In brief:

1. it is really used? I read "It might help move away from the bin/lib directory checks."
2. why dont name it .dancer2 ?
3. anyway it needs to be documented

I found the above quote at https://www.endpoint.com/blog/2015/10/28/perl-dancer-conference-2015-report
On teh repository there two issues which refere themself:
https://github.com/PerlDancer/Dancer2/issues/1032 and https://github.com/PerlDancer/Dancer2/pull/1043

The perlmonks post is: https://perlmonks.org/?node_id=11127292 and I can update it if you want.

thanks for looking

**Comment by 1nickt** [comment]
@LorenzoTa  Work is under way to use the `.dancer` file to identify the root dir of the app and remove the need for FindBin etc.

**Comment by LorenzoTa** [comment]
hello, it get documented? I still dont find it in the documentation.. perhaps 'cause of my poor search fu

**Comment by xsawyerx** [comment]
Indeed, this is a mistake.

@cromedome and I spoke about refreshing the [rewritten documentation](https://github.com/PerlDancer/Dancer2/pull/1069) and merging it. I've added this as an item to the list I maintain on what to add to that documentation.

I hope to review this documentation before the end of the week. If you have a suggestion on how to phrase this, please do share. :)

**Comment by LorenzoTa** [comment]
thanks for looking xsayerx,

_"If you have a suggestion on how to phrase this, please do share. :)"_

i really have no idea of the matter, just the will to see this great software well documented, and a perl lover :)

**Comment by xsawyerx** [comment]
I can now say that the documentation is actively being worked on! :)

**Comment by LorenzoTa** [comment]
[xsawyerx](https://github.com/xsawyerx): for sure due to my ignorance, but I cannot find the branch where the documentation is actively being worked on: could you be so kind to point me there?
thanks

**Comment by cromedome** [comment]
@LorenzoTa I'd entertain a PR for documentation about this. The code is there, the docs are not. Feel free to send a PR for the current docs, or look at #1069. That's still a ways from completion though!

**Comment by LorenzoTa** [comment]
Dear @cromedome thanks for still looking at this. I do not feel comfortable to send a PR for the documentation as I dont know well this framework. More: I still do not understand if the file .dancer is really used.

I still find it referenced in the [Core/Role/HasLocation.pm](https://github.com/PerlDancer/Dancer2/blob/cc0449c532725763f6c0dc33f1f2c5347bfaa483/lib/Dancer2/Core/Role/HasLocation.pm#L50) and in its test.

It is created bootstrapping a new Dancer2 application but again, I do not understand if it is really used or usefull.

If yes a short sentence in the Doc, like: _.dancer this file is created to help Dancer2 to find the root path of the current application_ should be placed under the BOOTSTRAPPING A NEW APP section of the manual.

If it is not needed then it should be removed from the bootstrap skeleton and from the above mentioned module.

Sorry but I doubt I can give more help :)

thanks for your work
lorenzo

**Comment by cromedome** [comment]
#1683 was created to address this.
