### ISSUE TITLE
Tutorial bug - subcommand omitted

### ISSUE THREAD

**Issue by tmtowtdi** [PerlDancer/Dancer2#1624]
Perl version: 5.30.1
Dancer2 version: 0.301003
Windows version: Windows 10, version 2004, OS Build 19041.985

In the tutorial, under "Part II: Taking Advantage of the dancer2 Utility to Set Up New Apps", the first example command given is

    dancer2 -a Dancr2

But that omits the "gen" subcommand, so the response (on Windows 10) is 

    Unknown option: a

 So the example should be 

    dancer2 gen -a Dancr2

**Comment by cromedome** [comment]
Resolved in #1625. Thanks for reporting!
