### ISSUE TITLE
Deprecated keyword: push_header

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#1646]
## Why?

This keyword had a generic name while only being relevant to the response.

## Benefits to Dancer2 codebase

More consistency and clarity in the code-base.

## Benefit to Dancer2 Community

More consistency and clarity in keywords.

## Alternatives

Use the `push_response_header` keyword instead.

**Comment by cromedome** [comment]
Deprecated in #1696. Closing.
