### ISSUE TITLE
Deprecated keyword: context

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#1649]
## Why?

This is an older keyword reflecting the history in which there was a context object. This object has been removed since in favor of `Dancer2::Core::App` holding the context.

## Benefits to Dancer2 codebase

Remove useless, confusing vestige of a previous state of the code-base.

## Benefit to Dancer2 Community

Remove a keyword that is meaningless in the current Dancer2 system.

## Alternatives

Use the `app` keyword instead.

**Comment by cromedome** [comment]
Deprecated in #1696. Closing.
