### ISSUE TITLE
Deprecated core Request instance method: request->dispatch_path

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#1651]
## Why?

Originally, `request->path()` (which is the `path()` method on `Dancer2::Core::Request`) had a broken implementation. We created the method `dispatch_path()` (which you could call as `request->dispatch_path()`). Since then, we fixed the method `path()` and moved the internal code to use it instead.

## Benefits to Dancer2 codebase

Removing unnecessary method that only existed due to a now-fixed originally-broken implementation.

## Benefit to Dancer2 Community

It is unlikely that anyone had been publicly using this since it has been warning since 2017.

## Alternatives

Use the `app` keyword instead.

**Comment by cromedome** [comment]
Deprecated in #1696. Closing.
