### ISSUE TITLE
Deprecated keyword in plugins: plugin_setting

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#1652]
## Why?

`plugin_setting` is a keyword from the older implementation of plugins. Making it works required jumping through hoops we still cannot decipher even though we wrote them. There is no added value to having this keyword still supported.

## Benefits to Dancer2 codebase

Cleaning up massive chunks of code that exist only to support this keyword.

## Benefit to Dancer2 Community

A consistent way to retrieve the plugin settings without using both the old and new interface.

## Alternatives

When writing a plugin, use the `$self->config()` method instead.

**Comment by cromedome** [comment]
Deprecated in #1696. Closing.
