### ISSUE TITLE
Deprecated keyword in plugins: dancer_app

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#1653]
## Why?

Just like the `plugin_setting` keyword in plugins, this is also a keyword from the old plugins interface. There is no need for this keyword since the new plugins interface is object-oriented and has the available methods.

## Benefits to Dancer2 codebase

A cleaner, leaner code-base.

## Benefit to Dancer2 Community

A more consistent, less confusing interface.

## Alternatives

When writing a plugin, use the `$self->app()` method instead.

**Comment by cromedome** [comment]
Deprecated in #1696. Closing.
