### ISSUE TITLE
Dancer2::Core::Error document is obsolete

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#1669]
The documentation for `Dancer2::Core::Error` includes instantiating a new object and then using the `render` method (which doesn't exist anymore) and then setting it as the response using `Dancer2::Core::Response`'s `set`, which doesn't exist.

Instead, we just create a new instance and call `throw`.

**Comment by GeekRuthie** [comment]
https://github.com/PerlDancer/Dancer2/pull/1680 Addresses this fix.

**Comment by cromedome** [comment]
Resolved, thanks!
