### ISSUE TITLE
Dancer2 Manual on Github is different from Manual on metaCPAN

### ISSUE THREAD

**Issue by gertvanoss** [PerlDancer/Dancer2#1673]
The code for Bootstrapping a new App in Dancer2 Manual seems incorrect

    dancer2 -a MyApp && cd MyApp

this should be

    dancer2 gen -a MyApp && cd MyApp

Github version is correct:
https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Manual.pod

MetaCPAN shows it different:
https://metacpan.org/dist/Dancer2/view/lib/Dancer2/Manual.pod

**Comment by cromedome** [comment]
Good find! We fixed this in Github but have yet to push a release that contains the fix. Hopefully not much longer.

Thanks for the report! I am closing this issue.
