### ISSUE TITLE
Duplicate entries in Makefile.pl for VERSION_FROM created by 'dancer2 gen -a my::app'

### ISSUE THREAD

**Issue by barkYboY** [PerlDancer/Dancer2#1675]
'dancer2 gen -a my::app' puts 2 entries (lib/my/app.pm lib/my/app.pm) in VERSION_FROM field in Makefile.PL 
this causes 'perl Makefile.pl' to fail with 
Could not open 'lib/my/app.pm lib/my/app.pm': No such file or directory at /usr/share/perl/5.34/ExtUtils/MM_Unix.pm line 2967.

removing one of the entries manually cures the error, but doesn't fix it for next project generated.

**Comment by cromedome** [comment]
I've created a PR to address this. Thanks for the bug report!
