### ISSUE TITLE
Document versioning scheme in Dancer2::Policy

### ISSUE THREAD

**Issue by yanick** [PerlDancer/Dancer2#1685]

**Comment by cromedome** [comment]
@yanick Dancer2::Policy is our SoC document. How about I rename GitGuide to Contributing, and include the versioning information there?

**Comment by cromedome** [comment]
Let me ask this instead: do we add our versioning policy to this, or instead, just have Dancer2::Policy cover our standards of conduct, and rename the module to reflect this (to Dancer2::StandardsOfConduct)? It would make it extremely clear what's covered in the document, and be more consistent with what I am seeing in other projects these days.

**Comment by yanick** [comment]
cromedome++ for the more specific names. Dancer2::StandardsOfConduct and Dancer2::Contributing sounds good to me. I have no special feeling for any wording, but the more descriptive, the better it is!

**Comment by cromedome** [comment]
@yanick updated contribution guidelines in #1691.

I am going one step further and documenting my release procedure in another PR. I'll create something akin to `ReleasingDancer2.md`, and document things there. As part of this, I'll link to semver.org and provide examples of how we will use it.

**Comment by cromedome** [comment]
@yanick see also #1693, I think all the bases are covered now! I make reference to semver in the releasing document.

**Comment by cromedome** [comment]
Considering this resolved with the merge of #1693.
