### ISSUE TITLE
Unable to use send_as in template

### ISSUE THREAD

**Issue by abeverley** [PerlDancer/Dancer2#1712]
This is a follow-on problem as a result of #1622 and its fix 3331ad7062

In the highly unlikely event that `send_as` is called during the render of a template, the error `Unable to load serializer class for plain: Can't locate Dancer2/Serializer/plain.pm` will be experienced. This is because 3331ad7062 removes the longjump when a template is processed, which means statements [such as this](https://github.com/PerlDancer/Dancer2/blob/f174c092c4568adbfbabd3aa74a479f5e34f1f9a/lib/Dancer2/Core/App.pm#L975) do not return immediately, leading to unexpected behavior when the subsequent statements are executed.

The use-case here is for the `Dancer2::Plugin::LogReport` plugin, which (in the worst case scenario if can't do anything else) will render a plain text error if there is an unhandled exception when rendering a template.

I have a proposed solution which I will submit as a separate PR.

**Comment by cromedome** [comment]
Resolved with merge at 1f913fde. Thanks!
