### ISSUE TITLE
Can not install with accelerate

### ISSUE THREAD

**Issue by waghanza** [PerlDancer/Dancer2#1720]
Hi,

I can not use `cpanm --installdeps . --with-feature=accelerate` to install some XS module to optimize dancer2.

With the following cpanfile
https://github.com/the-benchmarker/web-frameworks/blob/463af92e3299278d4d2db055772cab3711837a58/perl/dancer2/cpanfile#L1

I have 
```
 ! Installing the dependencies failed: Module 'Config::Any' is not installed
! Bailing out the installation for Dancer2-0.400001.
! Installing the dependencies failed: Module 'Dancer2' is not installed
! Bailing out the installation for ..
42 distributions installed
```

The dockerfile is use is
```dockerfile
FROM perl:5.40-slim

RUN apt-get -qq update && \
  apt-get -qy install --no-install-recommends build-essential

WORKDIR /usr/src/app

  COPY 'd2app.psgi' 'd2app.psgi'
  COPY 'cpanfile' 'cpanfile'

   RUN cpanm --install Gazelle

RUN cpanm --installdeps . --with-feature=accelerate

RUN apt-get -qq update
RUN apt-get -qy install curl
HEALTHCHECK CMD curl --fail http://0.0.0.0:3000 || exit 1

ENTRYPOINT plackup -s Gazelle --port 3000 --env production --app d2app.psgi
```

Regards,

**Comment by cromedome** [comment]
Are those the only errors? I feel there's more to that error dump. Can you paste the full list of errors, if there are more to post?

Unrelated to your question: Dancer2 1.0.0 came out 14 months ago, and we just released 1.1.2 recently. If you don't have a reason to keep the version pinned below 0.5, you should consider installing a more recent version.

--
Jason A. Crome / CromeDome
CPAN: https://metacpan.org/author/CROMEDOME
GitHub: https://github.com/cromedome
Blog: https://cromedome.net

On Sun, Dec 1, 2024, at 8:46 AM, Marwan Rabbâa wrote:
> 
> 
> Hi,
> 
> I can not use `cpanm --installdeps . --with-feature=accelerate` to install some XS module to optimize dancer2.
> 
> 
> With the following cpanfile
> https://github.com/the-benchmarker/web-frameworks/blob/463af92e3299278d4d2db055772cab3711837a58/perl/dancer2/cpanfile#L1
> 
> I have
> 
> ` ! Installing the dependencies failed: Module 'Config::Any' is not installed
> ! Bailing out the installation for Dancer2-0.400001.
> ! Installing the dependencies failed: Module 'Dancer2' is not installed
> ! Bailing out the installation for ..
> 42 distributions installed
`

**Comment by waghanza** [comment]
Thanks for you return  @cromedome. We should used the latest dancer2, I'll take a look at release, this should fix those issues.

**Comment by waghanza** [comment]
Unfortunately it does not work with
```perl
requires 'Dancer2', '>= 1.1.0, < 1.2.0';
```

full log => https://gist.github.com/waghanza/eb3dc77f2d52d70d4b53a2b0c9642f8d

**Comment by cromedome** [comment]
There's an issue with `Module::Pluggable` that prevents it from being installed as root. Temporarily, you can run `cpanm --notest --force Module::Pluggable` before running `cpanm --installdeps .`, and you should be good to go.

It's not a great solution; we've reported the problem to the module's maintainer, and hopefully it will be resolved soon.

Please report back and let us know if that worked for you. Thanks!

**Comment by waghanza** [comment]
Thanks, dancer2 will be out on https://web-frameworks-benchmark.netlify.app tomorrow
