### ISSUE TITLE
Does Dancer2 runs on localhost:3000 instead of 0.0.0.0:3000?

### ISSUE THREAD

**Issue by thegooddeveloper** [PerlDancer/Dancer2#247]
I noticed that when running Dancer2 apps with the simple PSGI HTTP server the message I get upon running the app is "HTTP::Server::Simple::PSGI: You can connect to your server at http://localhost:3000/". 

Dancer1 used to listen on http://0.0.0.0:3000

Was this changed in Dancer2?

**Comment by bcarroll** [comment]
localhost and 0.0.0.0 are not the same. localhost matches 127.0.0.1 where 0.0.0.0 will match any configured IP address on the system

**Comment by xsawyerx** [comment]
`0` is *all interfaces*, `0.0.0.0` is *all IPv4 interfaces*, `localhost` is usually `127.0.0.1`, unless you have an IPv6 interface and then it might tie to that too (or only that).

Dancer2 nowadays with Plack:

    $ plackup -Ilib bin/app.pl 
    HTTP::Server::PSGI: Accepting connections at http://0:5000/

You get to listen to `0` now, which covers both `0.0.0.0` for IPv4 interfaces but also for any IPv6 interface you may have.
