### ISSUE TITLE
Add support for additional configuration files

### ISSUE THREAD

**Issue by dsheroh** [PerlDancer/Dancer2#47]
Applications often require local configuration settings (e.g., database connection info, support email address, etc.) which should neither propagate back into the master copy of the app nor preclude updating the local copy when the master adds new config settings.  To allow for this, Dancer should support a configuration loading order along the lines of:

config.yml, config.local,yml, [environment].yml, [environment].local.yml

In each case, the .local version would be merged into the overall configuration, being merged in essentially the same way that [environment].yml is currently overlaid onto config.yml.

Ideally, this could be generalized even further, allowing users to insert an arbitrary number of additional configuration files at any point in the config loading order, thus allowing configuration of a large number of plugins (both general Dancer plugins and app-specific plugins) without having to resort to putting everything into a single monolithic configuration.

**Comment by rleir** [comment]
Can it be closed now?

**Comment by cromedome** [comment]
Resolved by e9a633d0851f42fa5822151920180a40887a8dbc. Closing!
