### ISSUE TITLE
Strange behavior of Plack+Shotgun on Windows

### ISSUE THREAD

**Issue by azawawi** [PerlDancer/Dancer2#478]
**On Windows, you need to add ```-Ilib```** for a new Dancer 0.09 fresh application to work under Plack+Shotgun:

```
plackup -Ilib -L Shotgun bin\app.pl
```
Otherwise you will get the following error when you access http://127.0.0.1:5000:

```
Error while loading C:\Users\azawawi\TestApp\bin\app.pl: Can't locate TestApp.pm
 in @INC (you may need to install the TestApp module) (@INC contains: C:/strawbe
rry/perl/site/lib/MSWin32-x64-multi-thread C:/strawberry/perl/site/lib C:/strawb
erry/perl/vendor/lib C:/strawberry/perl/lib .) at C:\Users\azawawi\TestApp\bin\a
pp.pl line 3.
BEGIN failed--compilation aborted at C:\Users\azawawi\TestApp\bin\app.pl line 3.
```

**On linux, you do not need to add the ```-Ilib```**

**Comment by xsawyerx** [comment]
@azawawi Does this issue still exist?

**Comment by azawawi** [comment]
@xsawyerx Dancer2 depends on Plack which depends on ```Test::TCP``` which does not install cleanly without a ```cpanm Test::TCP --notest``` on Windows 7 Ultimate 64-bit.

```set PLACK_SHOTGUN_MEMORY_LEAK=1 && plackup -L Shotgun bin\app.psgi```

Works :+1:

**Comment by xsawyerx** [comment]
@azawawi Thank you! :+1:
