### ISSUE TITLE
Prefix inconsistency

### ISSUE THREAD

**Issue by baynes** [PerlDancer/Dancer2#558]
If I have the following routes:
prefix undef;
get '/a' ... it matches '/a' and does not match '/a/'.
get '/b/' ... it matches '/b/' and does not match '/b'.
which is what I would expect.

But if I write the following:
prefix '/b'; get '/' ... it matches '/b' and '/b/'.
But I would expect it to behave as get '/b/' ... above.

It can give some nasty surprises if one has relative links in the generated page. Depending on if the page is loaded as '/b' or '/b/' the links are relative to different places.

It is also desirable to be able to write:
prefix '/b'; get '' ... to be able to match '/b' and not '/b/'.

**Comment by xsawyerx** [comment]
This has been resolved in the latest version thanks to #845.
