### ISSUE TITLE
config error_template does not work

### ISSUE THREAD

**Issue by baynes** [PerlDancer/Dancer2#565]
According to Dancer2::Config one can 

error_template (template path)

This setting lets you specify a template to be used in case of runtime error. At the present moment the template can use three variables:

However this does not work.

Delving in Dancer2::Core::Error it seems that what it actually does is
  use a serializer if one is set
  use $views/$error_code.tt if exists [ not documented ]
  use $public/$error_code.html if exists
  use default generated in code

The sub _render_html which seems to be the relevant code for rendering the template specified by error_template is not called anywhere.

I think the correct sequence should be:
  use a serializer if one is set
  use $views/$error_code.tt if exists
  use $public/$error_code.html if exists
  use error_template if specified
  use default generated in code

The documentation under Dancer2::Config show_errors which attempts to document this sequence will need to be updated. This is also wrong in that even when set to true the same error pages is generated, just the details are tacked on to the end. The wording implies it generates the detailed page another way. [Or is that intended and current behaviour is another bug?[

**Comment by drmuey** [comment]
I'd love to see that “correct sequence” in place, or at least have it working as documented, since non-200 pages look different than the rest of the site and I don’t really want to generate a bunch of static HTML files.

+1

I will submit a pull request if it the Dancer2 folks are amenable to it?

**Comment by veryrusty** [comment]
@drmuey go for it!

**Comment by drmuey** [comment]
@veryrusty ok, thanks :) Should I bump any versions or add any Changes entry or does that happen at release time?

**Comment by drmuey** [comment]
@baynes @veryrusty I have it working :) I just need to add new tests and look for other places in the POD that need to note $views/$error_code.tt

**Comment by drmuey** [comment]
Done, Pull Request 847

**Comment by xsawyerx** [comment]
#849 (based on #847) merged. Thanks! :+1:
