### ISSUE TITLE
Plugins implementation

### ISSUE THREAD

**Issue by dams** [PerlDancer/Dancer2#599]
This is a dump of my brain after we talked about it with @xsawyerx and @mickeyn

## we need Dancer::API

- DSL implementations will only use Dancer::API, no direct access to app or other core stuff
- Plugins will only use Dancer::API, no direct access to app or other core stuff
- dancer api will have the main core features exposed here
- when we change Dancer::API, we know we need to bump major version of dancer.
- so Dancer::API enable plugins isolation from core, enables plugin versionin, and prevent from the plugins messing with Dancer's guts.

## plugins are roles

- Actually I don't think this is a great idea anymore. Dunno, have to think about it
- Benefits are : we don't ned to reinvent the wheel for managing plugins dependancies, plusing mutual exclusions, etc, and it'll help with plugin versioning
- but, plugin would be a role to be applied to *what* ? Not an app, otherwise the plugin could mess with the app gits directly. Need tot hink more about it 

## plugins
- should consume a Dancer2::Role::Plugin, which gives access to Dancer::API.
- using D::API the plugin can Register new keywords
- using D::API the plugin can access the config
- using D::API the plugin can load/unload Plack::Middleware

## keywords
- when a plugin registers a keyword, it actually creates a role, that is applied on the DSL of the current app
- a keyword can be a standard keyword like we are used to it, but it can also be a "route decorator", it's a special keyword that takes the route parameters *before* it's created, so that it can mess ith it, or decide that this route shouldn't be loaded altogether.

## plack middlewares
- we need some syntactic sugar in Dancer2 to be able to add/remove/mess_with Plack::Middlewares.
- This features should be available in Dancer::API, so that DSL and plugins can use it.

**Comment by xsawyerx** [comment]
This is an old braindump and the plugin system *has* been rewritten and available in #1010 and waiting to be merged, so I'm closing this outdated issue.
