### ISSUE TITLE
Dancer2::Tutorial has two "COPYRIGHT AND LICENSE" sections

### ISSUE THREAD

**Issue by dolmen** [PerlDancer/Dancer2#608]
The [Dancer2::Tutotial](https://metacpan.org/pod/Dancer2::Tutorial#COPYRIGHT-AND-LICENSE) has 2 different sections "COPYRIGHT AND LICENSE".
Of course, both have different content.

**Comment by nunorc** [comment]
Can't seem to find the `dancr` example app source files in the current distribution of Dancer2 (they live in `examples/dancr` in Dancer1) -- this means the CSS file is not included. The other files discussed in the tutorial are not included as well.

**Comment by nunorc** [comment]
A possible suggestion is to add a reference to https://github.com/PerlDancer/dancer-tutorial in the Tutorial (which includes the source code). And keep only the Tutorial file in the distribution, and remove the copyright notice for the extra file.

**Comment by xsawyerx** [comment]
Fixed, thanks!

**Comment by dolmen** [comment]
Fixed? Really?
This does not seem to be fixed in the latest release 0.203001.
https://metacpan.org/pod/release/CROMEDOME/Dancer2-0.203001/lib/Dancer2/Tutorial.pod#COPYRIGHT-AND-LICENSE
If a later commit fixed the issue it would be helpful to link to it.

**Comment by dolmen** [comment]
Fixed by 4dae9cb3d90d0d9f3185b619a628e95076bc119f

**Comment by xsawyerx** [comment]
Yes. **Really**. :)
