### ISSUE TITLE
Updating Dancer2 Plugins

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#619]
There's a few modules which needs updating to meet latest Dancer2 releases. This includes both the last master, and the context untangling branch.

List:
* [Dancer2::Session::Cookie](https://github.com/PerlDancer/Dancer2-Session-Cookie)

**master**: patched. Waiting for release. @yanick has the keys.
Submitted https://github.com/PerlDancer/Dancer2-Session-Cookie/pull/9.

* [Dancer2::Plugin::Feed](https://github.com/hobbestigrou/Dancer2-Plugin-Feed)

Submitted https://github.com/hobbestigrou/Dancer2-Plugin-Feed/pull/2.

* Dancer2::Plugin::Paginator - Fails
* Dancer2::Plugin::ProgressStatus - v0.014 passes (uses Dancer2::Test)
* Dancer2::Plugin::RoutePodCoverage - Fails
* [Dancer2::Plugin::Adapter](https://github.com/PerlDancer/dancer2-plugin-adapter) - Fails (tests require updating to use Plack::Test)
* Dancer2::Session::JSON - Fails
* Dancer2::Template::Haml - v0.04 passes (uses Dancer2::Test)
* Dancer::Plugin::Browser - 
* Dancer2::Session::Sereal - Fails
* Dancer2::Plugin::Queue - Fails

Fixed/working:
* [Dancer2::Plugin::Auth::Tiny](https://github.com/PerlDancer/Dancer2-Plugin-Auth-Tiny)
* [Dancer2::Session::PSGI](https://github.com/veryrusty/Dancer2-Session-PSGI)
* [Dancer2::Plugin::Passphrase](https://github.com/hvoers/Dancer2-Plugin-Passphrase)

**Comment by xsawyerx** [comment]
We need this ticket refreshed with latest data. Anyone up for it?

This ticket is also **only** about plugins that simply don't work on recent versions of Dancer2 and is **not** about changing from the previous plugin system to the new plugin system. However, if a plugin is updated and works on the new system, please add it to #1078.

**Comment by SysPete** [comment]
All plugins listed as working in #1078 are known to work with current release *and* plugin2. There is only one plugin known to not work with plugin2 and that is also broken with current D2 release (Auth::YARBAC). I'm not sure there is any value in listing all 55 plugins in this issue as well as #1078.

**Comment by xsawyerx** [comment]
@SysPete Then do I understand correctly that we can just close this ticket?

**Comment by xsawyerx** [comment]
@SysPete, ping. :)

**Comment by SysPete** [comment]
@xsawyerx yes: time to close this one.
