### ISSUE TITLE
Can't find view in blib when using dzil test

### ISSUE THREAD

**Issue by burnersk** [PerlDancer/Dancer2#672]
Issue is that when you are trying to test just a Dancer2 app skeleton with dzil test Dancer2 can't find the views because it tries to find it within blib folder from the dzil test build.

How to solve this? prove works of course because it does not create a test build before.

When Dancer2 find itself within blib it should set views folder to ../views

**Comment by xsawyerx** [comment]
@burnersk update? :)

**Comment by xsawyerx** [comment]
Since we haven't received an update on this, I'm closing the issue.

If it comes again, or if you can provide us with an example of it failing, please reopen the issue or open a new one.

Thank you. :)
