### ISSUE TITLE
to_json and from_json are very expensive if called in a big loop

### ISSUE THREAD

**Issue by simonbrent** [PerlDancer/Dancer2#719]
Because they create a new Dancer2::Serializer::JSON object every time, calling to_json or from_json in a loop can add significant execution time.

I have an example with a loop iterating over about 9000 entries, each with a json string I need to turn into a hashref. In this case, calling Dancer2::from_json took about a second, while calling JSON::from_json took about 0.01 seconds.

Would you consider adding a faster method which didn't create the Serializer object every time?

Note: This was tested with Dancer 1, rather than Dancer2, but the code looks very similar

**Comment by iftekhar25** [comment]
So, looking back at this patch, I wonder if I'm trying to be too clever by adding MooX::Singleton as a dependency, we can just as well make it a whole lot simpler. Feedback is welcome, happy to revise it.

**Comment by xsawyerx** [comment]
@veryrusty's #972 was just merged, resolving this issue.

Thanks for all the discussion and work around it. :)
