### ISSUE TITLE
Replace param() keyword

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#740]
`param` keyword is tricky. It says "please fetch the values of a single parameter key", while it's still susceptible to having multiple values vs. single values.

This means that:

    my $value = param('key');

might return a single value (if a single value was provided by the user) or a single value of arrayref (if multiple values were provided by the user).

This is not just confusing, it's a way to fuck up storage.

If you think arrays will save you, you're still screwed:

    my @values = param('key');

This will return one item in the array with the value if only one is sent, but one item in the array as a arrayref for the values if more than one value was sent.

Moving `params` to `Hash::MultiValue`, we can deprecate this keyword.

    # before
    my $value = param('key');

    # after
    my $value = params->get('key');

We don't actually have to remove `param`. We can still keep it for a long while with a warning.

We would like to get comments before actually doing it. This is why it's labeled as a question.
("We" = @mickeyn and I)

**Comment by yanick** [comment]
What about `param_array()` as implemented in Dancer 1? It's probably isn't the most glamourous nor clever function name  ever, but what it doesn't have in pizzazz, I think it has in term of clarity and straight-forwardness...

**Comment by xsawyerx** [comment]
I thought about this quite a bit. @mickeyn and I came up with one single keyword for all of it: `parameters`. This fits with `Plack::Request`:

    my $body_parameters = parameters('body'); # returns Hash::MultiValue
    my $route_parameters = parameters('route'); # returns Hash::MultiValue
    my $query_parameters = parameters('query'); # returns Hash::MultiValue
    my $all_parameters = parameters; # returns Hash::MultiValue

This allows me to actually use `Plack::Request`'s parsing with very little overrides. The only annoying part is reimplementing the body parsing (which included copying some code) to allow a situation of a serializer present.

And here's my problem: What do we do about serialized parameters? There are two questions remaining before I can provide this PR:

1. Given `{"foo":["bar","baz"]}`, should `parameters->get('foo')` return "bar" (which would happen in the case of `?foo=bar&foo=baz`) or should it return `[ "bar", "baz" ]`?
2. Given non-reference content (`foo`, which can happen with serializations like CBOR), what do we do? `Hash::MultiValue` won't work. Do we crash? Do we ignore it? Do we just deserialize it? What should `parameters()` return?

I'm actually not sure what happens now in CBOR if you try to post parameters of a single value and try to reach it with `params` - but I know (from a test I wrote for the Dancer2 CBOR serializer) that you can easily return a string and it will be available in the user's content. That's not the problem though - the other way around is.

**Comment by veryrusty** [comment]
There are similar questions in #844. i.e. we currently do not handle serialized body content that is not a hashref.

My thoughts from 844 were (but I'm not totally convinced this is the best option):
  * deserialized body is available via `request->data`, no matter what its type with no extra processing after the deserialization.
  * if the data is a hashref, it gets merged with the other params.

**Comment by yanick** [comment]
1. As long as the deserialized body data is always provided as-is through `request->data`, we should probably follow the same behavior than for the other sources of parameters, for consistency sake. Although we should document that in a very big font, 'cause I'm sure it'll surprise a few peeps. :-)

2. In the case of a single entry, I'd say skip it from the parameters, as there is not an obvious key to assign to it.

**Comment by xsawyerx** [comment]
I continued working on this but unfortunately have a problem when trying to make both params() and parameters() work independently. The content is read twice and body parameters reflect twice the content. Maybe I'll try to rework it so params() gets the data directly through parameters() which does the actual work. Sigh.

**Comment by xsawyerx** [comment]
Still, I'm going to merge #937 first since it covers the issue mentioned here.

**Comment by xsawyerx** [comment]
#988 merged!
