### ISSUE TITLE
Rename show_errors as show_stacktrace?

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#769]
`show_errors` actually means to show stacktrace. It's confusing. Wouldn't be better to rename it to `show_stacktrace`?

We can still support `show_errors`, but at least now there's a more descriptive configuration.

**Comment by ambs** [comment]
Just for reference, this includes:

  * changing tests (if any)
  * change the default config file
  * update configuration
  * update the code itself.

And :+1: from me.

**Comment by msouth** [comment]
One good thing about show_stacktrace is that most developers are going to immediately know that this variable is something about output meant for consumption by developers.

**Comment by nunorc** [comment]
Pull request #829 only does the renaming part, I'm guessing that another part would be to support (at least for some time) both options, not sure what is the deprecation cycle on such matters.

**Comment by xsawyerx** [comment]
@nunorc that was my exact comment just now on the PR. :)

**Comment by xsawyerx** [comment]
Merged #1662.
