### ISSUE TITLE
Exception in Core::Response when handling response from failed JSON deserialize attempt

### ISSUE THREAD

**Issue by dboehmer** [PerlDancer/Dancer2#794]
I'm writing an app handling API requests and need to handle invalid JSON/YAML input with a custom error message. Unfortunately Dancer2 behaves strangely when confronted with invalid JSON data.

I built the following example which should have a server side error and send a valid HTTP error back. Instead the code fails at the client side, too, when accessing the response's content.

```
use Modern::Perl;
use Plack::Test;
use HTTP::Request::Common;

{
    package App;

    use Dancer2;

    set logger => 'Console';
    set serializer => 'JSON';

    any '/' => sub {
        return request->data;
    };
}

my $app = App->to_app;

test_psgi $app, sub {
    my $cb = shift;

    say $cb->(POST '/', Content => '{"foo":42}')->decoded_content;
    say $cb->(POST '/', Content => 'invalid')->decoded_content;
}
```

Output from my terminal:

```
{"foo":42}
[App:852] core @2014-12-01 13:00:47> Failed to deserialize the request: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "invalid") at /usr/lib/perl5/site_perl/5.14/JSON.pm line 171. in (eval 166) l. 2
Internal Server Error

Modification of a read-only value attempted at /home/USERNAME/workspace/Dancer2/lib//Dancer2/Core/Response.pm line 72.
```

How to correctly handle invalid data (after all with Serializer::Mutable) on the server side? What's wrong here that decoded_content() fails?

**Comment by seav** [comment]
> You should be able to handle wrong input using the serializer.before hook.

This is currently not possible. Looking at the `Dancer2::Core::Role::Serializer` code, the `engine.serializer.before` hook is only executed on serialization and not on deserialization.
