### ISSUE TITLE
Migration: session_domain was renamed to cookie_domain

### ISSUE THREAD

**Issue by szabgab** [PerlDancer/Dancer2#816]
As far as I'v just found out the session_domain configuration option has been removed
Instead of that there is one called cookie_domain. If that's the case, it would be nice if you could explain in the migration document, how the session management changed.

**Comment by veryrusty** [comment]
Pr #874 added the `session_domain` => `cookie_domain`change in the migration docs.

@szabgab Thanks for noting the change!
