### ISSUE TITLE
Dancer2::Session::YAML documentation refers to page not found

### ISSUE THREAD

**Issue by VinceW** [PerlDancer/Dancer2#831]
In the See Also section of Dancer2::Session::YAML there is textual reference to Dancer2::Session

When clicking on the link I expect to be taken to (the documentation) related to Sessions in Dancer2
However, the current link is pointing to Dancer2::Session. This link resolves in a 'page not found'

If the current situation **is** intentional, please disregard this ticket.
Otherwise:
I propose to change the link into: Dancer2::Core::Session

If it's however the intention to point to the Dancer1 version of session (more descriptive documentation, or whatever) the link could be changed into: Dancer::Session

I'm willing to prepare a fix for this, just need to know where the link should point to.

best,
VinceW

**Comment by xsawyerx** [comment]
You are absolutely right, @VinceW. I have just merged your fix!
