### ISSUE TITLE
Uninitialized variable in Core::Request

### ISSUE THREAD

**Issue by pants** [PerlDancer/Dancer2#852]
This appears from time to time in my logs:
> Route exception: Use of uninitialized value $value in string ne at /usr/local/lib/perl5/site_perl/Dancer2/Core/Request.pm line 664. in /usr/local/lib/perl5/site_perl/Return/MultiLevel.pm l. 97

This is part of `_build_cookies`. Malformed cookies (not sure where they come from, but regardless...) without an `=` will cause Dancer2 to die. It may be worth changing `Core/Request.pm` line 664 from:

    if ( $value ne '' )

to

    if ( defined $value and $value ne '' )

**Comment by veryrusty** [comment]
@pants++ for reporting the issue! Could you put together a test case and your suggested fix in a Pr ?

**Comment by pants** [comment]
Never done this process before. Please let me know if I did the fork/pull request/etc. correctly!

**Comment by veryrusty** [comment]
@pants your fork/pr process was awesome! :dancers:

**Comment by xsawyerx** [comment]
Solution merged, so I'm closing this.

Thanks. :)
