### ISSUE TITLE
0.159000: t/route-pod-coverage/route-pod-coverage.t fails with Pod::Simple 3.30

### ISSUE THREAD

**Issue by eserte** [PerlDancer/Dancer2#855]
See http://matrix.cpantesters.org/?dist=Dancer2%200.159000 for a pass/fail overview.

Looking at the analysis at http://analysis.cpantesters.org/solved?distv=Dancer2-0.159000 it seems that the fails are caused by Pod::Simple 3.30.

**Comment by veryrusty** [comment]
I've reported the change in behaviour of Pod::Simple::Search->find() upstream.
  * https://rt.cpan.org/Ticket/Display.html?id=102344

**Comment by veryrusty** [comment]
I've just pushed 4b376b0 (straight to master) with a workaround.

@xsawyerx once travis reports all is good, can you do a point release ?

**Comment by xsawyerx** [comment]
Absolutely!

Thank you, @eserte, @veryrusty. :)

**Comment by xsawyerx** [comment]
Released!

Thanks again, guys! :+1:
