### ISSUE TITLE
Internal Error in Templates

### ISSUE THREAD

**Issue by pdl** [PerlDancer/Dancer2#857]
When TT2 does not have a plugin that is used by a template, it causes an error.

I spent some time trying to work out if and how my Dancer2::Session::YAML was configured incorrectly before realising the missing plugin was not Dancer2's but Template::Plugin::YAML (it wasn't installed).

Is there any way of making the error message a little more clear, as currently, it reads:

> Error 500 - Internal Server Error
>
> plugin error - YAML: plugin not found
>
> Powered by Dancer2 0.159001 

__It would be nice to know that the error is with the templating engine rather than some other part of Dancer2.__

Steps to recreate:

```
# new perlbrew without Template::Plugin::YAML installed

dancer2 -a My::D2App
cd My-D2App/
echo 'template: template_toolkit' > config.yml
echo '[% USE YAML %] test' > views/layouts/main.tt 
echo '[% USE YAML %] test' > views/index.tt 
plackup bin/app.psgi

# GET localhost:5000/
```

**Comment by racke** [comment]
This seems to be bug, it doesn't show a stacktrace with `show_errors: 1`, only:

```
TestApp:26453] error @2015-03-28 11:16:45> Route exception: plugin error - YAML: plugin not found in /home/racke/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.1/Dancer2/Core/App.pm l. 1151
```

**Comment by xsawyerx** [comment]
PR #875 fixes the misleading error message.

**Comment by xsawyerx** [comment]
I'm closing this as it referred to the error message. #875 was merged.

@racke Would you like to open a different ticket to research why `show_errors` doesn't return the stack trace?
