### ISSUE TITLE
dzil build putting wrong $VERSION in Dancer2.pm

### ISSUE THREAD

**Issue by shadowcat-mst** [PerlDancer/Dancer2#879]
sherlock$ dzil build
[DZ] beginning to build Dancer2
[@Filter/ExtraTests] rewriting release test xt/release/distmeta.t
[@Filter/ExtraTests] rewriting author test xt/author/no-tabs.t
[@Filter/ExtraTests] rewriting release test xt/release/pod-syntax.t
[@Filter/PkgVersion] skipping lib/Dancer2.pm: assigns to $VERSION
[DZ] writing Dancer2 in Dancer2-0.159003
[MarkdownInRoot] overriding README.mkdn in root
[DZ] building archive with Archive::Tar; install Archive::Tar::Wrapper 0.15 or newer for improved speed
[DZ] writing archive to Dancer2-0.159003.tar.gz
[DZ] built in Dancer2-0.159003
sherlock$ grep VERSION Dancer2-0.159003/lib/Dancer2.pm 
$Dancer2::VERSION ||= '0.159000';
=head1 VERSION
sherlock$ 

So PkgVersion appears to be skipping it because it finds the version already present, thereby leaving the defaulted version in Dancer2.pm rather than the correct one. However -

16:09 < corecache> during the build, I get a notice from Filter/PkgVersion that 
                   it skips VERSION assignment for Dancer2.pm, which would 
                   actually result in the correct version string
16:14 <@mst> oh, interesting
16:14 <@mst> are you building the right commit?
16:15 <@mst> hrm, master is at 0.159000
16:15 <@mst> dist.ini sets final version
16:15 <@mst> yeah, that's fucked up
16:16 <@mst> sawyer: I'm unsure what your dzil config is supposed to be doing, 
             but I don't think that was it :)
...
10:49 <@sawyer> mst: the dist.ini provides a $VERSION variable and 
                lib/Dancer2.pm provides a default if it's not supplies
10:49 <@sawyer> *supplied
10:49 <@sawyer> it's for a test and should be removed
10:49 <@sawyer> but dist.ini is actually configured correctly

I can't understand how not replacing the placeholder version is correct, though.

**Comment by xsawyerx** [comment]
The problem is not `dzil`. The problem is that there's a test that checks for a version. Some tests could ascertain the version so sukria hard-coded it for testing purposes.

We can remove, find the test that fails (if it still exists). and fix it.

**Comment by shadowcat-mst** [comment]
dzil build is producing WRONG contents in lib/Dancer2.pm

This means that either your dzil.ini is broken or the contents of lib/Dancer2.pm is broken. The test might be why it *became* broken but it is not the bug I am reporting.

While it appears the latest Dancer2 was released using a version of the relevant plugin that jammed the version at the top anyway - the current release has two $VERSION lines instead of one, which is gross but probably not actively harmful - but the version I have, from dzil 5.034, shows a warning instead and doesn't add the line.

As such, THE CURRENT REPOSITORY IS NOT SAFE TO RELEASE FROM.

Please consider re-tagging the issue to reflect this.

**Comment by racke** [comment]
Which test, @xsawyerx ?

**Comment by racke** [comment]
If fails if you say for example:

`prove -vl t/forward.t`

Which is perfectly valid in principle to run just one test file.

**Comment by shadowcat-mst** [comment]
16:11 <@mst> racke: the problem is that we decided to switch to having dzil 
             generate $VERSION
16:11 <@mst> racke: but there are tests that expect it to be there
16:11 <@mst> racke: so somebody put that hack in Dancer2.pm, thereby 'fixing' 
             the test via prove but breaking dzil build
16:11 <@mst> intended consequences ftl, also, welcome to monday
16:11 < racke>  is(
16:11 < racke>             $res->headers->server,
16:11 < racke>             "Perl Dancer2 $Dancer2::VERSION",
16:11 < racke>             '[POST /bounce/] Correct Server',
16:11 < racke>         );
16:11 <@mst> right
16:12 <@mst> so if we're going to generate the $VERSION via dzil
16:12 <@mst> that needs fixed
16:12 <@mst> alternatively, there are dzil versionbump plugins that will keep 
             the $VERSION managed but in-repo
16:12 <@mst> I don't honestly care which route we take
16:12 <@mst> just have to take one of them or you can't do releases :)
16:12 < racke> ok we just skip this test if $VERSION is undef
16:13 <@mst> or you could set $Dancer2::VERSION ||= 'DUMMY' in the test script
16:13 <@mst> I don't see that would be a problem

**Comment by shadowcat-mst** [comment]
#dist-zilla recommends http://p3rl.org/Dist::Zilla::Plugin::RewriteVersion::Transitional which looks like it'll do the trick nicely to me, then we can leave the tests as-is -and- have the repo better match the shipping dist, which tends to be much less confusing for non-dzil-experts

**Comment by racke** [comment]
:+1:  - sounds good to me. Any volunteers with dzil experience?

**Comment by xsawyerx** [comment]
Please review #882 for a fix. Once it's approved I'll merge and make a release.

**Comment by xsawyerx** [comment]
Merged #883 which fixes this.
