### ISSUE TITLE
Are Simple sessions enabled by default?

### ISSUE THREAD

**Issue by szabgab** [PerlDancer/Dancer2#884]
According to https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Manual.pod
even 'Simple' sessions must be enabled first, but as I can see Dancer2 v0.159003 has Simple sessions enabled by default

Created a new app with ```dancer2 -a Abc```
Edited the lib/Abc.pm to have the following route:
```
get '/' => sub {
    my $cnt = session 'cnt' || 0;
    $cnt++;
    session cnt => $cnt;
    debug("Counter $cnt");
    template 'index';
};
```
Launched it using ```plackup bin/app.psgi``` and load the page in the browser.
This set a cookie in the browser and did not complain abut sessions not being enabled.
As I reload the page several time I see the counter increasing in the console output.
If I stop and start plackup, I can see the counter starts from 0 again.

**Comment by xsawyerx** [comment]
I can't find where it says *even 'Simple' sessions must be enabled first*. What I see is the sentence: *To make use of sessions, you must first enable the session engine* and then `simple` used as an example of how to enable.

It is indeed the default, as seen here:

https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Core/App.pm#L176

**Comment by szabgab** [comment]
From the pod I understood that I need to enable sessions in order to use sessions.
Even if I only wants Simple sessions.
My experiment shows that Simple sessions are enabled by default.

**Comment by xsawyerx** [comment]
From what I read in the POD it says you need to enable sessions. We can make a note that Simple sessions are the default.

Your experiment shows what I also said is correct behavior, yes.

**Comment by xsawyerx** [comment]
Here:
https://github.com/PerlDancer/Dancer2/commit/065f55a879c3191eb6897ecc727a29a2574499c3

**Comment by szabgab** [comment]
I still think the docs say that you need to make some changes in order to enable sessions,
specifically to addd
```
session: Simple
```
to the config file, but that note you just linked to and the actual behavior of Dancer2 shows me that
even without that entry, sessions already work.
But then again this is just my understanding of the docs.

**Comment by xsawyerx** [comment]
I don't understand the confusion.

The docs state:
* In order to use sessions, you need to pick which session you want.
* Here is an example.
* If you don't pick, there is a default: Simple sessions.

What is the problem? Perhaps you can provide with an example of clearer docs, because I don't understand the confusion you have from your explanations alone. Maybe an example will help me.

**Comment by szabgab** [comment]
"By default Dancer 2 has Simple sessions enabled. If you'd like to use a different session engine you must declare it in the configuration file. For example to use YAML file base sessions you need to add ```session: "YAML"``` to config.yml.
This is a change from Dancer 1 where, by default no session engine was enabled."

**Comment by xsawyerx** [comment]
https://github.com/PerlDancer/Dancer2/commit/66092aa665ea40fb8677e8d3ba4b7fd3d8942fc2

Is this better?

**Comment by szabgab** [comment]
Yes, I think it is much better. Thanks.
An addition:
I think it would be even better if the config.yml created by ```dancer2``` would include something like this:
```
session: Simple
# By default Simple, in-memory sessions are enabled (See Dancer2::Session::Simple ) 
# If you'd like to have YAML file based sessions, replace the above line with the following:
# session: YAML
````

That will put this information right where people need it.
