### ISSUE TITLE
Skel folder needs to be cleaned in each installation

### ISSUE THREAD

**Issue by ambs** [PerlDancer/Dancer2#886]
Accordingly with the current repo, there is only a share/skel/bin/app.psgi, but dancer2 still generates a share/skel/bin/app.pl. Why? because the installation process does not clean the share folder installed in the system.

Result? an app.pl is generated that does not work as expected (perl app.pl).

**Comment by xsawyerx** [comment]
Unfortunately the Dancer installation guides do not support deleting older versions, and there are is no versioning in the installation directories.

We could have the command line hard-code the files to deploy instead. That would work even if `app.pl` exists.

**Comment by ambs** [comment]
You can go two ways. Or keep the list of files anywhere, or prior to the installation, delete the full Dancer shared folder, and reinstall it.

In any way, installing the old app.pl with non working code (in the sense of, non working accordingly with the old way) is bad :)

**Comment by xsawyerx** [comment]
Deleting files as part of our installation: probably not possible, but definitely not recommended.

*installing the old app.pl with non working code* -- You're not talking about installing, you're talking about scaffolding. If we have a hard-coded list of files to scaffold, we will not scaffold the `app.pl` file. That will solve it, no?

**Comment by ambs** [comment]
Sorry, yes, I was talking about scaffolding. And yes, it will solve the problem. Given we probably do not change much the files from the scaffolding tree, letting it (`app.pl`) die there should be acceptable.

**Comment by rleir** [comment]
close this issue?  .. when you get a moment, thanks

**Comment by ambs** [comment]
Sure.
