### ISSUE TITLE
config port bug

### ISSUE THREAD

**Issue by andrewsolomon** [PerlDancer/Dancer2#890]
Using Dancer2 v0.159003  "set port => 3001;" in the app works as expected. If instead, I have 'port: 3001' in config.yml it listens to 3000 (the default port). In spite of this, when I dump the config it says 'port' => '3001'

```perl
student@ip-10-28-251-125:~/tmp/portbug$ cat app.pl 
#!/usr/bin/env perl

use Dancer2;
use Data::Dumper;

#set port => 3001;

get '/' => sub { 'Hello config: '.Dumper(config) };

dance;
```

```yml
student@ip-10-28-251-125:~/tmp/portbug$ cat config.yml 
port: 3001
```
```bash
student@ip-10-28-251-125:~/tmp/portbug$ curl localhost:3001
curl: (7) couldn't connect to host
student@ip-10-28-251-125:~/tmp/portbug$ curl localhost:3000
Hello config: $VAR1 = {
          'behind_proxy' => 0,
          'logger' => 'console',
          'template' => 'Tiny',
          'apphandler' => 'Standalone',
          'startup_info' => 1,
          'static_handler' => undef,
          'appdir' => '/mnt/data-store/student/tmp/portbug',
          'route_handlers' => [
                                [
                                  'AutoPage',
                                  1
                                ]
                              ],
          'traces' => 0,
          'host' => '0.0.0.0',
          'content_type' => 'text/html',
          'environment' => 'development',
          'views' => '/mnt/data-store/student/tmp/portbug/views',
          'public_dir' => '/mnt/data-store/student/tmp/portbug/public',
          'no_server_tokens' => 0,
          'charset' => '',
          'port' => '3001'
        };
student@ip-10-28-251-125:~/tmp/portbug$ 
```

**Comment by djzort** [comment]
i am facing this too, --port xxxx doesnt seem to work either?

**Comment by djzort** [comment]
This seems related https://github.com/PerlDancer/Dancer2/issues/385

Apparently --port is no longer supported but is still in Dancer2::Config pod (http://search.cpan.org/~xsawyerx/Dancer2/lib/Dancer2/Config.pod#Run_mode_and_listening_interface/port)

This works but is not documented

export DANCER_PORT=1234

**Comment by xsawyerx** [comment]
I'm sorry I haven't yet replied to this ticket. It's actually much simpler: If you use `plackup`, it doesn't matter what port you pick in the app, it's controlled by `plackup`. If you use `dance`, it will take the port into account:

```
$ cat app.pl
use Dancer2;
set port => 3002;
dance;
```

```
$ perl -Ilib app.pl
>> Dancer2 v0.000000_000 server 13607 listening on http://0.0.0.0:3002
```

That's it.
*(The version number there is for the development.)*

**Comment by djzort** [comment]
Could the pod be updated the help the next traveler?

**Comment by xsawyerx** [comment]
@djzort Absolutely! What do you think would be a good phrasing?

**Comment by djzort** [comment]
In Dancer2/Config.pod: 

B<port (int)>

The port Dancer2 will listen to. Default value is 3000. 

 $ cat app.pl
 use Dancer2;
 set port => 3002;
 dance;

If using L<plackup> to run your program, this setting can be provided on the command-line with the I<--port> switch. 

In Dancer2/Cookbook.pod: 

=head2 NON-STANDARD STEPS(?)
=head3 Port that your server listens on

If using L<plackup>, this setting can be provided on the command-line with the I<--port> switch or even the I<--listen> switch to use a UNIX socket instead. 

If using L<Plack::Handler::Apache2>, then use your apache configuration.

In your standalone app via:

 $ cat app.pl
 use Dancer2;
 set port => 3002;
 dance;

Or as an environmental variable for your standalone app:

 export DANCER_PORT=1234
