### ISSUE TITLE
cpanm Dancer2 fails at tests

### ISSUE THREAD

**Issue by modmanx** [PerlDancer/Dancer2#896]
I'm trying to install lib through cpanm and it gives me this error:

```
[main:4515] error @2015-04-28 19:49:09> Exception caught in 'core.app.before_request' filter: Hook error: Can't locate object method "failure" via package "Foo" (perhaps you forgot to load "Foo"?) at t/app.t line 150.
 at /home/dev/.cpanm/work/1430261337.4425/Dancer2-0.160000/blib/lib/Dancer2/Core/App.pm line 952. in /home/dev/.cpanm/work/1430261337.4425/Dancer2-0.160000/blib/lib/Dancer2/Core/App.pm l. 526
```
Should there be some trick to install with cpanm?

**Comment by veryrusty** [comment]
@modmanx Thanks for the report. That string gets emitted as part of the test suite, but won't stop Dancer2 installing.

Can you have another look through the build log, or post it somewhere (a gist) or email it (you can use my email address from the mailing list) so we can identify what's going on.

**Comment by modmanx** [comment]
Thank you for fast response
Here is a gist with log of installation

https://gist.github.com/modmanx/64a9bdedea5d371a9170

uname -a
```
Linux dev-VirtualBox 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by veryrusty** [comment]
Thanks for the full build log @modmanx.   It's the `t/config_reader.t` test failing, which is being discussed in #893.

If you need an immediate workaround you can either
  * install YAML::XS, or 
  * downgrade Config::Any to v0.24.

**Comment by modmanx** [comment]
Thank you again for rapid response! I installed YAML::XS and it's working now.
