### ISSUE TITLE
Dancer2 appears to remember the response serializer from one request to the other: if no serializer is set the last one set is remembered

### ISSUE THREAD

**Issue by emil-perhinschi** [PerlDancer/Dancer2#901]
when running https://github.com/PerlDancer/Dancer2-Plugin-REST/blob/master/t/02_prepare_serializer_for_format.t :

the last pair of tests (output and content type for path => '/') fail because the response is generated with the serializer set for the previous request ( path => '/foo.yml', content_type => qr'text/x-yaml')

the solution I found was to
  delete $dsl->response->{serializer}   (
when path is '/' but it might be a problem that the response serializer survives requests

**Comment by rleir** [comment]
Did the fix work? Close this when you get a moment, thanks!

**Comment by veryrusty** [comment]
It's still broken; and on my December hacking list to resolve. Deleting engines is a hacky workaround that I can't recommend.

**Comment by emil-perhinschi** [comment]
" delete $dsl->response->{serializer} ("

is not a fix, it is a workaround, the only way to get rid of the serializer when you want to return HTML

**Comment by veryrusty** [comment]
@emil-perhinschino that is not the case. One solution to this is `Dancer2::Plugin::SendAs`.

**Comment by cromedome** [comment]
Resolved as part of #1457. Thanks!
