### ISSUE TITLE
[RFC] label and milestone usage

### ISSUE THREAD

**Issue by burnersk** [PerlDancer/Dancer2#903]
Hi folks. This is a meta "issue" about labeling GitHub issues and assigning them to milestones. Some months ago I wrote a message to the Dancer2 mailing list explaining some of my basic ideas for "communicating to users via milestones". In this issue I like to present my thoughts about the actual strategy for labeling future GitHub issues. **This is a discussion issue** so please *don't* just take this and change everything (old or from now) to this schema.

# Labels

## How hard is something to implement/fix?

Currently there are labels for that like *Beginner Suiteable*. I would like to prefer a more detailed structure:

* `severity:High` means it is really hard to implement/fix the labeled issue
* `severity:Moderate` means a expertised developer can implement/fix the labeled issue
* `severity:Normal` - well, does this actually needs an explanation ;)
* `severity:Easy` means a new developer can implement/fix the labeled issue
* `severity:Trivial` means anyone can implement/fix the labeled issue (mostly for typos or documentation)

## How huge is the impact?

* `priority:Critical` exposed shell access, security related issues, breaks (mostly) everything, kills the server (mem)
* `priority:High` breaks common things, stresses the server (mem, i/o)
* `priority:Medium` breaks not-so-common things
* `priority:Low` produces warnings - so - does not break things

## Which part(s) is/are affected?

Note: module in this context means only modules which are shipped with the Dancer core. 3rd party modules does not apply here.

* `core:$FEATURE`
* `module:$MODULE`
* `module:$MODULE:$FEATURE`

## Further labels

* What kind
  * `type:Code`
    * `type:Code:New-Feature`
    * `type:Code:Enhancement`
    * `type:Code:Bug`
  * `type:Documentation`
* Scheduling
  * `delayed` the labeled issue was intended to be implemented/fixed in the last release. So please prefer those issue
  * `next-major` this issue is planned for the next major release

# Milestones

Milestones will be there for every release in the past and for the current. The following milestones will also be there - always:

* Next revision release (e.g. 0.160001)
* Next but one revision release (e.g. 0.160002)
* Next minor release (e.g. 0.161000)
* Next major release (e.g. 1.000000)

Having a issue that is *not* assigned to an milestone does *not* mean, that those issue shouldn't be working on. It just means that those weren't yet planned. On the other side... issue which do have a milestone assigned should go in that release. If there are one or a few issue couldn't done in time, they will be moved to the next release milestone and labeled as `delayed`.

**Comment by burnersk** [comment]
I forgot to write the milestones section. Updated the description.

**Comment by xsawyerx** [comment]
We don't have *that* many issues. We barely tag them even nowadays (something I was just looking at). Is it possible that this is over-engineering it?

**Comment by rleir** [comment]
An interesting question thanks, but perhaps this is not the place for it. Can we close it?

**Comment by xsawyerx** [comment]
I do feel like this was a bit over-engineered, but there was not further discussion on this since created, so it does not seem to spark enough interest.

I'm closing this.

If interest comes up, we can always revisit the issue and reopen.

**Comment by rleir** [comment]
Is there a Dancer2 Roadmap for future plans? This discussion would fit well there.

**Comment by xsawyerx** [comment]
There isn't a roadmap right now, except ideas we have in mind, some of which appear in tickets.

Starting a roadmap is a good idea. @rleir, would you be interested in working on one?

**Comment by rleir** [comment]
Would it help if I did a quick summary of the open, forward-looking tickets? It could be put in the wiki. Then everyone can tap on it, improve it, and keep it going in the future.

On June 14, 2016 4:40:03 AM EDT, Sawyer X <notifications@github.com> wrote:
>There isn't a roadmap right now, except ideas we have in mind, some of
>which appear in tickets.
>
>Starting a roadmap is a good idea. @rleir, would you be interested in
>working on one?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/PerlDancer/Dancer2/issues/903#issuecomment-225816272

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rleir** [comment]
[would you tap on this when you have a moment](https://github.com/PerlDancer/Dancer2/wiki/Roadmap)
