### ISSUE TITLE
 #510 is not resolved by #892 after all

### ISSUE THREAD

**Issue by drmuey** [PerlDancer/Dancer2#905]
Unfortunetely, #510 is not resolved by #892 :( its behaving like it was in my first post to #510

Dancer2 v.160000 and Dancer2::Plugin::Database v 2.12 still give me: 
Hook 'database_connected' does not exist at /Users/dmuey/perl5/perlbrew/perls/perl-5.16.0/lib/site_perl/5.16.0/Dancer2/Plugin/Database.pm line 45.

commenting out line 45, $dsl->execute_hook(@_);, (since I am not using the hooks) allows it to work but that is a limited temporary hack :)

**Comment by veryrusty** [comment]
@drmuey can you reduce this issue to a minimimal test case ?

**Comment by drmuey** [comment]
sure, I'll try to do that ASAP, thx

**Comment by drmuey** [comment]
Doh! The app I was seeing this on has a use lib '…' that went to a specific checkout (i.e. old version) of Dancer2.

Removing that and having 0.160001 installed does indeed seem to work. Thanks y’all!

I owe @veryrusty some beer at YAPC :) Thanks!
