### ISSUE TITLE
No import of read_glob_content in App.pm

### ISSUE THREAD

**Issue by sevenk** [PerlDancer/Dancer2#906]
The use of send_file with streaming:
return send_file($s_filepath, system_path => 1, streaming=>1, $s_file_cf, content_type=>$cont);

results in:
Route exception: Undefined subroutine &Dancer2::Core::App::read_glob_content called at /usr/share/perl5/site_perl/Dancer2/Core/App.pm line 885

importing read_glob_content fix this.

**Comment by veryrusty** [comment]
Thanks for reporting this @sevenk !

There is also a logic error in send_file; it should stream be default but the example above is hitting the code path for non-streaming of content even with `streaming => ` specified.  Expect a patch soon.

**Comment by veryrusty** [comment]
@sevenk If this is blocking development, note that you do not need to add `streaming=>1` as an option to send_file if you want to use psgi streaming. Streaming is the default option if the server supports it. Removing `streaming => 1` from your call will stop the above mentioned logic error from being triggered but still stream the content.

**Comment by veryrusty** [comment]
Fix has been applied to master.

@xsawyerx can you do a release ?
