### ISSUE TITLE
[PATCH] fix spelling/grammar glitches

### ISSUE THREAD

**Issue by gregoa** [PerlDancer/Dancer2#910]
In Debian we are currently applying the following patch to Dancer2.
We thought you might be interested in it too.

    Description: fix spelling/grammar glitches
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2015-05-16
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libdancer2-perl.git/plain/debian/patches/language.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by veryrusty** [comment]
Merged as 267d8af.  Thanks @gregoa !
