### ISSUE TITLE
public/404.html not displaying

### ISSUE THREAD

**Issue by andrewsolomon** [PerlDancer/Dancer2#912]
For release 0.160001 the 404 error retrieving a page from public/404.html has stopped working (again:)

It's easy to replicate this by creating a default framework `dancer2 gen -a MyWeb::App` and visiting http://hostname/invalidroutename

Playing with the various versions I have at hand, it seems to be fairly fragile functionality:

0.09 - OK
0.143000 - BUG
0.150000 - OK
0.159003 - BUG
0.160001 - BUG

**Comment by veryrusty** [comment]
If the setting `show_errors` is true, then a static error page is NOT rendered. This allows the errors to actually be shown.  I think this is a reasonable approach, but understand that it may catch some out.

This is noted in the `environments/development.yml` that is generated via `dancer2 gen -a MyWeb::App`, which may not be the best place to have this behaviour documented. If you can think of a better place to also document this, doc patches are extremely welcome  [subtle hint ;)].

**Comment by xsawyerx** [comment]
:+1:

**Comment by xsawyerx** [comment]
Closing this issue since it's known.

@andrewsolomon the commits you've pushed to your fork, would it be possible to submit them as PR?
