### ISSUE TITLE
Dancer2-0.160002 test failure with Plack v1.0036

### ISSUE THREAD

**Issue by nanis** [PerlDancer/Dancer2#921]
I haven't tried to diagnose this, but here some information:

- I have a working 0.160001 install
- <pre>C:\...\Dancer2-0.160002> perl -MPlack::Response -E "say $Plack::Response::VERSION"
1.0036</pre>
- Will link to test output on CPANTesters when it becomes available.
- Below, I added a call to dump the `$plack` object right before the problem:

<pre>C:\Users\sinan\.cpanm\work\1433418642.3540\Dancer2-0.160002> perl -Iblib\lib t/classes/Dancer2-Core-Response/new_from.t
1..3                                                                                                                   
ok 1 - Dancer2::Core::Response->can(...)                                                                               
    # Subtest: new_from_array                                                                                          
    1..4                                                                                                               
    ok 1 - An object of class 'Dancer2::Core::Response' isa 'Dancer2::Core::Response'                                  
    ok 2 - Correct status                                                                                              
    ok 3 - Correct content                                                                                             
    ok 4 - All headers correct                                                                                         
ok 2 - new_from_array                                                                                                  
    # Subtest: new_from_plack                                                                                          
    1..5                                                                                                               
    ok 1 - An object of class 'Plack::Response' isa 'Plack::Response'                                                  
    # --- !!perl/hash:Plack::Response                                                                                  
    # body: Bar                                                                                                        
    # headers: !!perl/hash:HTTP::Headers::Fast                                                                         
    #   content-type: text/plain                                                                                       
    #   x-test: Val                                                                                                    
    # status: 200                                                                                                      
coercion for "headers" failed: Not an ARRAY reference at blib\lib/Dancer2/Core/Role/Headers.pm line 16.                
    # Child (new_from_plack) exited without calling finalize()                                                         
not ok 3 - new_from_plack                                                                                              
#   Failed test 'new_from_plack'                                                                                       
#   at c:/opt/perl-5.22.0/lib/Test/Builder.pm line 279.                                                                
# Looks like you failed 1 test of 3.                                                                                   
# Looks like your test exited with 255 just after 3.</pre>

<pre>Summary of my perl5 (revision 5 version 22 subversion 0) configuration:
   
  Platform:
    osname=MSWin32, osvers=6.3, archname=MSWin32-x64-multi-thread
    uname=''
    config_args='undef'
    hint=recommended, useposix=true, d_sigaction=undef
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cl', ccflags ='-nologo -GF -W3 -O1 -favor:INTEL64 -MD -Zi -DNDEBUG -GL -fp:precise -DWIN32 -D_CONSOLE -DNO_STRICT -DWIN64 -DCONSERVATIVE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE  -DPERL_TEXTMODE_SCRIPTS -DUSE_SITECUSTOMIZE -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS',
    optimize='-O1 -favor:INTEL64 -MD -Zi -DNDEBUG -GL -fp:precise',
    cppflags='-DWIN32'
    ccversion='18.00.31101', gccversion='', gccosandvers=''
    intsize=4, longsize=4, ptrsize=8, doublesize=8, byteorder=12345678, doublekind=3
    d_longlong=undef, longlongsize=8, d_longdbl=define, longdblsize=8, longdblkind=0
    ivtype='__int64', ivsize=8, nvtype='double', nvsize=8, Off_t='__int64', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='link', ldflags ='-nologo -nodefaultlib -debug -opt:ref,icf -ltcg  -libpath:"c:\opt\perl-5.22.0\lib\CORE"  -machine:AMD64 "/manifestdependency:type='Win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'"'
    libpth="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\lib\amd64"
    libs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib
    perllibs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib
    libc=msvcrt.lib, so=dll, useshrplib=true, libperl=perl522.lib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags='-dll -nologo -nodefaultlib -debug -opt:ref,icf -ltcg  -libpath:"c:\opt\perl-5.22.0\lib\CORE"  -machine:AMD64 "/manifestdependency:type='Win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'"'

Characteristics of this binary (from libperl): 
  Compile-time options: HAS_TIMES HAVE_INTERP_INTERN MULTIPLICITY
                        PERLIO_LAYERS PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
                        PERL_IMPLICIT_CONTEXT PERL_IMPLICIT_SYS
                        PERL_MALLOC_WRAP PERL_NEW_COPY_ON_WRITE
                        PERL_PRESERVE_IVUV USE_64_BIT_INT USE_ITHREADS
                        USE_LARGE_FILES USE_LOCALE USE_LOCALE_COLLATE
                        USE_LOCALE_CTYPE USE_LOCALE_NUMERIC USE_LOCALE_TIME
                        USE_PERLIO USE_PERL_ATOF USE_SITECUSTOMIZE
  Built under MSWin32
  Compiled at Jun  2 2015 07:12:31
  %ENV:
    PERLDOC_PAGER="c:\opt\cygwin64\bin\less.exe -+C -E -F -g -i"
  @INC:
    c:/opt/perl-5.22.0/site/lib/MSWin32-x64-multi-thread
    c:/opt/perl-5.22.0/site/lib
    c:/opt/perl-5.22.0/lib
    .
</pre>

**Comment by eserte** [comment]
Tests fail on all platforms with Plack 1.0036. 1.0034 and earlier is fine. See http://analysis.cpantesters.org/reports_by_field?distv=Dancer2-0.160002;field=mod%3APlack

**Comment by nanis** [comment]
Interesting. Thank you.

**Comment by veryrusty** [comment]
Plack 1.0035 changed to using HTTP::Headers::Fast, but the coercion in Dancer2::Core::Role::Headers doesn't handle HTTP::Headers::Fast objects.

**Comment by veryrusty** [comment]
Change the title to reflect this is an issue against Plack, rather than a specific platform.

Fix in #922 :dancers:

**Comment by nanis** [comment]
Thank you @veryrusty for the diagnosis & update.

**Comment by nanis** [comment]
Thank you!

<pre>--> Working on X/XS/XSAWYERX/Dancer2-0.160003.tar.gz
Fetching http://www.cpan.org/authors/id/X/XS/XSAWYERX/Dancer2-0.160003.tar.gz ... OK
Configuring Dancer2-0.160003 ... OK
Building and testing Dancer2-0.160003 ... OK
Successfully installed Dancer2-0.160003</pre>
