### ISSUE TITLE
failed memory_cycles.t issue

### ISSUE THREAD

**Issue by gravattj** [PerlDancer/Dancer2#924]
After some trial and error, I found that upgrading Devel::Cycle to 1.12 fixed this:

```
t/logger_console.t ..................................... ok

#   Failed test 'runner has no memory cycles'
#   at t/memory_cycles.t line 25.
# Cycle #1
#     Dancer2::Core::Runner A->{apps} => @B
```

**Comment by xsawyerx** [comment]
This is no longer an issue since in the next version `Devel::Cycle` is not going to be installed. None of the less, I've added it as a recommendation in the `dist.ini` file.

Thanks! :)
