### ISSUE TITLE
session_dir default value is not "appdir/session"?

### ISSUE THREAD

**Issue by sherwind** [PerlDancer/Dancer2#926]
Hi,

I'm using uwsgi to run multiple Dancer apps on a dev server. It works fine except that today I noticed apps that don't specify session_dir create and share "sessions" directory under /etc/uwsgi.d -- the cwd before each app is launched. I already fixed this issue in uwsgi but my understanding is that the default session_dir should be "appdir/sessions". Is this a bug or my understanding of appdir is just wrong? Thanks 

    $ perldoc Dancer2::Session::YAML | grep -B1 default
       Files will be stored to the value of the setting "session_dir", whose
       default value is "appdir/sessions".

    $ dancer2 -a MyWebApp

    $ echo 'session: "YAML"' >> MyWebApp/config.yml

    $ ls
    MyWebApp        

    $ plackup MyWebApp/bin/app.psgi &>/dev/null &

    $ lwp-request -s -d http://localhost:5000
    200 OK

    $ ls
    MyWebApp        sessions

    $ grep -A4 'has session_dir' $(perldoc -l Dancer2::Core::Role::SessionFactory::File)
    has session_dir => (
        is      => 'ro',
        isa     => Str,
        default => sub { path( '.', 'sessions' ) },
    );

**Comment by hvoers** [comment]
I think this is a bug, the code is wrong.

path( '.', 'sessions' ) should be path( setting('appdir'), 'sessions' )

**Comment by hvoers** [comment]
I made a PR #929

**Comment by veryrusty** [comment]
Thanks for reporting this @sherwind. Looks like a bug to me, `appdir/sessions` as the default is going to be less surprising that `./sessions`

@hvoers that suggestion won't work. `setting` is a DSL keyword, which will not be available within `Dancer2::Core::Role::SessionFactory::File`.  Looks like there are no tests against that role either :(

**Comment by hvoers** [comment]
On Thu, 11 Jun 2015, Russell Jenkins wrote:

> @hvoers that suggestion won't work. setting is a DSL keyword, which will not be available within Dancer2::Core::Role::SessionFactory::File.

Mmm. 'path' is a DSL keyword and it works just fine.

@Sherwin Can you test this patch?

**Comment by sherwind** [comment]
@hvoers you are right that there is a `path` DSL but @veryrusty must be correct as well. `Dancer2::Session::YAML` consumes `Dancer2::Core::Role::SessionFactory::File` which provides the `session_dir` attribute. The `path` that gets called by the default value provider of `session_dir` is the one from `Dancer2::FileUtils`.

**Comment by sherwind** [comment]
It's a he said, she said situation. Both `Dancer2::Session::YAML` and `Dancer2::Session::JSON` claim that`session_dir` defaults to `appdir/sessions` but in the code they don't do anything to support it and just left it to `Dancer2::Core::Role::SessionFactory::File`. In contrast, `Dancer2::Core::Role::SessionFactory::File` says that the default value is `./sessions` and does that exactly in the code. :-)

**Comment by veryrusty** [comment]
@sherwind++  Thanks for taking the time for the explanation.

I concur that `appdir/sessions` is the best "default" location for session files. Its not possible to define with the default for the `session_dir` attribute in `Dancer2::Core::Role::SessionFactory::File`. However its trivial to pass that "default" in when the session engine is instantiated in `Dancer2::Core::App`. 

We still needs tests for the file-based session roles and stores.. Need to find more tuits!

**Comment by xsawyerx** [comment]
Fixed merged. Thanks for reporting! :+1:
