### ISSUE TITLE
error_template not rendered for implicit 404

### ISSUE THREAD

**Issue by mattchance** [PerlDancer/Dancer2#936]
When there are no matching routes or static files for a request and a 404 is thrown, the error_template set in the config is not used.

To reproduce:
https://gist.github.com/32544ef5d6972184050d

A request to /does-not-exist will result in error.tt being rendered, due to explicitly throwing a 404 error.
A request to /doesnt-exist however will not result in error.tt being rendered, instead a built-in error page.

**Comment by veryrusty** [comment]
Hmmm, `Dancer2::Core::Error` is attempting to render the `error_template` for that second URL, but fails with this error (and hence falls back to the default error page):
```
Can't call method "params" on an undefined value at lib/Dancer2/Core/Role/Template.pm line 180.
```

**Comment by xsawyerx** [comment]
Fix merged. Thanks for reporting! :+1:
