### ISSUE TITLE
Callbacks for streaming asynchronous responses

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#941]
While we have the `content` keyword for streaming content to the user as part of an asynchronous response, we have no way of knowing whether it worked or not.

The writer does not expose whether it was able to write or not. This means that if a user closed a connection before we called `done`, you will probably get a caught exception in your log that you can't do anything about.

While there are discussions on expanding the spec of PSGI to accommodate for that, maybe we should already think of syntax that - for now - will just eval the write operation instead. I've checked and this approach works, but I'm not sure about the DSL for it.

I'm mainly interested in hearing what everyone thinks a good syntax would be:

The simple case would be to have two callbacks for success and fail for the `content` keyword:

    content $more_data, \&success, \&fail;
  
Another would be to return a promise:

    my $p = content $mode_data, \&success, \&fail;
    $p->then(...);

or

    content( $more_data, \&success, \&fail )->then(...);

But that would require a promises module (I like `Promises` personally) which I don't know if we want to add to core. I'm thinking a plugin might help with this, or perhaps a module that upgrades regular callbacks into promises (and then maybe wrap that in a plugin or specialized DSL) - the **q** library has that.

Another option would be named callbacks:

    content $new_data, on_success => \&success, on_fail => \&on_fail;

Another would be a new keyword of some kind, but I'm not sure that will actually help.

Any other ideas I missed?

**Comment by andrewsolomon** [comment]
I have no experience with Promises but having now read [Promises::Cookbook::GentleIntro](https://metacpan.org/pod/Promises::Cookbook::GentleIntro) I think it'd be a great addition.

My preference is to have named callbacks. Partly because of its readability, but also because this is a new terrain it leaves more room for change.

**Comment by xsawyerx** [comment]
I think the first question to answer is: Should we return promises or not. That ties us into either Futures or Promises. There is an implementation of **q** in Futures but not for Promises. If we had that, we could say "we don't return promises, but you can use these modules to create promises from it".

We would need some sample code for it.

We can make the `content` keyword faster by using positional parameters and prototypes instead of named parameters, a la `AE`.

**Comment by xsawyerx** [comment]
Reconsidering this, providing a callback for the entire `delayed` makes more sense. When a write fails, the entire `delayed` should fail. You should be able to do an eval for each `content` call, but otherwise have one `on_error` callback for the entire response.

How about this syntax:

    get '/' => delayed {
        content "hello";
        done;
    } on_error => sub {
        my $data_or_better_name = shift;
        my ( $error, $req, $res, ... ) = @{$data_or_better_name}{qw<error request response ...>;
        ...;
    };

**Comment by xsawyerx** [comment]
Fixed by #999 and merged!
