### ISSUE TITLE
VERSION sub doesn't validate the given argument

### ISSUE THREAD

**Issue by miyagawa** [PerlDancer/Dancer2#943]
perl's UNIVERSAL VERSION sub is supposed to validate a supplied argument, when it is given.

```
➜  ~  perl -e 'use Data::Dumper'
➜  ~  perl -e 'use Data::Dumper 11'
Data::Dumper version 11 required--this is only version 2.154 at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

Dancer2's VERSION sub defined in #879 #882 #883 don't pass the argument (`@_`) to its SUPER sub, meaning `use Dancer2 99` or `perl -MDancer2\ 99` will just pass without checking the version, which is incorrect.

See perldoc UNIVERSAL for more about this behavior.

You should at least pass the argument to the super sub. You might also want to invest a bit in dzil setup so that it keeps the `$VERSION` value  in the repository .pm files. That way you don't need to override `VERSION` sub in the first place.

**Comment by xsawyerx** [comment]
The problem we have is running the testing suite outside `dzil test` (which is what I prefer, honestly), so this method seemed to work best. Let me fix this right by passing the `@_`.

Thank you for spotting this!

**Comment by xsawyerx** [comment]
Hmm... Changing it to `shift->SUPER::VERSION(@_)` doesn't fix it either, since there's no $VERSION number to compare it to:

    $ perl -Ilib -MDancer2\ 999
    Dancer2 does not define $Dancer2::VERSION--version check failed at lib/Dancer2.pm line 16.
    BEGIN failed--compilation aborted.

Which means we'll need to sort out the dzil config. Sigh.

**Comment by miyagawa** [comment]
> Changing it to shift->SUPER::VERSION(@_) doesn't fix it either, since there's no $VERSION number to compare it to:

Well at least it's now correctly giving you an error, rather than accepting whatever version requirement you throw in.

Unless no test suite runs `use Dancer2 1` or something against your git version of the perl module file, the new code will just run fine as soon as you ship it with the real `$VERSION` in your code.

**Comment by xsawyerx** [comment]
Good point. Will commit, push, and release tomorrow. A release is due for a while now.

**Comment by xsawyerx** [comment]
Pushed: https://github.com/PerlDancer/Dancer2/commit/8d0810f34b77be9a35c8c6784dbfa76f1ec3f748

@miyagawa++.

**Comment by karenetheridge** [comment]
@xsawyerx if you're looking to get real $VERSIONs into your repo code via dzil I can help - hit me up on irc! (the short version of the answer is: [RewriteVersion::Transitional] plus [Git::Commit].)

**Comment by xsawyerx** [comment]
@karenetheridge I had hoped I wouldn't relapse into spending hours on dzil configurations. :/

My problem tends to be "I don't want to use this plugin until I actually understand it", and that leads to 17 other plugins. Would still be happy (and thankful) to at least discuss this.

**Comment by veryrusty** [comment]
As someone who was asleep when this was reported/fixed/merged (damn timezones), thanks to all!
