### ISSUE TITLE
Failure to escape paths in regex patterns causes spurious failures on Windows

### ISSUE THREAD

**Issue by nanis** [PerlDancer/Dancer2#947]
Can be fixed by using `\Q$file\E` on line 22 of the test script `t\logger_console.t`.

See also [Tests failing due to directory separators are unforced errors](http://www.nu42.com/2014/11/tests-failing-due-to-path-separators.html).

<pre>t\logger_console.t ..................................... Unrecognized escape \l passed through in regex; marked by <-- HERE in m/core in t\l <-- HERE ogger_console.t l. 15/ at t\logger_console.t line 22.

t\logger_console.t ..................................... 1/? #   Failed test 'core message sent'
#   at t\logger_console.t line 22.
#                   '[test:4652] core @2015-07-12 21:57:26> core in t\logger_console.t l. 15
# '
#     doesn't match '(?^:core in t\logger_console.t l. 15)'
Unrecognized escape \l passed through in regex; marked by <-- HERE in m/debug in t\l <-- HERE ogger_console.t l. 15/ at t\logger_console.t line 22.

#   Failed test 'debug message sent'
#   at t\logger_console.t line 22.
#                   '[test:4652] debug @2015-07-12 21:57:26> debug in t\logger_console.t l. 15
# '
#     doesn't match '(?^:debug in t\logger_console.t l. 15)'
Unrecognized escape \l passed through in regex; marked by <-- HERE in m/info in t\l <-- HERE ogger_console.t l. 15/ at t\logger_console.t line 22.

#   Failed test 'info message sent'
#   at t\logger_console.t line 22.
#                   '[test:4652] info @2015-07-12 21:57:26> info in t\logger_console.t l. 15
# '
#     doesn't match '(?^:info in t\logger_console.t l. 15)'
Unrecognized escape \l passed through in regex; marked by <-- HERE in m/warning in t\l <-- HERE ogger_console.t l. 15/ at t\logger_console.t line 22.

#   Failed test 'warning message sent'
#   at t\logger_console.t line 22.
#                   '[test:4652] warning @2015-07-12 21:57:26> warning in t\logger_console.t l. 15
# '
#     doesn't match '(?^:warning in t\logger_console.t l. 15)'
Unrecognized escape \l passed through in regex; marked by <-- HERE in m/error in t\l <-- HERE ogger_console.t l. 15/ at t\logger_console.t line 22.

#   Failed test 'error message sent'
#   at t\logger_console.t line 22.
#                   '[test:4652] error @2015-07-12 21:57:26> error in t\logger_console.t l. 15
# '
#     doesn't match '(?^:error in t\logger_console.t l. 15)'
# Looks like you failed 5 tests of 5.
t\logger_console.t ..................................... Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/5 subtests</pre>

**Comment by veryrusty** [comment]
Thanks for reporting this @nanis!! Do you have the tuits to patch and create a pull request ?

**Comment by nanis** [comment]
I'll probably get around to it in less than 12 hours. Just wanted to make sure I submitted it before I forgot.

**Comment by veryrusty** [comment]
Thanks in advance @nanis; that is most awesomely appreciated!

**Comment by xsawyerx** [comment]
@nanis++ !

**Comment by nanis** [comment]
Apologies ... c75cbfe should not have been listed here as it is incomplete (missed the unescaped dot in the pattern). Only 91c2f34 should be applied.

**Comment by nanis** [comment]
See [pull request](https://github.com/PerlDancer/Dancer2/pull/948) which replaces this issue.
