### ISSUE TITLE
config key "views" maybe broken with tt?

### ISSUE THREAD

**Issue by wchristian** [PerlDancer/Dancer2#951]
15-07-15@17:07:09 (Mithaldu) what is the correct way to configure custom template toolkit paths with dancer2?
15-07-15@17:07:35 (Mithaldu) setting views: meep/marp just causes TT to look for meep/marp/meep/marp/my.tt
15-07-15@17:12:38 (Mithaldu) i guess telling TT to INCLUDE_PATH: . works too, if a little inelegant

**Comment by rleir** [comment]
Are you still seeing the problem? (please close the issue if not). In my test, it seems correct to me:

set views => path(dirname(__FILE__), 'meep/marp');

.. lib/Cfoo/meep/marp/hello.tt is not a regular file or reference at /usr/local/share/perl/5.20.1/Dancer2/Core/Role/Template.pm line 128.\n"}

**Comment by wchristian** [comment]
Repro steps:

- osname=MSWin32, osvers=6.3, archname=MSWin32-x86-multi-thread-64int
- uname='Win32 strawberry-perl 5.18.4.1 #1 Thu Oct  2 12:10:29 2014 i386'
- dancer2 0.162000 installed 
- download https://dl.dropboxusercontent.com/u/10190786/micro.zip
- unpack
- perl app.pl
- curl localhost:3000
- error @2015-10-01 21:30:03> Route exception: Failed to render template: file error - rami\my.tt: not found at C:/strawberry/perl/site/lib/Dancer2/Core/Role/Template.pm line 128.
- remove comments on engine config
- perl app.pl
- curl localhost:3000 
- works

**Comment by veryrusty** [comment]
The example by @rleir has an absolute path, whereas the example from @wchristian has a relative path for `views`.  Pr #955 has the details even if the solution there is not the preferred one.

**Comment by rleir** [comment]
@veryrusty Thanks for #955. @wchristian Does this work for you?

**Comment by wchristian** [comment]
The explanation in #951 is fine, though i'll have to leave it up to you, whether you wish to close this based around having one unaccepted pull request.

**Comment by veryrusty** [comment]
Please leave the issue open.

**Comment by veryrusty** [comment]
Fixed by #1037. Thanks @wchristian for raising the issue!
