### ISSUE TITLE
please add a way to disable the serializer for responses within a route

### ISSUE THREAD

**Issue by wchristian** [PerlDancer/Dancer2#952]
I have an app that's 99% json API, and needs a small handful of pure html endpoints, which almost entirely use the same code that the rest of the app does. Creating an entirely separate dancer2 app would be a waste of effort.

Right now i am doing this and it serves me decently fine:

    sub html (&) {
        my ( $route ) = @_;
        sub { delete app->response->{serializer}; $route->( @_ ) }
    }
    
        get "search" => html {
            template "rami/search", { name => "abc" };
        };

I would however prefer to be able to directly unset the serializer on the response object, or have a more direct way to affect that.

**Comment by veryrusty** [comment]
The `template` keyword returns the rendered content which you still need to encode before sending.

Rather than unset the serializer, use `send_file($fh,..)`:
```
sub html (&) {
    my $route = shift;
    sub {
        # call route and encode content
        my $content = Encode::encode( 'UTF-8', $route->(@_) );
        # stream content
        send_file(\$content, content_type => 'text/html; charset=UTF-8');    
    }
}
```
which could be further refined to use the apps charset.

**Comment by veryrusty** [comment]
@wchristian If you have a spare minute, could you take a look at [Dancer2::Plugin::SendAs](https://metacpan.org/pod/Dancer2::Plugin::SendAs). Suggestions are much appreciated!

**Comment by veryrusty** [comment]
Dancer2::Plugin::SendAs solves the original issue. Closing issue.

**Comment by wchristian** [comment]
I'm not on the project that needed it anymore, so i can't give it a test, however looking at the synopsis the plugin looks fine. However, personally i wouldn't consider this resolved unless the plugin is also mentioned in the Dancer2 core docs, as it otherwise becomes a piece of tribal knowledge (i hope it is known why that is bad).

**Comment by veryrusty** [comment]
Thanks @wchristian. Agree that tribal knowledge sucks.  I'll get it documented.

I've got a project I want to use it on; if that is successful I plan on making it core functionality.

**Comment by wchristian** [comment]
Sounds good. :)
