### ISSUE TITLE
"headers" is only calling "header" again.

### ISSUE THREAD

**Issue by gmalley** [PerlDancer/Dancer2#956]
It seems like "headers" is only calling "header" again instead of literally calling the "headers".

When testing the code below with curl, it returns empty.

post '//hook' => sub { my $hd = header "Content-Type"; "Your Headers: [".$hd."]"; };

**Comment by hvoers** [comment]
This is not a valid issue.
You want to inspect the "incoming POST headers" aka request->headers
"header" and "headers" are for setting one or more *response* headers.

Please close this issue.

**Comment by hvoers** [comment]
See also https://metacpan.org/pod/Dancer2::Manual#DSL-KEYWORDS

**Comment by xsawyerx** [comment]
Henk be right! :)

I apologize for confusing people on the mailing list, I was a bit confused myself.

Thank you, Henk.

**Comment by gmalley** [comment]
Thank you.
