### ISSUE TITLE
use *** with ***; seems to be misdocumented

### ISSUE THREAD

**Issue by wchristian** [PerlDancer/Dancer2#958]
This is regarding: https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Manual.pod#EXPORTS

It claims you can do:

    package MyApp;
    use Dancer2;
     
    set session => 'YAML';
    use Blog with => { session => engine('session') };

However due to Perl phasers rules, that wouldn't work, since the `use Blog` would be called before the `set session`.

**Comment by xsawyerx** [comment]
Fixed. Thanks! :+1:
