### ISSUE TITLE
Custom error template rendering broken by use of var in 'before' hook

### ISSUE THREAD

**Issue by aka-raj** [PerlDancer/Dancer2#959]
Dancer2 0.161

1) 500.tt rendered OK:

    any '/foo' => sub {
      die ('died here');
      template 'foo';
    }

2) inclusion of a before_template_render hook causes 500.tt to be ignored:

    hook before_template_render => sub {
      my $tokens = shift;
      var some_var => 21; # <= this seems to be culprit ??
    };

* show_errors: 0 -  msg = "Wooops, something went wrong"
* show_errors: 1 - msg = "died here at /home/raj/apps/error_test/bin/../lib/error_test.pm line 16"

commenting out 'var' in before_template_render hook restores proper 500.tt rendering function

**Comment by aka-raj** [comment]
just realised use of 'var' in before_template_render hook probably not supported - substituting $tokens->{some_var} instead works fine

**Comment by veryrusty** [comment]
May need to break this into two issues
  * Dancer2::Core::Error->_build_content has two `eval` blocks that render templates. If an error is thrown by either, we never log the actual error. That makes debugging harder than it should be.
  * The error being thrown when the custom template being rendered is
```
Function 'var' must be called from a route handler
```

If someone wants to look into this before I get a chance, it looks like where ever Dancer2::Core::App generates a Dancer2::Core::Error object, we need to ensure that `$Dancer2::Core::Route::REQUEST` and `$Dancer2::Core::Route::RESPONSE` are localised to the current request/response.

**Comment by xsawyerx** [comment]
Fix in #962 merged. Thanks for opening the ticket! :)
