### ISSUE TITLE
the manual links for the debug commands go nowhere

### ISSUE THREAD

**Issue by wchristian** [PerlDancer/Dancer2#960]
See: https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Manual.pod#LOGGING

**Comment by hvoers** [comment]
Should point to:
https://metacpan.org/pod/Dancer2::Manual#debug
Ditto for warning, info and error.

**Comment by xsawyerx** [comment]
Fixed. Thanks @wchristian, @hvoers! :+1:
