### ISSUE TITLE
Custom handling of errors in core.app.before_request

### ISSUE THREAD

**Issue by aka-raj** [PerlDancer/Dancer2#961]
Custom error template doesn't handle "Exception caught in 'core.app.before_request' filter: Hook error: [...]"

None of the init_error, before_error, after_error & on_route_exception hooks get called beforehand, but the 'before' hook does, but then request terminates with above message. 

Can core.app.before_request errors be handled in same way as route errors?

Full text message:
>Internal Server Error

>Exception caught in 'core.app.before_request' filter: Hook error: DBD::mysql::st execute failed: 
>[...] at /home/raj/apps/RequestForm/bin/../lib/RequestForm/DB.pm line 147.
> at /home/raj/perl5/lib/perl5/Dancer2/Core/App.pm line 962.
> at /home/raj/perl5/lib/perl5/Dancer2/Core/Role/Hookable.pm line 114.

**Comment by veryrusty** [comment]
`before_request` hooks are executed after a route is matched but before its executed. If they die, rendering custom errors should "just work". Looks straight forward to implement. Expect a Pr soonish :)

**Comment by xsawyerx** [comment]
Fix in #964 merged. Thank you for opening the ticket. :)
