### ISSUE TITLE
Dancer2::Cookbook Templates

### ISSUE THREAD

**Issue by djzort** [PerlDancer/Dancer2#963]
it states "For a full list of the tokens automatically added to your template (like session, request, and vars, refer to Dancer2::Core::Role::Template)."

No such details exist though?

**Comment by krokozy** [comment]
Move to other framework, Dancer seems good but the docs are a joke.

**Comment by xsawyerx** [comment]
Please do not add spiteful comments. This is a comment on a specific problem that needs solving. You have raised another concern for doc issues in general and that should be discussed there (hopefully without any spiteful comments either).

@djzort, good point. I will try to fix that tomorrow.

**Comment by djzort** [comment]
no rush, just wanted to capture it

**Comment by xsawyerx** [comment]
@djzort, Done: https://github.com/PerlDancer/Dancer2/commit/7d8b0fecc809f2ff7a09cdbf5cd48b1b1980f208

Thank you. :)
