### ISSUE TITLE
Dancer2 can't compile & Travis-CI didn't pick it up

### ISSUE THREAD

**Issue by vlyon** [PerlDancer/Dancer2#965]
Ever since e250caf86afd60705b7b1e8c7992cf837a5503a3 Dancer2 can't compile due to the missing role `Dancer2::Core::Role::Response` which is used on line 6 of `lib/Dancer2/Core/Response/Delayed.pm`

Sadly this failure has not been picked up by Travis-CI because of how it installs dependencies.
The command: `dzil listdeps --author --missing` will return `Dancer2::Core::Role::Response` as a missing dependency which happens to be part of the Dancer2 cpan package!

Once an older version of Dancer2 is installed all the tests pass, giving us a false positive.
But when we remove the old version of Dancer2, the tests can't even run (can't compile).

There needs to be a way to prevent `dzil` from giving Dancer2 as a dependency on itself.

**Comment by veryrusty** [comment]
Nice pickup! @vlyon++  Will fix shortly.

**Comment by veryrusty** [comment]
Removed the non-existand role from Dancer2::Core::Response::Delayed.

**Comment by veryrusty** [comment]
Thanks again @vlyon!

**Comment by vlyon** [comment]
@veryrusty 
It's a quick fix, but the problem with `dzil` still remains.
Any way of fixing that to prevent this from happening again?
