### ISSUE TITLE
D2::Plugin::Database & log_queries fails

### ISSUE THREAD

**Issue by aka-raj** [PerlDancer/Dancer2#977]
> Dancer2 v0.161000 server 7695 listening on http://0.0.0.0:3000
> Dancer2::Plugin::Database (2.12)

_config.yml_

    plugins:
      Database:
        log_queries: 1

_myapp.pm_
database->quick_select($sql):

_console_
Undefined subroutine &Dancer::Logger::debug called at [...]/Dancer/Plugin/Database/Core/Handle.pm line 285.

**Comment by veryrusty** [comment]
This looks like a bug in the plugin.

Ping @ambs & @bigpresh  .

**Comment by ambs** [comment]
Will look to it asap

**Comment by ambs** [comment]
@aka-raj, do you have the time to test with http://eremita.di.uminho.pt/~ambs/Dancer-Plugin-Database-Core.tar.gz ?

**Comment by ambs** [comment]
(bug detected, trying to understand if the fix fixes it)

**Comment by ambs** [comment]
if you prefer, https://github.com/bigpresh/Dancer-Plugin-Database/tree/fix/logger

**Comment by aka-raj** [comment]
Sure, will let you know. Probably tomorrow (Sunday) before i get chance.

On 15/08/2015 19:16, Alberto Simões wrote:
>
> @aka-raj <https://github.com/aka-raj>, do you have the time to test 
> with 
> http://eremita.di.uminho.pt/~ambs/Dancer-Plugin-Database-Core.tar.gz 
> <http://eremita.di.uminho.pt/%7Eambs/Dancer-Plugin-Database-Core.tar.gz> ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PerlDancer/Dancer2/issues/977#issuecomment-131416505>.
>

-- 
Richard Jones

**Comment by ambs** [comment]
Sure! Thanks

**Comment by aka-raj** [comment]
Yes that works for me, all 'quick' methods dump query to console. Thanks.

On 15/08/2015 19:16, Alberto Simões wrote:
>
> @aka-raj <https://github.com/aka-raj>, do you have the time to test 
> with 
> http://eremita.di.uminho.pt/~ambs/Dancer-Plugin-Database-Core.tar.gz 
> <http://eremita.di.uminho.pt/%7Eambs/Dancer-Plugin-Database-Core.tar.gz> ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PerlDancer/Dancer2/issues/977#issuecomment-131416505>.
>

-- 
Richard Jones

**Comment by ambs** [comment]
Weeee. Releasing during today.

**Comment by ambs** [comment]
Fixed on Dancer::Plugin::Database::Core version 0.12.
Thanks one more.
