### ISSUE TITLE
prefix dispatch processing are different by Dancer/Dancer2

### ISSUE THREAD

**Issue by fangyuan** [PerlDancer/Dancer2#985]
Hi, I meet a prolem when try to upgrade to Dancer2.

use case:

```perl
package App;
use App::Product;
prefix => undef;

1;

package App::Product;
prefix => '/product';
get '/' => sub {
    # product list
};

get '/view/:id' => sub {

};
```

In Dancer, `GET /product` same as `GET/product/`, both return status `200`. 

But in Dancer2, `GET /product` status is `404`, `GET /product/` status is `200`.

So I need add `/` for these links in pages, maybe it is not good solution.
Any suggestions? Thanks.

**Comment by fangyuan** [comment]
Debug code and find the reason is that the `regexp` is different for Dancer and Dancer2.
In Dancer: `_compiled_regexp' => qr/(?^:^(?^:^\/product(?:\/)?$)$)/`
In Dancer2: `'regexp' => '^\\/product$'`

I find the example code in #845,  
```perl
prefix '/' => sub { get '' => sub {...} };
```
then update original Dancer app routes,
```perl
package App::Product;
prefix '/produtc';
get '' => sub { #in Dancer, get '/' => sub{};
};
```
then it can find route exists, fix the problem.

Maybe someone could help add this tip to Dancer2::Manual::Migration. Thanks.

**Comment by hvoers** [comment]
No, do not close this.
It's a bug in D2.

**Comment by veryrusty** [comment]
No, this was a deliberate change. I'll comment more when at a keyboard rather than just a phone. #817 and the linked issues and Prs have the back story.

Anyone wish to do a pull request to note change in migration docs? ;)

**Comment by veryrusty** [comment]
Here is a slightly longer version.

The two paths `/foo` and `/foo/` represent different resources (see the HTTP spec). In D2 these two routes match `/foo/` but not `/foo`:
```
prefix '/foo' => sub { get '/' => sub {...}; };
prefix '/foo' => sub { get '/:bar?' => sub {...}; };
```
Having one of these matching `/foo` but not the other (as in D1) is inconsistent.

The change in D2 is about constructing routes with prefixes in a consistent way (strings are concatenated before the resulting route is converted into a regex). As a result D2 allows prefixes to be lexical, allow for (optional) named params and splats in a consistent way. This makes it possible to keep route definitions "DRY" by using a prefix for both `/foo` and `/foo/`.

Here's a contrived example to show what *is* possible in D2:
```
prefix '/hello' => sub {
  # prefixes concatenated, including params
  prefix ':world?' => sub {
    get '' => sub { '/hello' . param('world') };
    # match /hello/ 
    prefix '/:name?' => sub {
      get '' => sub { '/hello' . param('world') . '/' . param('name') };
      # mixed optional named params and splats
      get '/**' => sub {
        my ($mega) = splat;
        join '/', '/hello' . param('world'), param('name'), @$mega
      };
    };
  };
};
```

I hope that all makes sense. If you have time to put together an addition to the migration docs to cover this, a PR would be most appreciated (we *love* doc patches)!.
