### ISSUE TITLE
Deprecated examples on Dancer2::Plugin

### ISSUE THREAD

**Issue by ambs** [PerlDancer/Dancer2#990]
A simple fix is needed in https://metacpan.org/pod/Dancer2::Plugin to remove that part on 'module compatibility' that is deprecated.

**Comment by cromedome** [comment]
Are you talking about the "Deprecation note" between the "register_plugin" and "plugin_args" sections? If so I will cut that out and submit a pull request shortly.

**Comment by xsawyerx** [comment]
Fixed by #1020. Thanks!
