### ISSUE TITLE
Dancer2 automated sanity checks with swat

### ISSUE THREAD

**Issue by melezhik** [PerlDancer/Dancer2#994]
Hi! I have recently created a sanity checks suite for a simple Dancer application:
- install Dancer
- run a simple dedicated dancer application under plack/starman
- run smokes test against:
    - `:` parameters
    - get, post requests
    - cookies
    - static file
    - config parameter

- An example  travis builds could for found here - https://travis-ci.org/melezhik/dancer2-swat-test
- Till PAUSE index gets updated  it is recommend to install from stratopan

```
   $ cpanm -q --mirror-only --mirror https://stratopan.com/melezhik/swat-packages/master swat::dancer
   $  swat swat::dancer 
```

- Project home page - https://github.com/melezhik/swat-packages/tree/master/dancer

---

If you guys found this interesting we could talk about further collaboration. Thanks.

**Comment by xsawyerx** [comment]
@melezhik I apologize for my ignorance, but why did you create the ticket? What would you like us to help with?

**Comment by melezhik** [comment]
Hi @xsawyerx ! Thanks for the answer. There many ways as swat could be used.One of possible interest for Dancer2 developers is to provides black box tests to be run in continues integration chain. Like you dev guys develop another version of Dancer and runs some checks after commit. This is travis example with tap output of such a tests. Current it is possible by swat:

- installs  an Dancer2 framework from the source
- runs a dedicated , sample Dancer2 application
- make a _various_ requests against it
- validate responses 
- at the end shut down application
- return result as tap output ( generated by prove )  

---

I know it is somewhat that  overlaps with existed unit test at Dancer2 contribution, but swat make it difference in some, I could explain it more, also there is documentation available at  swat github pages and also some examples ( not too many ) at http://swatpm.org

**Comment by xsawyerx** [comment]
Thank you for the input. We will discuss the option of using swat. Meanwhile I'm closing this ticket since there is no "issue" to fix.

Thanks again.

**Comment by melezhik** [comment]
sure, thanks.

**Comment by melezhik** [comment]
Hi @Xaerxess !  btw I have updated latest swat test suite for dancer2 -  please follow  https://github.com/melezhik/swat-examples/tree/master/dancer

**Comment by Xaerxess** [comment]
@melezhik CC: @xsawyerx ;)

**Comment by melezhik** [comment]
sorry  @Xaerxess  , this was github wrong prompt, definitely I mean @xsawyerx !

**Comment by Xaerxess** [comment]
No problem!

**Comment by melezhik** [comment]
Hi I have just uploaded a sparrow plugin to run regression tests against sample dancer2 application - https://sparrowhub.org/info/swat-dancer2?v=0.000002 , please tell me what you think about it, and if this could be useful for dancer2 development? Don't hesitate ask any questions, here in github or by email. Sparrow/swat could be  good way to run a dedicated tests suites in Dancer2 development. Thanks.

Alexey
