### ISSUE TITLE
add "charset" to content-type "application/json"

### ISSUE THREAD

**Issue by JaHIY** [PerlDancer/Dancer2#995]
`Dancer2::Serializer::JSON` should read the `charset` from config and add it to `content-type`.

For example, if I set `charset` to `utf-8` in config, the `content-type` of `Dancer2::Serializer::JSON` will become `application/json; charset=utf-8`.

**Comment by veryrusty** [comment]
Sorry @JaHIY, the specs (see below) do not require it. If you have a use-case where adding this is needed, could you please document what is consuming the response so we can help sort out an alternative approach?

---

[RFC4627](http://www.ietf.org/rfc/rfc4627.txt) states
> JSON text SHALL be encoded in Unicode.  The default encoding is UTF-8

and goes on to explain how to determine the encoding of the octet stream.

Furthermore, the IANA assignment for [application/json](http://www.iana.org/assignments/media-types/application/json) (registered by RFC4627) includes the following note:

> No "charset" parameter is defined for this registration.
> Adding one really has no effect on compliant recipients.

**Comment by JaHIY** [comment]
@veryrusty Thank you for your explanation.
